import type { RecipeLanguage } from '@/types/recipe'

// Display labels only: canonical IDs/slugs and matching relationships stay unchanged.
// Order: English, German, French, Italian, Japanese, Brazilian Portuguese.
const LABELS: Record<string, readonly string[]> = {
  "pulpa-de-acai": ["Unsweetened açaí pulp","Ungesüßtes Açaí-Fruchtpüree","Pulpe d’açaí sans sucre","Polpa di açaí senza zucchero","無糖アサイーパルプ","Polpa de açaí sem açúcar"],
  "banana": ["Banana","Banane","Banane","Banana","バナナ","Banana"],
  "granola": ["Granola","Granola","Granola","Granola","グラノーラ","Granola"],
  "almendras": ["Almonds","Mandeln","Amandes","Mandorle","アーモンド","Amêndoas"],
  "bacalao": ["Fresh cod","Frischer Kabeljau","Cabillaud frais","Merluzzo fresco","生のタラ","Bacalhau fresco"],
  "almidon-de-maiz": ["Cornstarch","Maisstärke","Fécule de maïs","Amido di mais","コーンスターチ","Amido de milho"],
  "agua-con-gas": ["Sparkling water","Sprudelwasser","Eau gazeuse","Acqua frizzante","炭酸水","Água com gás"],
  "aceite-de-girasol": ["Sunflower oil","Sonnenblumenöl","Huile de tournesol","Olio di girasole","ひまわり油","Óleo de girassol"],
  "aceite-de-canola": ["Canola oil","Rapsöl","Huile de colza","Olio di colza","菜種油","Óleo de canola"],
  "cacao-en-polvo": ["Unsweetened cocoa powder","Ungesüßtes Kakaopulver","Cacao en poudre sans sucre","Cacao in polvere senza zucchero","無糖ココアパウダー","Cacau em pó sem açúcar"],
  "ketchup": ["Ketchup","Ketchup","Ketchup","Ketchup","ケチャップ","Ketchup"],
  "salsa-worcestershire": ["Worcestershire sauce","Worcestersauce","Sauce Worcestershire","Salsa Worcestershire","ウスターソース（Worcestershire）","Molho inglês"],
  "mayonesa": ["Mayonnaise","Mayonnaise","Mayonnaise","Maionese","マヨネーズ","Maionese"],
  "zumo-de-pina": ["Pineapple juice","Ananassaft","Jus d’ananas","Succo d’ananas","パイナップルジュース","Suco de abacaxi"],
  "crema-de-coco-endulzada": ["Sweetened cream of coconut","Gesüßte Kokoscreme","Crème de coco sucrée","Crema di cocco zuccherata","加糖ココナッツクリーム","Creme de coco adoçado"],
  "ron-blanco": ["White rum","Weißer Rum","Rhum blanc","Rum bianco","ホワイトラム","Rum branco"],
  "espresso": ["Brewed espresso","Zubereiteter Espresso","Espresso préparé","Espresso preparato","抽出したエスプレッソ","Espresso preparado"],
  "galletas-dulces-sencillas": ["Plain sweet biscuits","Einfache süße Kekse","Biscuits sucrés nature","Biscotti dolci semplici","シンプルな甘いビスケット","Biscoitos doces simples"],
  "aguacate": ["Avocado", "Avocado", "Avocat", "Avocado", "アボカド", "Abacate"],
  "brocoli": ["Broccoli", "Brokkoli", "Brocoli", "Broccoli", "ブロッコリー", "Brócolis"],
  "frijoles-negros": ["Black beans", "Schwarze Bohnen", "Haricots noirs", "Fagioli neri", "黒豆", "Feijão preto"],
  "arroz-integral": ["Brown rice", "Vollkornreis", "Riz complet", "Riso integrale", "玄米", "Arroz integral"],
  "tomates-cherry": ["Cherry tomatoes", "Kirschtomaten", "Tomates cerises", "Pomodorini", "ミニトマト", "Tomate-cereja"],
  "tofu": ["Tofu", "Tofu", "Tofu", "Tofu", "豆腐", "Tofu"],
  "semillas-de-sesamo": ["Sesame seeds", "Sesamsamen", "Graines de sésame", "Semi di sesamo", "ごま", "Gergelim"],
  "harina-de-maiz-precocida": ["Precooked corn flour", "Vorgekochtes Maismehl", "Farine de maïs précuite", "Farina di mais precotta", "加熱済みとうもろこし粉", "Farinha de milho pré-cozida"],
  "carne-desmechada": ["Shredded meat", "Gezupftes Fleisch", "Viande effilochée", "Carne sfilacciata", "ほぐした肉", "Carne desfiada"],
  "frijoles-refritos": ["Refried beans", "Bohnenmus", "Purée de haricots refrits", "Fagioli rifritti", "リフライドビーンズ", "Feijão refrito"],
  "tocineta": ["Bacon", "Bacon", "Bacon", "Bacon", "ベーコン", "Bacon"],
  "fresas": ["Strawberries", "Erdbeeren", "Fraises", "Fragole", "いちご", "Morangos"],
  "pina": ["Pineapple", "Ananas", "Ananas", "Ananas", "パイナップル", "Abacaxi"],
  "mango": ["Mango", "Mango", "Mangue", "Mango", "マンゴー", "Manga"],
  "sandia": ["Watermelon", "Wassermelone", "Pastèque", "Anguria", "すいか", "Melancia"],
  "kiwi": ["Kiwi", "Kiwi", "Kiwi", "Kiwi", "キウイ", "Kiwi"],
  "uvas": ["Grapes", "Trauben", "Raisins", "Uva", "ぶどう", "Uvas"],
  "moras": ["Blackberries", "Brombeeren", "Mûres", "More", "ブラックベリー", "Amoras"],
  "frambuesas": ["Raspberries", "Himbeeren", "Framboises", "Lamponi", "ラズベリー", "Framboesas"],
  "platano": ["Plantain", "Kochbanane", "Banane plantain", "Platano", "プランテン", "Banana-da-terra"],
  "leche-de-almendras": ["Almond milk", "Mandelmilch", "Lait d’amande", "Latte di mandorla", "アーモンドミルク", "Leite de amêndoas"],
  "manzana": ["Apple", "Apfel", "Pomme", "Mela", "りんご", "Maçã"],
  "pepino": ["Cucumber", "Gurke", "Concombre", "Cetriolo", "きゅうり", "Pepino"],
  "yogur-griego": ["Greek yogurt", "Griechischer Joghurt", "Yaourt grec", "Yogurt greco", "ギリシャヨーグルト", "Iogurte grego"],
  "semillas-de-chia": ["Chia seeds", "Chiasamen", "Graines de chia", "Semi di chia", "チアシード", "Sementes de chia"],
  "quinoa": ["Quinoa", "Quinoa", "Quinoa", "Quinoa", "キヌア", "Quinoa"],
  "garbanzos": ["Chickpeas", "Kichererbsen", "Pois chiches", "Ceci", "ひよこ豆", "Grão-de-bico"],
  "calabacin": ["Zucchini", "Zucchini", "Courgette", "Zucchina", "ズッキーニ", "Abobrinha"],
  "tahini": ["Tahini", "Tahini", "Tahini", "Tahina", "タヒニ", "Tahine"],
  "menta": ["Mint", "Minze", "Menthe", "Menta", "ミント", "Hortelã"],
  "caldo-de-pollo": ["Chicken broth", "Hühnerbrühe", "Bouillon de poulet", "Brodo di pollo", "チキンブロス", "Caldo de frango"],
  "mazorca": ["Corn on the cob", "Maiskolben", "Épi de maïs", "Pannocchia", "とうもろこし", "Espiga de milho"],
  "papa-criolla": ["Papa criolla potato", "Papa-criolla-Kartoffel", "Pomme de terre papa criolla", "Patata papa criolla", "パパ・クリオージャ", "Batata papa criolla"],
  "papa-blanca": ["White potato", "Weiße Kartoffel", "Pomme de terre blanche", "Patata bianca", "白いじゃがいも", "Batata branca"],
  "alcaparras": ["Capers", "Kapern", "Câpres", "Capperi", "ケッパー", "Alcaparras"],
  "arandanos": ["Blueberries", "Heidelbeeren", "Myrtilles", "Mirtilli", "ブルーベリー", "Mirtilos"],
  "bicarbonato-de-sodio": ["Baking soda", "Natron", "Bicarbonate de soude", "Bicarbonato di sodio", "重曹", "Bicarbonato de sódio"],
  "carne-molida-de-res": ["Ground beef", "Rinderhackfleisch", "Bœuf haché", "Carne macinata di manzo", "牛ひき肉", "Carne bovina moída"],
  "mostaza-dijon": ["Dijon mustard", "Dijon-Senf", "Moutarde de Dijon", "Senape di Digione", "ディジョンマスタード", "Mostarda Dijon"],
  "polvo-de-hornear": ["Baking powder", "Backpulver", "Levure chimique", "Lievito per dolci", "ベーキングパウダー", "Fermento químico"],
  "queso-mozzarella": ["Mozzarella", "Mozzarella", "Mozzarella", "Mozzarella", "モッツァレラ", "Queijo muçarela"],
  "queso-ricotta": ["Ricotta", "Ricotta", "Ricotta", "Ricotta", "リコッタ", "Ricota"],
  "vinagre-de-manzana": ["Apple cider vinegar", "Apfelessig", "Vinaigre de cidre", "Aceto di mele", "りんご酢", "Vinagre de maçã"],
  "zanahoria": ["Carrot", "Karotte", "Carotte", "Carota", "にんじん", "Cenoura"],
  "hielo": ["Ice", "Eis", "Glace", "Ghiaccio", "氷", "Gelo"],
  "arroz-blanco-cocido": ["Cooked white rice", "Gekochter weißer Reis", "Riz blanc cuit", "Riso bianco cotto", "炊いた白米", "Arroz branco cozido"],
  "ajo": ["Garlic", "Knoblauch", "Ail", "Aglio", "にんにく", "Alho"],
  "huevo": ["Egg", "Ei", "Œuf", "Uovo", "卵", "Ovo"],
  "aceite-de-oliva": ["Olive oil", "Olivenöl", "Huile d’olive", "Olio d’oliva", "オリーブオイル", "Azeite de oliva"],
  "comino": ["Cumin", "Kreuzkümmel", "Cumin", "Cumino", "クミン", "Cominho"],
  "pimienta-negra": ["Black pepper", "Schwarzer Pfeffer", "Poivre noir", "Pepe nero", "黒こしょう", "Pimenta-do-reino"],
  "sal": ["Salt", "Salz", "Sel", "Sale", "塩", "Sal"],
  "azucar": ["Sugar", "Zucker", "Sucre", "Zucchero", "砂糖", "Açúcar"],
  "agua": ["Water", "Wasser", "Eau", "Acqua", "水", "Água"],
  "extracto-de-vainilla": ["Vanilla extract", "Vanilleextrakt", "Extrait de vanille", "Estratto di vaniglia", "バニラエキストラクト", "Extrato de baunilha"],
  "cebolla": ["Onion", "Zwiebel", "Oignon", "Cipolla", "玉ねぎ", "Cebola"],
  "leche": ["Milk", "Milch", "Lait", "Latte", "牛乳", "Leite"],
  "arroz": ["Rice", "Reis", "Riz", "Riso", "米", "Arroz"],
  "cebolla-larga": ["Scallion", "Frühlingszwiebel", "Ciboule", "Cipollotto", "青ねぎ", "Cebolinha"],
  "berenjena": ["Eggplant", "Aubergine", "Aubergine", "Melanzana", "なす", "Berinjela"],
  "guisantes": ["Peas", "Erbsen", "Petits pois", "Piselli", "グリーンピース", "Ervilhas"],
  "champiñones": ["Button mushrooms", "Champignons", "Champignons de Paris", "Champignon", "マッシュルーム", "Champignons"],
  "caldo-de-res": ["Beef broth", "Rinderbrühe", "Bouillon de bœuf", "Brodo di manzo", "ビーフブロス", "Caldo de carne"],
  "camarones": ["Shrimp", "Garnelen", "Crevettes", "Gamberi", "えび", "Camarões"],
  "carne-molida": ["Ground meat", "Hackfleisch", "Viande hachée", "Carne macinata", "ひき肉", "Carne moída"],
  "pimiento-verde": ["Green bell pepper", "Grüne Paprika", "Poivron vert", "Peperone verde", "緑パプリカ", "Pimentão verde"],
  "chile-molido": ["Ground chili", "Gemahlene Chili", "Piment moulu", "Peperoncino macinato", "粉唐辛子", "Pimenta em pó"],
  "achiote": ["Annatto", "Annatto", "Rocou", "Annatto", "アナトー", "Urucum"],
  "frijol-cargamanto": ["Cargamanto beans", "Cargamanto-Bohnen", "Haricots cargamanto", "Fagioli cargamanto", "カルガマント豆", "Feijão cargamanto"],
  "hojas-de-platano": ["Banana leaves", "Bananenblätter", "Feuilles de bananier", "Foglie di banano", "バナナの葉", "Folhas de bananeira"],
  "albahaca-seca": ["Dried basil", "Getrocknetes Basilikum", "Basilic séché", "Basilico secco", "乾燥バジル", "Manjericão seco"],
  "espinacas": ["Spinach", "Spinat", "Épinards", "Spinaci", "ほうれん草", "Espinafre"],
  "limon": ["Lemon", "Zitrone", "Citron", "Limone", "レモン", "Limão"],
  "pan-rallado": ["Breadcrumbs", "Paniermehl", "Chapelure", "Pangrattato", "パン粉", "Farinha de rosca"],
  "perejil": ["Parsley", "Petersilie", "Persil", "Prezzemolo", "パセリ", "Salsinha"],
  "pimiento-rojo": ["Red bell pepper", "Rote Paprika", "Poivron rouge", "Peperone rosso", "赤パプリカ", "Pimentão vermelho"],
  "salsa-de-tomate": ["Tomato sauce", "Tomatensauce", "Sauce tomate", "Salsa di pomodoro", "トマトソース", "Molho de tomate"],
  "tomate": ["Tomato", "Tomate", "Tomate", "Pomodoro", "トマト", "Tomate"],
  "agua-fria": ["Cold water", "Kaltes Wasser", "Eau froide", "Acqua fredda", "冷水", "Água fria"],
  "manteca-de-cerdo": ["Lard", "Schweineschmalz", "Saindoux", "Strutto", "ラード", "Banha de porco"],
  "panceta-de-cerdo": ["Pork belly", "Schweinebauch", "Poitrine de porc", "Pancetta di maiale", "豚バラ肉", "Barriga de porco"],
  "carne-de-cerdo": ["Pork", "Schweinefleisch", "Porc", "Carne di maiale", "豚肉", "Carne de porco"],
  "pollo": ["Chicken", "Hähnchen", "Poulet", "Pollo", "鶏肉", "Frango"],
  "papas": ["Potatoes", "Kartoffeln", "Pommes de terre", "Patate", "じゃがいも", "Batatas"],
  "pasta-para-canelones": ["Cannelloni pasta", "Cannelloni", "Pâtes à cannelloni", "Pasta per cannelloni", "カネロニ", "Massa para canelone"],
  "galletas": ["Cookies", "Kekse", "Biscuits", "Biscotti", "ビスケット", "Biscoitos"],
  "maracuya": ["Passion fruit", "Passionsfrucht", "Fruit de la passion", "Frutto della passione", "パッションフルーツ", "Maracujá"],
  "leche-condensada": ["Condensed milk", "Kondensmilch", "Lait concentré", "Latte condensato", "練乳", "Leite condensado"],
  "repollo": ["Cabbage", "Kohl", "Chou", "Cavolo", "キャベツ", "Repolho"],
  "sake": ["Sake", "Sake", "Saké", "Sake", "日本酒", "Saquê"],
  "pan-blanco": ["White bread", "Weißbrot", "Pain blanc", "Pane bianco", "白パン", "Pão branco"],
  "vinagre-blanco": ["White vinegar", "Weißer Essig", "Vinaigre blanc", "Aceto bianco", "ホワイトビネガー", "Vinagre branco"],
  "queso-rallado": ["Grated cheese", "Geriebener Käse", "Fromage râpé", "Formaggio grattugiato", "おろしたチーズ", "Queijo ralado"],
  "tortillas-de-harina": ["Flour tortillas", "Weizentortillas", "Tortillas de blé", "Tortillas di farina", "小麦トルティーヤ", "Tortilhas de trigo"],
  "papa-sabanera": ["Sabanera potato", "Sabanera-Kartoffel", "Pomme de terre sabanera", "Patata sabanera", "サバネラ種のじゃがいも", "Batata sabanera"],
  "guascas": ["Guascas", "Guascas", "Guascas", "Guascas", "グアスカス", "Guascas"],
  "semillas-de-granada": ["Pomegranate seeds", "Granatapfelkerne", "Graines de grenade", "Chicchi di melograno", "ざくろの実", "Sementes de romã"],
  "mirin": ["Mirin", "Mirin", "Mirin", "Mirin", "みりん", "Mirin"],
  "oregano-seco": ["Dried oregano", "Getrockneter Oregano", "Origan séché", "Origano secco", "乾燥オレガノ", "Orégano seco"],
  "harina-de-trigo": ["Wheat flour", "Weizenmehl", "Farine de blé", "Farina di frumento", "小麦粉", "Farinha de trigo"],
  "pimenton-dulce": ["Sweet paprika", "Edelsüßes Paprikapulver", "Paprika doux", "Paprika dolce", "甘口パプリカパウダー", "Páprica doce"],
  "aceite-vegetal": ["Vegetable oil", "Pflanzenöl", "Huile végétale", "Olio vegetale", "植物油", "Óleo vegetal"],
  "mantequilla": ["Butter", "Butter", "Beurre", "Burro", "バター", "Manteiga"],
  "miel": ["Honey", "Honig", "Miel", "Miele", "はちみつ", "Mel"],
  "queso-parmesano": ["Parmesan", "Parmesan", "Parmesan", "Parmigiano", "パルメザン", "Queijo parmesão"],
  "cilantro": ["Cilantro", "Koriandergrün", "Coriandre", "Coriandolo", "パクチー", "Coentro"],
  "crema-de-leche": ["Cream", "Sahne", "Crème", "Panna", "生クリーム", "Creme de leite"],
  "jengibre": ["Ginger", "Ingwer", "Gingembre", "Zenzero", "しょうが", "Gengibre"],
  "laurel": ["Bay leaf", "Lorbeerblatt", "Laurier", "Alloro", "ローリエ", "Louro"],
  "salsa-de-soja": ["Soy sauce", "Sojasauce", "Sauce soja", "Salsa di soia", "しょうゆ", "Molho de soja"],
  "vino-blanco": ["White wine", "Weißwein", "Vin blanc", "Vino bianco", "白ワイン", "Vinho branco"],
  "hogao": ["Hogao", "Hogao", "Hogao", "Hogao", "ホガオ", "Hogao"],
  "bondiola-de-cerdo": ["Pork collar", "Schweinenacken", "Échine de porc", "Coppa di maiale", "豚肩ロース", "Copa-lombo suíno"],
  "pimenton": ["Paprika", "Paprikapulver", "Paprika", "Paprika", "パプリカパウダー", "Páprica"],
  "platano-verde": ["Green plantain", "Grüne Kochbanane", "Banane plantain verte", "Platano verde", "青いプランテン", "Banana-da-terra verde"],
  "ternera": ["Veal", "Kalbfleisch", "Veau", "Vitello", "仔牛肉", "Vitela"],
  "arveja-amarilla": ["Yellow peas", "Gelbe Erbsen", "Pois jaunes", "Piselli gialli", "黄えんどう豆", "Ervilha amarela"],
  "cebolleta": ["Spring onion", "Frühlingszwiebel", "Oignon nouveau", "Cipollotto", "青ねぎ", "Cebolinha"],
}

const INDEX = { en: 0, de: 1, fr: 2, it: 3, ja: 4, pt: 5 } as const

export function ingredientLabel(slug: string, fallback: string, lang: RecipeLanguage): string {
  return lang === 'es' ? fallback : LABELS[slug]?.[INDEX[lang]] ?? fallback
}
