import type { LegalPageContentMap } from '@/lib/legal-content'

export const PRIVACIDAD_CONTENT: LegalPageContentMap = {
  es: {
    metaTitle: 'Privacidad | Manual de Cocina',
    metaDescription: 'Cómo funciona actualmente Manual de Cocina en materia de privacidad: qué datos se tratan y cuáles no.',
    eyebrow: 'Privacidad',
    title: 'Privacidad',
    intro: 'Esta página describe, a nivel informativo, cómo funciona actualmente el sitio.',
    sections: [
      { heading: 'Datos y servicios', html: '<p>Las páginas públicas consultan contenido editorial almacenado en Supabase. El sitio se aloja mediante infraestructura de Hostinger.</p>' },
      { heading: 'Cuentas y datos personales', html: '<p>El sitio es de solo lectura para las personas visitantes: no se requiere crear una cuenta ni se recopilan datos personales para navegar, buscar o leer recetas.</p>' },
      { heading: 'Favoritas', html: '<p>La función de guardar recetas utiliza almacenamiento local del navegador (localStorage) para recordar las recetas guardadas en ese dispositivo. Esta información no se envía a nuestros servidores ni se comparte con nadie.</p>' },
      { heading: 'Publicidad y analítica', html: '<p>No utilizamos Google Analytics ni ningún otro servicio de analítica o seguimiento. La única publicidad prevista para el sitio es Google AdSense; no se utilizará ningún otro servicio publicitario. AdSense no se considera activo hasta completar su integración técnica y las medidas de consentimiento correspondientes.</p>' },
      { heading: 'Contacto', html: '<p>Si escribes a hola@manualdecocina.com, la información del mensaje se utilizará únicamente para atender tu consulta. No envíes información sensible que no sea necesaria para la consulta.</p>' },
    ],
  },
  en: {
    metaTitle: 'Privacy | Manual de Cocina',
    metaDescription: 'How Manual de Cocina currently works regarding privacy: what data is handled and what is not.',
    eyebrow: 'Privacy',
    title: 'Privacy',
    intro: 'This page describes, for information purposes, how the site currently works.',
    sections: [
      { heading: 'Data and services', html: '<p>Public pages read editorial content stored in Supabase. The site is hosted on Hostinger infrastructure.</p>' },
      { heading: 'Accounts and personal data', html: '<p>The site is read-only for visitors: no account is required and no personal data is collected to browse, search or read recipes.</p>' },
      { heading: 'Favorites', html: '<p>The save-recipe feature uses local browser storage (localStorage) to remember the recipes saved on that device. This information is not sent to our servers or shared with anyone.</p>' },
      { heading: 'Advertising and analytics', html: "<p>We don't use Google Analytics or any other analytics or tracking service. The only advertising planned for the site is Google AdSense; no other advertising service will be used. AdSense is not considered active until its technical integration and the corresponding consent measures are completed.</p>" },
      { heading: 'Contact', html: "<p>If you write to hola@manualdecocina.com, the information in your message will be used only to handle your inquiry. Please don't send sensitive information that isn't necessary for the inquiry.</p>" },
    ],
  },
  de: {
    metaTitle: 'Datenschutz | Manual de Cocina',
    metaDescription: 'Wie Manual de Cocina derzeit in Sachen Datenschutz funktioniert: welche Daten verarbeitet werden und welche nicht.',
    eyebrow: 'Datenschutz',
    title: 'Datenschutz',
    intro: 'Diese Seite beschreibt informativ, wie die Website derzeit funktioniert.',
    sections: [
      { heading: 'Daten und Dienste', html: '<p>Die öffentlichen Seiten greifen auf redaktionelle Inhalte zu, die in Supabase gespeichert sind. Die Website wird auf der Infrastruktur von Hostinger gehostet.</p>' },
      { heading: 'Konten und personenbezogene Daten', html: '<p>Die Website ist für Besucherinnen und Besucher nur lesbar: Es ist kein Konto erforderlich, und es werden keine personenbezogenen Daten erhoben, um zu stöbern, zu suchen oder Rezepte zu lesen.</p>' },
      { heading: 'Favoriten', html: '<p>Die Funktion zum Speichern von Rezepten nutzt den lokalen Speicher des Browsers (localStorage), um die auf diesem Gerät gespeicherten Rezepte zu merken. Diese Informationen werden nicht an unsere Server gesendet oder mit jemandem geteilt.</p>' },
      { heading: 'Werbung und Analyse', html: '<p>Wir verwenden weder Google Analytics noch einen anderen Analyse- oder Tracking-Dienst. Die einzige für die Website geplante Werbung ist Google AdSense; es wird kein anderer Werbedienst genutzt. AdSense gilt erst als aktiv, wenn die technische Integration und die entsprechenden Einwilligungsmaßnahmen abgeschlossen sind.</p>' },
      { heading: 'Kontakt', html: '<p>Wenn du an hola@manualdecocina.com schreibst, werden die Informationen der Nachricht ausschließlich zur Bearbeitung deiner Anfrage verwendet. Sende bitte keine sensiblen Informationen, die für die Anfrage nicht notwendig sind.</p>' },
    ],
  },
  fr: {
    metaTitle: 'Confidentialité | Manual de Cocina',
    metaDescription: 'Comment Manual de Cocina fonctionne actuellement en matière de confidentialité : quelles données sont traitées et lesquelles ne le sont pas.',
    eyebrow: 'Confidentialité',
    title: 'Confidentialité',
    intro: 'Cette page décrit, à titre informatif, le fonctionnement actuel du site.',
    sections: [
      { heading: 'Données et services', html: "<p>Les pages publiques consultent du contenu éditorial stocké dans Supabase. Le site est hébergé sur l'infrastructure de Hostinger.</p>" },
      { heading: 'Comptes et données personnelles', html: "<p>Le site est en lecture seule pour les visiteurs : aucun compte n'est requis et aucune donnée personnelle n'est collectée pour naviguer, chercher ou lire des recettes.</p>" },
      { heading: 'Favoris', html: "<p>La fonction d'enregistrement des recettes utilise le stockage local du navigateur (localStorage) pour mémoriser les recettes enregistrées sur cet appareil. Cette information n'est envoyée à aucun de nos serveurs ni partagée avec qui que ce soit.</p>" },
      { heading: 'Publicité et analyse', html: "<p>Nous n'utilisons ni Google Analytics ni aucun autre service d'analyse ou de suivi. La seule publicité prévue pour le site est Google AdSense ; aucun autre service publicitaire ne sera utilisé. AdSense n'est pas considéré comme actif tant que son intégration technique et les mesures de consentement correspondantes ne sont pas terminées.</p>" },
      { heading: 'Contact', html: "<p>Si tu écris à hola@manualdecocina.com, les informations du message seront utilisées uniquement pour traiter ta demande. Merci de ne pas envoyer d'informations sensibles qui ne sont pas nécessaires à la demande.</p>" },
    ],
  },
  it: {
    metaTitle: 'Privacy | Manual de Cocina',
    metaDescription: 'Come funziona attualmente Manual de Cocina in materia di privacy: quali dati vengono trattati e quali no.',
    eyebrow: 'Privacy',
    title: 'Privacy',
    intro: 'Questa pagina descrive, a titolo informativo, come funziona attualmente il sito.',
    sections: [
      { heading: 'Dati e servizi', html: "<p>Le pagine pubbliche consultano contenuti editoriali archiviati in Supabase. Il sito è ospitato sull'infrastruttura di Hostinger.</p>" },
      { heading: 'Account e dati personali', html: '<p>Il sito è di sola lettura per le persone visitatrici: non è richiesto creare un account né vengono raccolti dati personali per navigare, cercare o leggere ricette.</p>' },
      { heading: 'Preferiti', html: "<p>La funzione di salvataggio delle ricette utilizza l'archiviazione locale del browser (localStorage) per ricordare le ricette salvate su quel dispositivo. Questa informazione non viene inviata ai nostri server né condivisa con nessuno.</p>" },
      { heading: 'Pubblicità e analisi', html: "<p>Non utilizziamo Google Analytics né alcun altro servizio di analisi o tracciamento. L'unica pubblicità prevista per il sito è Google AdSense; non verrà utilizzato alcun altro servizio pubblicitario. AdSense non si considera attivo finché non siano completate la sua integrazione tecnica e le relative misure di consenso.</p>" },
      { heading: 'Contatti', html: '<p>Se scrivi a hola@manualdecocina.com, le informazioni del messaggio saranno utilizzate solo per gestire la tua richiesta. Ti chiediamo di non inviare informazioni sensibili non necessarie alla richiesta.</p>' },
    ],
  },
  ja: {
    metaTitle: 'プライバシー | Manual de Cocina',
    metaDescription: 'Manual de Cocinaのプライバシーに関する現在の運用について：取り扱うデータと取り扱わないデータ。',
    eyebrow: 'プライバシー',
    title: 'プライバシー',
    intro: 'このページは、当サイトが現在どのように機能しているかを情報提供の目的で説明するものです。',
    sections: [
      { heading: 'データとサービス', html: '<p>公開ページはSupabaseに保存された編集コンテンツを参照しています。サイトはHostingerのインフラでホスティングされています。</p>' },
      { heading: 'アカウントと個人情報', html: '<p>当サイトは訪問者にとって閲覧専用です。閲覧、検索、レシピの読了にアカウント登録は不要で、個人情報の収集も行っていません。</p>' },
      { heading: 'お気に入り', html: '<p>レシピ保存機能はブラウザのローカルストレージ（localStorage）を使用し、その端末に保存したレシピを記憶します。この情報は当社のサーバーに送信されることも、第三者と共有されることもありません。</p>' },
      { heading: '広告と解析', html: '<p>Google Analyticsやその他の解析・トラッキングサービスは使用していません。当サイトで予定している広告はGoogle AdSenseのみで、ほかの広告サービスは使用しません。技術的な導入と、それに対応する同意対策が完了するまで、AdSenseは稼働しているとはみなしません。</p>' },
      { heading: 'お問い合わせ', html: '<p>hola@manualdecocina.comにご連絡いただいた場合、メッセージの内容はお問い合わせへの対応にのみ使用します。お問い合わせに不要な機密情報は送信しないようお願いいたします。</p>' },
    ],
  },
  pt: {
    metaTitle: 'Privacidade | Manual de Cocina',
    metaDescription: 'Como o Manual de Cocina funciona atualmente em matéria de privacidade: quais dados são tratados e quais não são.',
    eyebrow: 'Privacidade',
    title: 'Privacidade',
    intro: 'Esta página descreve, a título informativo, como o site funciona atualmente.',
    sections: [
      { heading: 'Dados e serviços', html: '<p>As páginas públicas consultam conteúdo editorial armazenado no Supabase. O site é hospedado na infraestrutura da Hostinger.</p>' },
      { heading: 'Contas e dados pessoais', html: '<p>O site é somente leitura para as pessoas visitantes: não é necessário criar uma conta nem são coletados dados pessoais para navegar, buscar ou ler receitas.</p>' },
      { heading: 'Favoritos', html: '<p>A função de salvar receitas utiliza armazenamento local do navegador (localStorage) para lembrar as receitas salvas naquele dispositivo. Essa informação não é enviada aos nossos servidores nem compartilhada com ninguém.</p>' },
      { heading: 'Publicidade e análise', html: '<p>Não utilizamos o Google Analytics nem nenhum outro serviço de análise ou rastreamento. A única publicidade prevista para o site é o Google AdSense; nenhum outro serviço de publicidade será utilizado. O AdSense não é considerado ativo até que sua integração técnica e as medidas de consentimento correspondentes sejam concluídas.</p>' },
      { heading: 'Contato', html: '<p>Se você escrever para hola@manualdecocina.com, as informações da mensagem serão usadas apenas para atender à sua solicitação. Não envie informações sensíveis que não sejam necessárias para a solicitação.</p>' },
    ],
  },
}
