"""Authored IT/JA/PT-BR localizations; retain every quantity and safety step."""
import json
from pathlib import Path
p=Path(__file__).resolve().parents[1]/'editorial/receta-de-feijoada-localizaciones-20261008.json'
data=json.loads(p.read_text()); assert set(data)=={'en','de','fr'}
data.update({
'it':{
'path':'/it/feijoada-ricetta','historical_path':True,'title':'Feijoada casalinga con fagioli neri e maiale','seo_title':'Feijoada casalinga con fagioli neri e maiale',
'excerpt':'Feijoada casalinga per 8 con fagioli neri, maiale, pancetta e salsiccia affumicata: ammollo, bollitura iniziale, cottura lenta e conservazione.',
'summary':'Questa feijoada casalinga unisce fagioli neri, spalla di maiale fresca, pancetta e salsiccia affumicata completamente cotta in un brodo scuro addensato con parte degli stessi fagioli. È un adattamento con ingredienti ben identificati, senza carni salate da dissalare; non rappresenta tutte le varianti brasiliane.\n\nLa proposta rende 8 porzioni di stufato. I 680 minuti stimati comprendono 8 ore di ammollo in frigorifero, 30 minuti di preparazione, 160 di cottura e 10 di riposo. Il soffritto si prepara mentre bollono i fagioli. Quantità, resa e tempi attendono conferma con una prova in cucina; contano morbidezza e temperatura, non solo l’orologio.',
'difficulty':'Media','course':'Piatto principale','cuisine':'Brasiliana, adattamento casalingo',
'ingredients':['Fagioli neri secchi','Spalla di maiale fresca disossata','Salsiccia di maiale affumicata completamente cotta','Pancetta cruda','Cipolla','Aglio','Olio d’oliva','Sale','Pepe nero','Acqua di cottura','Alloro secco, da togliere'],
'groups':{'Alubias y cocción':'Fagioli e cottura','Carnes':'Carni','Sofrito y sazón':'Soffritto e condimento'},'units':{'hojas':'foglie'},
'steps':[
['Ammolla i fagioli in frigorifero','Controlla i 500 g di fagioli neri secchi, elimina sassolini e chicchi rovinati e sciacqua. Mettili in un recipiente ampio con circa 1,5 litri d’acqua, coperti di diversi centimetri. Copri e ammolla 8 ore in frigorifero a 4 °C o meno; aggiungi acqua se viene assorbita. Alla fine getta tutta l’acqua d’ammollo e sciacqua. Quest’acqua è aggiuntiva rispetto ai 2,5 litri per la cottura.'],
['Prepara e separa la carne cruda','Trita i 200 g di cipolla e i 20 g d’aglio su un tagliere pulito per vegetali. Su un altro tagliere per carne cruda taglia i 400 g di spalla fresca disossata a cubetti di circa 3 cm e i 100 g di pancetta a strisce corte. Affetta i 250 g di salsiccia a rondelle di 1 cm; scegli un prodotto indicato come completamente cotto, non salsiccia fresca né carne salata da dissalare. Tieni le carni al freddo fino alla cottura e lava mani e utensili dopo aver toccato maiale crudo.'],
['Fai bollire i fagioli prima di abbassare il fuoco','Versa i fagioli scolati in una pentola da almeno 6 litri con i 2,5 litri d’acqua fresca e le 2 foglie d’alloro. Porta a ebollizione, circa 15 minuti indicativi, poi mantieni un bollore evidente per almeno 30 minuti senza coperchio, controllando schiuma e traboccamenti. Schiuma con un cucchiaio; aggiungi acqua bollente se i fagioli non sono più coperti. Non assaggiare fagioli crudi o duri e non sostituire questa fase con una slow cooker.'],
['Rosola carni e aromi','Durante la bollitura scalda una padella ampia a fuoco medio con i 15 g d’olio. Cuoci la pancetta circa 5 minuti, mescolando, finché inizia a dorare. Aggiungi il maiale in due riprese, circa 4 minuti ciascuna, solo per dorare l’esterno; finirà di cuocere nello stufato. Togli le carni su un piatto dedicato. Nella stessa padella fai soffriggere la cipolla 7 minuti, l’aglio 1 minuto e la salsiccia 4 minuti. Conserva tutto, grasso compreso: la stima nutrizionale lo conta interamente.'],
['Cuoci lo stufato finché è tenero','Dopo i 30 minuti di bollitura unisci alla pentola carni, salsiccia, soffritto e succhi della padella, raschiandola con poco brodo caldo. Aggiungi 1 g di pepe; lascia il sale per la fine. Riporta a lieve bollore e cuoci circa 100 minuti con coperchio socchiuso, mescolando dal fondo ogni 15–20 minuti. Tieni fagioli e carni appena coperti e aggiungi acqua bollente a incrementi di 100 ml se necessario. Evita che si attacchino o che un bollore troppo forte disfi tutti i fagioli.'],
['Controlla temperatura e consistenza','Con termometro pulito misura il centro di diversi cubetti di maiale: questo stufato adotta un obiettivo pratico di almeno 74 °C, superiore al minimo per tagli interi. La carne deve inoltre cedere facilmente sotto una forchetta, e un fagiolo preso con cucchiaio deve essere cremoso all’interno senza nucleo duro. Se qualcosa è ancora tenace o la temperatura è insufficiente, prolunga e controlla di nuovo; i tempi sono proposti, non garantiti. Non assaggiare con utensili che hanno toccato carne cruda.'],
['Addensa, sala e lascia riposare','Preleva un mestolo di fagioli morbidi senza carne, schiacciali in una ciotola e rimetti la pasta nella pentola. Cuoci dolcemente circa altri 15 minuti mescolando, finché il brodo vela leggermente il dorso di un cucchiaio; se troppo denso aggiungi acqua bollente. Togli le 2 foglie d’alloro. Assaggia solo ora e aggiungi i 4 g di sale previsti, o meno se gli insaccati sono già sapidi; meno sale modifica la stima del sodio. Spegni e lascia riposare 10 minuti coperto.'],
['Porziona e raffredda rapidamente','Dividi lo stufato in 8 porzioni con quantità simili di fagioli, carni e brodo. Puoi accompagnare con riso, arancia o farofa, esclusi da ingredienti e nutrizione. Per conservare dividi subito gli avanzi in piccoli contenitori bassi e refrigera a 4 °C o meno entro 2 ore, o 1 ora se l’ambiente supera 32 °C; non aspettare che la pentola grande si raffreddi interamente fuori. Consuma in 3–4 giorni o congela porzioni; 2 mesi è un limite di qualità proposto. Scongela in frigorifero e riscalda mescolando fino ad almeno 74 °C in più punti.']],
'notes':'Usa fagioli neri secchi; non sostituirli con fagioli già cotti mantenendo queste quantità e tempi. Questa versione non contiene carne essiccata, orecchio o piedino di maiale; aggiungerli richiede un altro procedimento e calcolo nutrizionale. La salsiccia deve risultare completamente cotta dalla confezione: affumicata non significa sempre cotta. Va bene linguiça cotta o salsiccia di maiale affumicata equivalente; marca e prodotto cambiano gusto e sodio. La spalla fresca non si dissala. Diluisci con acqua bollente e addensa schiacciando fagioli cotti anziché aggiungere farina. Non unire ingredienti acidi prima che i fagioli siano teneri. Il riposo fuori dal fuoco non sostituisce la rapida refrigerazione degli avanzi.',
'faq':[['Posso saltare l’ammollo?','La proposta parte da 8 ore di ammollo refrigerato e acqua nuova per cuocere. Non viene fornito un tempo equivalente senza ammollo; il procedimento cambia e resta necessaria la bollitura iniziale di 30 minuti.'],['Perché i fagioli rimangono duri?','Fagioli vecchi, acqua dura o ingredienti acidi aggiunti presto possono allungare la cottura. Mantieni acqua calda sufficiente e cuoci finché non resta un nucleo duro; sala alla fine come previsto.'],['Come addenso senza farina?','Schiaccia un mestolo di fagioli teneri senza carne e rimettilo nello stufato. Cuoci dolcemente altri 15 minuti mescolando; aggiungi acqua bollente se troppo denso.']],
'keywords':['feijoada casalinga','feijoada fagioli neri','stufato di maiale e fagioli neri'],
'cover_alt':'Feijoada di fagioli neri con maiale, pancetta e rondelle di salsiccia affumicata in brodo scuro',
'nutrition':{'serving_size':'1 di 8 porzioni di stufato, senza accompagnamenti','method':'Dieci schede USDA verificate, pesi crudi edibili di fagioli, maiale e pancetta e peso della salsiccia già cotta; somma divisa per 8. La salsiccia affumicata è approssimata con una scheda generica di salsiccia di maiale affumicata, non una scheda specifica di linguiça brasiliana. Sono conteggiati tutto il grasso e il brodo trattenuto. Alloro tolto e acqua d’ammollo gettata esclusi.','note':'Stima informativa, non analisi dello stufato finito. Marca e sale degli insaccati, ammollo, resa e distribuzione del brodo cambiano i valori. Riso, arancia, farofa e verdure di accompagnamento esclusi.'}
},
'ja':{
'path':'/ja/feijoada','historical_path':False,'title':'黒豆と豚肉の家庭風フェイジョアーダ','seo_title':'黒豆と豚肉の家庭風フェイジョアーダ',
'excerpt':'黒豆、豚肉、ベーコン、燻製ソーセージで作る8人分の家庭風フェイジョアーダ。浸水、沸騰、煮込み、保存まで順に紹介します。',
'summary':'この家庭風フェイジョアーダは、黒豆、生の豚肩肉、ベーコン、十分に加熱済みの燻製ソーセージを使い、豆の一部をつぶして黒い煮汁にとろみをつけます。材料を明確にした家庭向けのアレンジで、塩抜きが必要な肉は使いません。ブラジルのすべての作り方を代表するものではありません。\n\n煮込み8人分を想定しています。推定680分の内訳は冷蔵庫での浸水8時間、準備30分、調理160分、休ませる時間10分です。炒める工程は豆を沸騰させている間に行います。分量、出来上がり量、時間は調理試作による確認前の目安で、時計だけでなく柔らかさと温度を確かめます。',
'difficulty':'中級','course':'主菜','cuisine':'ブラジル料理の家庭向けアレンジ',
'ingredients':['乾燥黒豆','生の骨なし豚肩肉','十分に加熱済みの豚肉の燻製ソーセージ','未加熱のベーコン','玉ねぎ','にんにく','オリーブオイル','塩','黒こしょう','煮込み用の水','乾燥ローリエ、最後に取り除く'],
'groups':{'Alubias y cocción':'豆と煮込み用','Carnes':'肉類','Sofrito y sazón':'香味野菜と調味料'},'units':{'hojas':'枚'},
'steps':[
['豆を冷蔵庫で浸水する','乾燥黒豆500 gを確認して小石や傷んだ豆を除き、すすぎます。大きめの容器に入れ、水約1.5リットルで豆の上数cmまで覆います。ふたをして4 °C以下の冷蔵庫で8時間浸し、水が吸収されたら足します。終わったら浸水した水をすべて捨ててすすぎます。この水は煮込み用の2.5リットルとは別です。'],
['材料を準備して生肉を分ける','清潔な野菜用まな板で玉ねぎ200 gとにんにく20 gをみじん切りにします。別の生肉用まな板で、生の骨なし豚肩肉400 gを約3 cm角、ベーコン100 gを短い細切りにします。ソーセージ250 gは厚さ1 cmの輪切りにします。表示が十分に加熱済みの製品を使い、生ソーセージや塩抜きが必要な肉は使いません。肉は調理まで冷蔵し、生の豚肉に触れた後は手と器具を洗います。'],
['火を弱める前に豆を沸騰させる','水を切った豆を容量6リットル以上の鍋に入れ、新しい水2.5リットルとローリエ2枚を加えます。目安約15分で沸騰させ、泡や吹きこぼれを確認できるようふたをせず、はっきり沸騰した状態を少なくとも30分保ちます。泡はスプーンで取り、豆が水面に出たら熱湯を足します。生の豆や硬い豆を味見しないでください。この工程をスロークッカーに置き換えません。'],
['肉と香味野菜を炒める','豆を沸騰させている間に、広いフライパンにオイル15 gを入れて中火で温めます。ベーコンを混ぜながら約5分、色づき始めるまで炒めます。豚肉を2回に分けて各約4分、表面だけ焼きつけます。中心までの加熱は煮込みで仕上げます。肉を専用の皿に取り出し、同じフライパンで玉ねぎ7分、にんにく1分、ソーセージ4分の順に炒めます。脂も含めすべて残します。栄養推定にはその脂を全量計上しています。'],
['柔らかくなるまで煮込む','豆を30分沸騰させた後、肉、ソーセージ、炒めた野菜、フライパンの汁を鍋に加えます。フライパンに少量の熱い煮汁を入れてこそげ取ります。黒こしょう1 gを加え、塩は最後まで加えません。再び穏やかに沸かし、ふたを少し開けて約100分煮込み、15–20分おきに底から混ぜます。豆と肉がかろうじて覆われる水位を保ち、必要なら熱湯を100 mlずつ足します。焦げつきや、豆が全部崩れるほど強い沸騰を避けます。'],
['温度と柔らかさを確認する','清潔な食品用温度計で複数の豚肉の角切りの中心を測ります。この煮込みでは実用上の目標を少なくとも74 °Cとし、塊肉の最低基準より高く設定しています。さらに肉がフォークで押すと容易にほぐれ、スプーンで取り出した豆が芯までなめらかで硬い中心がないことを確認します。硬さや温度が足りなければ煮込みを延長し、再確認します。時間は提案であり保証ではありません。生肉に触れた器具で味見しないでください。'],
['とろみをつけて味を調え休ませる','肉を含まない柔らかい豆をお玉1杯取り、ボウルでつぶして鍋に戻します。混ぜながら弱火で約15分さらに煮て、スプーンの背を薄く覆う濃さにします。濃すぎたら熱湯を足します。ローリエ2枚を取り除きます。ここで初めて味見して、予定の塩4 gを加えます。加工肉の塩味で十分なら減らしますが、推定ナトリウム量も変わります。火を止めてふたをし、10分休ませます。'],
['分けて速やかに冷蔵する','豆、肉、煮汁が同じくらいずつになるよう8人分に分けます。ご飯、オレンジ、ファロファを添えてもよいですが、材料や栄養値には含めていません。保存する分は速やかに小さく浅い容器に分け、2時間以内、室温が32 °Cを超える場合は1時間以内に4 °C以下で冷蔵します。大鍋全体が室温で冷めるまで待ちません。3–4日以内に食べるか、小分けで冷凍します。2か月は品質面での提案です。冷蔵庫で解凍し、混ぜながら複数箇所で少なくとも74 °Cに達するまで再加熱します。']],
'notes':'乾燥黒豆を使います。煮豆への置き換えで同じ分量と時間は使えません。この版には干し肉、豚耳、豚足を含みません。加える場合は別の手順と栄養計算が必要です。ソーセージは表示が十分に加熱済みのものを選びます。燻製というだけでは加熱済みとは限りません。加熱済みリングイッサまたは同等の豚肉の燻製ソーセージを使えますが、製品により味とナトリウム量が変わります。生の豚肩肉は塩抜きしません。さらりとさせるには熱湯、とろみには小麦粉でなく柔らかい豆をつぶして使います。豆が柔らかくなるまで酸味のある材料を加えません。火を止めて休ませても、残りを速やかに冷蔵する必要は変わりません。',
'faq':[['浸水を省略できますか？','この提案は冷蔵庫での浸水8時間と、新しい煮込み用の水を前提とします。浸水なしの同等の時間は示していません。工程が変わり、最初の沸騰30分も省略できません。'],['豆が硬いままなのはなぜですか？','古い豆、硬水、酸味のある材料を早く加えることなどで時間が延びる場合があります。十分な湯を保ち、硬い芯がなくなるまで煮ます。予定の塩は最後に加えます。'],['小麦粉なしでとろみをつけるには？','肉を含まない柔らかい豆をお玉1杯つぶして鍋に戻します。混ぜながら弱火でさらに15分煮て、濃すぎる場合は熱湯を足します。']],
'keywords':['家庭風フェイジョアーダ','黒豆のフェイジョアーダ','豚肉と黒豆の煮込み'],
'cover_alt':'黒豆、豚肉、ベーコン、燻製ソーセージを黒い煮汁で煮たフェイジョアーダ',
'nutrition':{'serving_size':'煮込み8人分のうち1人分、付け合わせなし','method':'確認済みUSDA資料10件を使用し、豆、豚肉、ベーコンは生の可食重量、ソーセージは加熱済みの重量で計算して合計を8で割っています。燻製ソーセージは一般的な豚肉の燻製ソーセージの資料で近似し、ブラジルのリングイッサ専用資料ではありません。脂と残る煮汁は全量計上し、取り除くローリエと捨てる浸水の水は除外しています。','note':'情報用の推定で、出来上がりの分析値ではありません。加工肉の製品と塩分、浸水、出来上がり量、煮汁の分配により変わります。ご飯、オレンジ、ファロファ、野菜の付け合わせは除外しています。'}
},
'pt':{
'path':'/pt/feijoada','historical_path':False,'title':'Feijoada caseira de feijão preto e porco','seo_title':'Feijoada caseira de feijão preto e porco',
'excerpt':'Feijoada caseira para 8 com feijão preto, porco, bacon e linguiça defumada: molho, fervura inicial, cozimento lento e conservação passo a passo.',
'summary':'Esta proposta de feijoada caseira combina feijão preto, paleta suína fresca, bacon e linguiça defumada completamente cozida em um caldo escuro engrossado com parte do próprio feijão. É uma adaptação com ingredientes fáceis de identificar, sem carnes salgadas que precisem de dessalga; não pretende representar todas as versões brasileiras.\n\nRende 8 porções de feijoada. Os 680 minutos estimados incluem 8 horas de molho na geladeira, 30 minutos de preparo, 160 de cozimento e 10 de descanso. O refogado é feito enquanto o feijão ferve. Quantidades, rendimento e tempos aguardam confirmação por teste de cozinha; a maciez e a temperatura importam mais que o relógio.',
'difficulty':'Média','course':'Prato principal','cuisine':'Brasileira, adaptação caseira',
'ingredients':['Feijão preto seco','Paleta suína fresca sem osso','Linguiça suína defumada completamente cozida','Bacon cru','Cebola','Alho','Azeite de oliva','Sal','Pimenta-do-reino','Água para cozinhar','Louro seco, para retirar'],
'groups':{'Alubias y cocción':'Feijão e cozimento','Carnes':'Carnes','Sofrito y sazón':'Refogado e temperos'},'units':{'hojas':'folhas'},
'steps':[
['Deixe o feijão de molho na geladeira','Escolha os 500 g de feijão preto seco, retire pedrinhas ou grãos danificados e enxágue. Coloque em um recipiente grande com cerca de 1,5 litro de água, cobrindo por vários centímetros. Tampe e deixe de molho 8 horas na geladeira a 4 °C ou menos; acrescente água se for absorvida. No fim descarte toda a água do molho e enxágue. Essa água é adicional aos 2,5 litros usados no cozimento.'],
['Prepare os ingredientes e separe a carne crua','Pique os 200 g de cebola e os 20 g de alho em uma tábua limpa para vegetais. Em outra tábua para carne crua, corte os 400 g de paleta fresca sem osso em cubos de cerca de 3 cm e os 100 g de bacon em tiras curtas. Corte os 250 g de linguiça em rodelas de 1 cm; use um produto cuja embalagem indique que está completamente cozido, não linguiça fresca nem carne salgada que precise de dessalga. Mantenha as carnes refrigeradas até cozinhar e lave mãos e utensílios depois de tocar carne suína crua.'],
['Ferva o feijão antes de baixar o fogo','Coloque o feijão escorrido em uma panela de pelo menos 6 litros com os 2,5 litros de água nova e as 2 folhas de louro. Leve à fervura, cerca de 15 minutos como referência, e mantenha fervura evidente por pelo menos 30 minutos sem tampa, controlando espuma e transbordamento. Retire a espuma com uma colher; acrescente água fervente se os grãos deixarem de ficar cobertos. Não prove feijão cru ou duro e não substitua esta etapa por uma panela de cozimento lento.'],
['Doure as carnes e o refogado','Durante a fervura, aqueça uma frigideira larga em fogo médio com os 15 g de azeite. Cozinhe o bacon por cerca de 5 minutos, mexendo, até começar a dourar. Acrescente o porco em duas levas, cerca de 4 minutos cada, apenas para dourar a superfície; ele terminará de cozinhar na feijoada. Retire as carnes para um prato reservado para isso. Na mesma frigideira refogue a cebola 7 minutos, o alho 1 minuto e a linguiça 4 minutos. Reserve tudo, inclusive a gordura: a estimativa nutricional a conta por inteiro.'],
['Cozinhe até ficar macio','Depois dos 30 minutos de fervura, acrescente carnes, linguiça, refogado e líquidos da frigideira à panela, raspando a frigideira com um pouco de caldo quente. Adicione 1 g de pimenta e deixe o sal para o fim. Retome fervura suave e cozinhe por cerca de 100 minutos com a tampa entreaberta, mexendo desde o fundo a cada 15–20 minutos. Mantenha feijão e carnes apenas cobertos, acrescentando água fervente de 100 em 100 ml se necessário. Evite que grudem ou que uma fervura forte desfaça todos os grãos.'],
['Confira a temperatura e a textura','Com um termômetro limpo meça o centro de vários cubos de porco: o objetivo prático desta feijoada é pelo menos 74 °C, acima do mínimo para cortes inteiros. A carne também deve ceder facilmente à pressão de um garfo, e um grão retirado com colher deve ficar cremoso por dentro, sem miolo duro. Se algo continuar firme ou abaixo da temperatura, cozinhe mais e confira novamente; os tempos são uma proposta, não uma garantia. Não prove com utensílios que tocaram carne crua.'],
['Engrosse, ajuste o sal e deixe descansar','Retire uma concha de feijão macio sem carne, amasse em uma tigela e devolva a pasta à panela. Cozinhe suavemente por mais cerca de 15 minutos, mexendo, até o caldo cobrir levemente as costas de uma colher; acrescente água fervente se ficar espesso demais. Retire as 2 folhas de louro. Prove só agora e acrescente os 4 g de sal previstos, ou menos se os embutidos já salgarem bastante; menos sal muda a estimativa de sódio. Desligue e deixe descansar 10 minutos com a panela tampada.'],
['Divida e refrigere rapidamente','Divida em 8 porções com quantidades parecidas de feijão, carnes e caldo. Arroz, laranja ou farofa podem acompanhar, mas não entram nos ingredientes nem na nutrição. Para guardar, divida logo as sobras em recipientes pequenos e rasos e refrigere a 4 °C ou menos em até 2 horas, ou 1 hora se o ambiente passar de 32 °C; não espere a panela grande inteira esfriar fora da geladeira. Consuma em 3–4 dias ou congele porções; 2 meses é uma proposta de qualidade. Descongele na geladeira e reaqueça mexendo até pelo menos 74 °C em vários pontos.']],
'notes':'Use feijão preto seco; não troque por feijão já cozido mantendo estes tempos e quantidades. Esta versão não leva carne seca, orelha nem pé de porco; incluí-los exige outro preparo e cálculo nutricional. A linguiça precisa estar completamente cozida conforme a embalagem: defumada nem sempre significa cozida. Pode ser linguiça cozida ou embutido suíno defumado equivalente; a marca muda o sabor e o sódio. A paleta fresca não precisa de dessalga. Para afinar o caldo acrescente água fervente; para engrossar amasse feijão já cozido em vez de usar farinha. Não acrescente ingredientes ácidos antes de o feijão ficar macio. O descanso fora do fogo não substitui a refrigeração rápida das sobras.',
'faq':[['Posso pular o molho?','Esta proposta começa com 8 horas de molho na geladeira e água nova para cozinhar. Não há tempo equivalente sem molho; o processo muda e a fervura inicial de 30 minutos continua necessária.'],['Por que o feijão continua duro?','Grãos velhos, água dura ou ingredientes ácidos colocados cedo podem prolongar o cozimento. Mantenha água quente suficiente e cozinhe até não haver miolo duro; acrescente o sal previsto no fim.'],['Como engrossar sem farinha?','Amasse uma concha de feijão macio sem carne e devolva à panela. Cozinhe suavemente por mais 15 minutos, mexendo; acrescente água fervente se ficar espesso demais.']],
'keywords':['feijoada caseira','feijoada de feijão preto','feijão preto com carne de porco'],
'cover_alt':'Feijoada de feijão preto com cubos de porco, bacon e rodelas de linguiça defumada em caldo escuro',
'nutrition':{'serving_size':'1 de 8 porções de feijoada, sem acompanhamentos','method':'Dez fichas USDA verificadas, pesos crus comestíveis para feijão, porco e bacon e peso da linguiça já cozida; soma dividida por 8. A linguiça defumada é aproximada por uma ficha genérica de embutido suíno defumado, não por uma ficha específica de linguiça brasileira. Toda a gordura e o caldo retido são contados. Louro retirado e água do molho descartada ficam de fora.','note':'Estimativa informativa, não análise da feijoada pronta. Marca e sal da linguiça e do bacon, molho, rendimento e divisão do caldo alteram os valores. Arroz, laranja, farofa e verduras de acompanhamento não são contados.'}
}})
p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
print('Authored all six feijoada localizations; media and publication still pending.')
