import json
from pathlib import Path
p=Path(__file__).resolve().parents[1]/'editorial/ensalada-de-pollo-con-aguacate-y-mango-localizaciones-20261008.json'
assert not p.exists()
data={
 'en':{
  'path':'/en/chicken-salad-with-avocado-and-mango-2','historical_path':True,
  'title':'Chicken salad with avocado and mango','seo_title':'Chicken salad with avocado and mango',
  'excerpt':'Chicken, avocado and mango salad for 4 with pan-cooked chicken and lime dressing. Follow washing, cooking, slicing and gentle assembly step by step.',
  'summary':'This salad combines pan-cooked chicken, avocado and mango cubes, lettuce, cucumber and red onion. A dressing of lime, olive oil and a little honey brings everything together without a thick sauce.\n\nThe proposal serves 4. The estimated 55 minutes include 30 minutes of preparation, 20 of cooking in two batches and 5 of resting. Check the chicken with a thermometer for at least 74 °C; quantities, times and yield still need confirmation in a kitchen test.',
  'difficulty':'Easy','course':'Main-course salad','cuisine':'International',
  'ingredients':['Raw boneless skinless chicken breast','Avocado flesh','Mango flesh','Cucumber with skin','Romaine lettuce','Red onion','Lime juice','Olive oil','Honey','Salt','Black pepper'],
  'groups':{'Ensalada':'Salad','Cocción y aliño':'Cooking and dressing'},
  'steps':[
   ['Wash and dry the produce','Wash your hands and prepare a clean produce board separate from the chicken board. Rinse cucumber, mango, avocado and lime under running water before cutting or peeling, without soap. Wash and thoroughly dry the 100 g lettuce unless its package says ready to eat. Slice the 150 g cucumber into thin half-moons and the 40 g red onion into slivers; refrigerate with the lettuce while cooking.'],
   ['Prepare four chicken fillets','Do not wash raw chicken. On its separate board, divide the 600 g boneless skinless breast into four fillets of about 150 g, with an even thickness of about 1.5 cm. If needed, gently flatten between food-safe sheets. Season with 1 g salt and 0.5 g pepper. Discard used paper and wash hands and utensils; do not put salad or cooked chicken on the raw-chicken board or plate.'],
   ['Cook and check the temperature','Heat a wide frying pan over medium heat with 5 g oil. Cook two fillets for about 4–5 minutes per side, leaving them still until they release; adjust the heat if they burn. Use a food thermometer to check that the thickest centre of each fillet reaches at least 74 °C, without touching the pan with the probe. If below temperature, keep cooking and check again; colour and timing alone are insufficient. Transfer to a clean plate and repeat with the other two fillets and the remaining 5 g cooking oil. The planned 20 minutes are only a guide.'],
   ['Rest and slice into strips','Rest the cooked chicken for 5 minutes on the clean plate. With a clean knife and board, cut each fillet into strips about 1 cm wide. It should stop giving off intense steam before going into the salad; wait longer if needed and add that time to the total. Set aside only while finishing assembly, not for hours at room temperature.'],
   ['Dice the mango and avocado','Peel the washed mango, remove the flesh from its stone and weigh 250 g. Cut into cubes about 2 cm across. Open the washed avocado and remove its stone with a spoon rather than striking it with a knife. Scoop out and weigh 200 g flesh, then cut into roughly 2 cm cubes. Use the clean produce board without raw-chicken contact and prepare both just before mixing to limit avocado browning.'],
   ['Whisk the lime dressing','In a small bowl mix the 40 g lime juice, 10 g honey, remaining 2 g salt and 0.5 g pepper. Add the 20 g oil reserved for dressing and whisk with a fork until temporarily combined. Stir again just before use if it separates. Dressing does not replace cooking chicken or prevent cross-contamination.'],
   ['Assemble gently','Put lettuce, cucumber and onion in a large bowl and toss with half the dressing. Add mango and avocado cubes and the warm chicken strips. Fold in the remaining dressing with two spoons, lifting gently from below without crushing the avocado. Divide among four plates, distributing chicken and fruit evenly.'],
   ['Serve and refrigerate','Serve freshly assembled, alone or with an accompaniment not included in the nutrition. Cover leftovers and refrigerate at 4 °C or below within 2 hours, or 1 hour if the surrounding temperature exceeds 32 °C. As a conservative proposal, eat assembled salad within 24 hours; lettuce and avocado lose texture. To prepare ahead, keep cooked chicken, vegetables and dressing separately chilled and assemble when serving; do not freeze the complete salad because its texture changes substantially.']
  ],
  'notes':'Choose ripe but firm mango and avocado that yields slightly without falling apart. Replace lime juice with the same weight of lemon juice if desired; flavour and nutrition change. Omitting honey makes the dressing sharper and changes its nutritional figures. Dry lettuce prevents dilution. Prepare only the fruit needed; acidity slows browning a little but does not preserve avocado indefinitely. Use separate utensils for raw chicken and ready-to-eat foods. Temperature determines cooking, not the absence of a pink colour.',
  'faq':[['Can I prepare the salad ahead?','Keep already cooked chicken, vegetables and dressing separately chilled and assemble at serving time. Cut avocado near assembly. Dressed salad loses texture; consumption within 24 hours refrigerated is proposed.'],['How do I know the chicken is cooked?','Measure the thickest centre of each fillet with a food thermometer: it must reach at least 74 °C. Neither a fixed time nor meat colour alone guarantees that point.'],['Why is there water at the bottom?','Wet lettuce, very soft mango and dressing added too far in advance can release liquid. Dry leaves well, use firm fruit and toss just before serving.']],
  'keywords':['chicken avocado mango salad','pan-cooked chicken salad','lime salad dressing'],
  'cover_alt':'Salad with browned chicken strips, mango and avocado cubes, lettuce, cucumber and red onion',
  'nutrition':{'serving_size':'1 of 4 portions','method':'Eleven verified USDA entries per 100 g are weighted by the stated edible ingredient amounts and divided by 4. Chicken uses 600 g raw boneless skinless breast; red onion is approximated with generic raw onion data. All 30 g oil and all dressing are counted even if some remains in the pan or bowl.','note':'An informational estimate, not an analysis of the prepared salad. Cooking juices lost, fruit variety, retained oil and portioning affect the result. Bread and other additional accompaniments are not counted.'}
 },
 'de':{
  'path':'/de/huhnersalat-mit-avocado-und-mango','historical_path':True,
  'title':'Hähnchensalat mit Avocado und Mango','seo_title':'Hähnchensalat mit Avocado und Mango',
  'excerpt':'Hähnchensalat mit Avocado und Mango für 4: Pfannenhähnchen, Limettendressing und klare Schritte vom Waschen bis zum vorsichtigen Anrichten.',
  'summary':'Dieser Salat verbindet Hähnchen aus der Pfanne, Avocado- und Mangowürfel, Romanasalat, Gurke und rote Zwiebel. Limette, Olivenöl und etwas Honig bilden ein leichtes Dressing ohne dicke Sauce.\n\nDer Vorschlag ergibt 4 Portionen. Die geschätzten 55 Minuten enthalten 30 Minuten Vorbereitung, 20 Minuten Braten in zwei Durchgängen und 5 Minuten Ruhe. Hähnchen mit Thermometer auf mindestens 74 °C prüfen; Mengen, Zeiten und Ausbeute sind noch nicht im Küchentest bestätigt.',
  'difficulty':'Einfach','course':'Salat als Hauptgericht','cuisine':'International',
  'ingredients':['Rohe Hähnchenbrust ohne Haut und Knochen','Avocadofruchtfleisch','Mangofruchtfleisch','Gurke mit Schale','Romanasalat','Rote Zwiebel','Limettensaft','Olivenöl','Honig','Salz','Schwarzer Pfeffer'],
  'groups':{'Ensalada':'Salat','Cocción y aliño':'Braten und Dressing'},
  'steps':[
   ['Gemüse waschen und trocknen','Hände waschen und ein sauberes Obst- und Gemüsebrett getrennt vom Hähnchenbrett vorbereiten. Gurke, Mango, Avocado und Limette vor Schneiden oder Schälen unter fließendem Wasser ohne Seife waschen. 100 g Romanasalat waschen und gut trocknen, außer die Packung bezeichnet ihn als verzehrfertig. 150 g Gurke in dünne Halbmonde und 40 g rote Zwiebel in feine Streifen schneiden; mit dem Salat bis zum Anrichten kühlen.'],
   ['Vier Hähnchenfilets vorbereiten','Rohes Hähnchen nicht waschen. Auf seinem getrennten Brett 600 g Brust ohne Haut und Knochen in vier etwa 150 g schwere Filets mit gleichmäßiger Dicke von etwa 1,5 cm teilen. Falls nötig zwischen lebensmittelechten Bögen vorsichtig flach drücken. Mit 1 g Salz und 0,5 g Pfeffer würzen. Benutztes Papier entsorgen, Hände und Geräte waschen; Salat und gebratenes Hähnchen nicht auf Brett oder Teller des rohen Hähnchens legen.'],
   ['Braten und Kerntemperatur prüfen','Eine breite Pfanne bei mittlerer Hitze mit 5 g Öl erhitzen. Zwei Filets etwa 4–5 Minuten je Seite braten und liegen lassen, bis sie sich lösen; bei Verbrennen Hitze anpassen. Mit Lebensmittelthermometer prüfen, dass die dickste Mitte jedes Filets mindestens 74 °C erreicht, ohne die Pfanne mit der Sonde zu berühren. Bei zu niedriger Temperatur weiterbraten und erneut messen; Farbe und Uhr allein reichen nicht. Auf sauberen Teller geben und mit den anderen zwei Filets und den übrigen 5 g Bratöl wiederholen. Die vorgesehenen 20 Minuten sind Richtwerte.'],
   ['Ruhen lassen und in Streifen schneiden','Gegartes Hähnchen 5 Minuten auf dem sauberen Teller ruhen lassen. Mit sauberem Messer und Brett jedes Filet in etwa 1 cm breite Streifen schneiden. Vor dem Salat soll es nicht mehr stark dampfen; bei Bedarf länger warten und zur Gesamtzeit addieren. Nur während der restlichen Vorbereitung beiseitestellen, nicht stundenlang bei Raumtemperatur.'],
   ['Mango und Avocado würfeln','Gewaschene Mango schälen, Fruchtfleisch vom Stein lösen und 250 g wiegen. In etwa 2 cm große Würfel schneiden. Gewaschene Avocado öffnen, Stein mit einem Löffel entfernen statt mit dem Messer hineinzuschlagen, Fruchtfleisch herauslösen und 200 g wiegen. Ebenfalls etwa 2 cm groß würfeln. Sauberes Obstbrett ohne Kontakt mit rohem Hähnchen verwenden und beides erst kurz vor dem Mischen vorbereiten, um Avocadobräunung zu begrenzen.'],
   ['Limettendressing verrühren','40 g Limettensaft, 10 g Honig, übrige 2 g Salz und 0,5 g Pfeffer in einer kleinen Schüssel mischen. Die für das Dressing vorgesehenen 20 g Öl zugeben und mit einer Gabel vorübergehend verbinden. Bei Trennung vor Gebrauch erneut rühren. Dressing ersetzt weder Hähnchengaren noch verhindert es Kreuzkontamination.'],
   ['Salat vorsichtig mischen','Salat, Gurke und Zwiebel in eine große Schüssel geben und mit der Hälfte des Dressings mischen. Mango, Avocado und lauwarme Hähnchenstreifen zugeben. Restliches Dressing mit zwei Löffeln vorsichtig von unten unterheben, ohne die Avocado zu zerdrücken. Auf vier Teller verteilen und Hähnchen sowie Obst ähnlich portionieren.'],
   ['Servieren und gekühlt aufbewahren','Frisch angerichtet servieren, allein oder mit einer nicht eingerechneten Beilage. Reste abdecken und innerhalb von 2 Stunden bei höchstens 4 °C kühlen, bei Umgebungstemperatur über 32 °C innerhalb 1 Stunde. Als konservativer Vorschlag den fertigen Salat binnen 24 Stunden essen; Salat und Avocado verlieren Textur. Zum Vorbereiten gegartes Hähnchen, Gemüse und Dressing getrennt kalt lagern und erst beim Servieren mischen. Den vollständigen Salat nicht einfrieren, da sich seine Textur stark verändert.']
  ],
  'notes':'Reife, feste Mango und leicht nachgebende, nicht zerfallende Avocado wählen. Limette lässt sich durch dasselbe Gewicht Zitronensaft ersetzen; Geschmack und Nährwerte ändern sich. Ohne Honig wird das Dressing saurer und die Nährwerte stimmen nicht mehr unverändert. Salat gut trocknen, damit er nicht verdünnt. Nur benötigtes Obst vorbereiten; Säure verzögert Bräunung etwas, hält Avocado aber nicht unbegrenzt frisch. Getrennte Geräte für rohes Hähnchen und verzehrfertige Lebensmittel verwenden. Die Temperatur bestimmt die Garung, nicht fehlende rosa Farbe.',
  'faq':[['Kann ich den Salat vorbereiten?','Bereits gegartes Hähnchen, Gemüse und Dressing getrennt kühlen und beim Servieren mischen. Avocado kurz vorher schneiden. Angemachter Salat verliert Textur; Verzehr binnen 24 Stunden gekühlt ist vorgeschlagen.'],['Woran erkenne ich gegartes Hähnchen?','Die dickste Mitte jedes Filets mit Lebensmittelthermometer messen: mindestens 74 °C. Weder eine feste Zeit noch die Fleischfarbe allein garantieren das.'],['Warum sammelt sich Wasser unten?','Nasser Salat, sehr weiche Mango und früh zugegebenes Dressing können Flüssigkeit abgeben. Blätter gut trocknen, festes Obst wählen und erst vor dem Servieren mischen.']],
  'keywords':['Hähnchensalat Avocado Mango','Hähnchen aus der Pfanne Salat','Limettendressing'],
  'cover_alt':'Salat mit goldbraunen Hähnchenstreifen, Mango, Avocado, Romanasalat, Gurke und roter Zwiebel',
  'nutrition':{'serving_size':'1 von 4 Portionen','method':'Elf überprüfte USDA-Einträge je 100 g werden mit den angegebenen essbaren Zutatengewichten gewichtet und durch 4 geteilt. Hähnchen basiert auf 600 g roher Brust ohne Haut und Knochen; rote Zwiebel wird mit allgemeiner roher Zwiebel angenähert. Alle 30 g Öl und das gesamte Dressing sind enthalten, auch wenn Reste in Pfanne oder Schüssel bleiben.','note':'Informative Schätzung, keine Analyse des fertigen Salats. Verlorene Bratsäfte, Obstsorten, zurückbleibendes Öl und Verteilung verändern das Ergebnis. Brot und zusätzliche Beilagen sind nicht enthalten.'}
 },
 'fr':{
  'path':'/fr/salade-de-poulet-avec-avocat-et-mangue-2','historical_path':True,
  'title':'Salade de poulet à l’avocat et à la mangue','seo_title':'Salade de poulet à l’avocat et à la mangue',
  'excerpt':'Salade de poulet, avocat et mangue pour 4, poulet à la poêle et vinaigrette au citron vert. Lavez, cuisez, découpez et assemblez sans écraser les fruits.',
  'summary':'Cette salade associe poulet poêlé, dés d’avocat et de mangue, laitue, concombre et oignon rouge. Citron vert, huile d’olive et un peu de miel lient les ingrédients sans sauce épaisse.\n\nLa proposition donne 4 portions. Les 55 minutes estimées comprennent 30 de préparation, 20 de cuisson en deux fois et 5 de repos. Vérifiez au thermomètre que le poulet atteint au moins 74 °C ; doses, temps et rendement restent à confirmer par un essai en cuisine.',
  'difficulty':'Facile','course':'Salade en plat principal','cuisine':'Internationale',
  'ingredients':['Blanc de poulet cru sans peau ni os','Chair d’avocat','Chair de mangue','Concombre avec peau','Laitue romaine','Oignon rouge','Jus de citron vert','Huile d’olive','Miel','Sel','Poivre noir'],
  'groups':{'Ensalada':'Salade','Cocción y aliño':'Cuisson et vinaigrette'},
  'steps':[
   ['Laver et sécher les végétaux','Lavez-vous les mains et préparez une planche propre pour fruits et légumes, séparée de celle du poulet. Rincez concombre, mangue, avocat et citron vert sous l’eau courante avant de couper ou d’éplucher, sans savon. Lavez et séchez bien les 100 g de laitue, sauf si l’emballage indique prête à consommer. Coupez 150 g de concombre en fines demi-lunes et 40 g d’oignon en lamelles ; réservez avec la laitue au réfrigérateur pendant la cuisson.'],
   ['Préparer quatre filets de poulet','Ne lavez pas le poulet cru. Sur sa planche séparée, partagez les 600 g de blanc sans peau ni os en quatre filets d’environ 150 g, épais régulièrement d’environ 1,5 cm. Si besoin, aplatissez doucement entre feuilles aptes au contact alimentaire. Assaisonnez avec 1 g de sel et 0,5 g de poivre. Jetez le papier utilisé et lavez mains et ustensiles ; ne posez ni salade ni poulet cuit sur la planche ou l’assiette du poulet cru.'],
   ['Cuire et vérifier la température','Chauffez une grande poêle à feu moyen avec 5 g d’huile. Cuisez deux filets environ 4–5 minutes par face, sans les déplacer avant qu’ils se décollent ; ajustez si cela brûle. Mesurez au thermomètre alimentaire le centre le plus épais de chaque filet : au moins 74 °C, sans toucher la poêle avec la sonde. Sinon, poursuivez et mesurez à nouveau ; couleur et minuterie ne suffisent pas. Transférez dans une assiette propre et recommencez avec les deux autres et les 5 g d’huile de cuisson restants. Les 20 minutes prévues sont indicatives.'],
   ['Laisser reposer et couper en lanières','Laissez le poulet cuit reposer 5 minutes dans l’assiette propre. Avec couteau et planche propres, coupez chaque filet en lanières d’environ 1 cm. Il ne doit plus dégager une forte vapeur avant d’aller dans la salade ; attendez davantage si nécessaire et ajoutez ce temps au total. Réservez seulement pendant la fin du montage, pas des heures à température ambiante.'],
   ['Couper mangue et avocat','Épluchez la mangue lavée, détachez la chair du noyau et pesez 250 g. Coupez en dés d’environ 2 cm. Ouvrez l’avocat lavé, retirez le noyau avec une cuillère plutôt qu’en frappant avec un couteau, prélevez la chair et pesez 200 g. Coupez aussi en dés de 2 cm. Utilisez la planche à fruits propre sans contact avec du poulet cru et préparez juste avant de mélanger pour limiter le brunissement.'],
   ['Mélanger la vinaigrette au citron vert','Dans un petit bol mélangez 40 g de jus de citron vert, 10 g de miel, les 2 g de sel et 0,5 g de poivre restants. Ajoutez les 20 g d’huile réservés à la vinaigrette et battez à la fourchette pour une liaison temporaire. Remuez juste avant usage si elle se sépare. La vinaigrette ne remplace pas la cuisson du poulet et n’empêche pas la contamination croisée.'],
   ['Assembler délicatement','Mettez laitue, concombre et oignon dans un grand saladier et mélangez avec la moitié de la vinaigrette. Ajoutez mangue, avocat et poulet tiède. Incorporez le reste avec deux cuillères, en soulevant doucement depuis le fond sans écraser l’avocat. Répartissez dans quatre assiettes, avec des quantités similaires de poulet et de fruits.'],
   ['Servir et réfrigérer','Servez aussitôt, seule ou avec un accompagnement non compris dans la nutrition. Couvrez les restes et réfrigérez à 4 °C maximum dans les 2 heures, ou 1 heure si l’ambiance dépasse 32 °C. Par prudence, consommez la salade montée sous 24 heures ; laitue et avocat perdront leur texture. Pour anticiper, gardez poulet cuit, végétaux et vinaigrette séparés au froid et montez au service. Ne congelez pas la salade complète : sa texture changerait beaucoup.']
  ],
  'notes':'Choisissez une mangue mûre mais ferme et un avocat souple sans être défait. Remplacez éventuellement le citron vert par le même poids de jus de citron jaune ; saveur et nutrition changent. Sans miel, la vinaigrette devient plus acide et les chiffres diffèrent. Séchez la laitue pour ne pas diluer. Préparez seulement les fruits utiles ; l’acide ralentit un peu le brunissement, sans préserver l’avocat indéfiniment. Séparez les ustensiles du poulet cru et des aliments prêts à manger. La température détermine la cuisson, pas l’absence de rose.',
  'faq':[['Puis-je préparer la salade à l’avance ?','Gardez poulet déjà cuit, végétaux et vinaigrette séparés au froid, puis assemblez au service. Coupez l’avocat près du montage. La salade assaisonnée perd sa texture ; consommation réfrigérée sous 24 heures proposée.'],['Comment vérifier la cuisson du poulet ?','Mesurez le centre le plus épais de chaque filet avec un thermomètre alimentaire : au moins 74 °C. Un temps fixe ou la couleur seuls ne le garantissent pas.'],['Pourquoi y a-t-il de l’eau au fond ?','Laitue mouillée, mangue trop molle et assaisonnement trop précoce peuvent libérer du liquide. Séchez les feuilles, choisissez des fruits fermes et mélangez juste avant de servir.']],
  'keywords':['salade poulet avocat mangue','salade poulet poêlé','vinaigrette citron vert'],
  'cover_alt':'Salade aux lanières de poulet dorées, dés de mangue et avocat, laitue, concombre et oignon rouge',
  'nutrition':{'serving_size':'1 des 4 portions','method':'Onze fiches USDA vérifiées pour 100 g sont pondérées par les poids comestibles indiqués et divisées par 4. Poulet calculé sur 600 g de blanc cru sans peau ni os ; oignon rouge approché par l’oignon cru générique. Les 30 g d’huile et toute la vinaigrette sont comptés, même avec des restes dans la poêle ou le bol.','note':'Estimation informative, pas analyse de la salade préparée. Jus perdus à la cuisson, variété des fruits, huile retenue et répartition changent le résultat. Pain et accompagnements supplémentaires ne sont pas comptés.'}
 }
}
p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
