"""Authored IT/JA/PT-BR localizations, including all mussel handling and yield notes."""
import json
from pathlib import Path
p=Path(__file__).resolve().parents[1]/'editorial/pasta-frutos-del-mar-localizaciones-20261008.json'
data=json.loads(p.read_text());assert set(data)=={'en','de','fr'}
data['de']['ingredients'][4]='Zerkleinerte Tomaten aus der Dose'
data.update({
'it':{
'path':'/it/pasta-frutti-di-mare','historical_path':True,'title':'Pasta ai frutti di mare con pomodoro','seo_title':'Pasta ai frutti di mare con pomodoro',
'excerpt':'Pasta ai frutti di mare per 4 con gamberi, calamari e cozze: salsa di pomodoro, cotture separate e passaggi per finire gli spaghetti.',
'summary':'Questa pasta ai frutti di mare unisce spaghetti, gamberi, calamari e cozze in una salsa breve di pomodoro, aglio, cipolla e prezzemolo. Le cozze si aprono a parte per filtrare il liquido; gli altri frutti di mare cuociono nella salsa e si tengono da parte mentre la pasta termina la cottura.\n\nLa proposta rende 4 piatti e stima 25 minuti di preparazione e 25 di cottura, 50 in totale, con acqua, pasta e cozze in parallelo quando possibile. Quantità, tempi e resa attendono una prova in cucina. La nutrizione ipotizza 150 g di carne edibile da 600 g di cozze con guscio; la resa reale va pesata.',
'difficulty':'Media','course':'Piatto principale','cuisine':'Mediterranea, proposta casalinga',
'ingredients':['Spaghetti secchi','Gamberi crudi sgusciati','Calamaro crudo pulito','Cozze vive con guscio','Pomodori triturati in conserva','Cipolla','Aglio','Olio d’oliva','Prezzemolo fresco','Sale','Acqua per la pasta senza sale','Acqua per aprire le cozze'],
'groups':{'Pasta y marisco':'Pasta e frutti di mare','Salsa':'Salsa','Cocción':'Cottura'},
'steps':[
['Pulisci e controlla i frutti di mare','Usa 250 g di gamberi crudi già sgusciati e privati dell’intestino e 250 g di calamaro pulito: corpo senza pelle né interiora, tentacoli senza becco. Taglia il corpo ad anelli di circa 0,5 cm e dividi i tentacoli grandi. Controlla i 600 g di cozze vive con guscio da fornitore autorizzato: scarta gusci rotti e cozze aperte che non si chiudono con un leggero colpo. Spazzola sotto acqua fredda e togli il bisso appena prima di cuocere; non lasciarle immerse in acqua dolce. Tieni i frutti di mare separati e refrigerati a 4 °C o meno mentre fai la salsa. Se gamberi o calamaro sono congelati, scongela prima in frigorifero; l’attesa non entra nei 50 minuti.'],
['Trita gli aromi e scalda l’acqua','Trita i 100 g di cipolla e i 12 g d’aglio su un tagliere pulito diverso da quello dei frutti di mare crudi. Lava e trita gli 8 g di prezzemolo. Metti i 3 litri d’acqua per pasta in una pentola ampia e porta a ebollizione senza sale: si condisce la salsa. Prepara un’altra pentola con coperchio per cozze e una padella grande per salsa. Lava mani e utensili dopo i frutti di mare crudi e usa una ciotola pulita per quelli cotti.'],
['Prepara una salsa di pomodoro breve','Scalda i 30 g d’olio nella padella a fuoco medio. Soffriggi la cipolla 5 minuti finché si ammorbidisce senza bruciare. Aggiungi l’aglio e mescola 1 minuto. Unisci i 400 g di pomodori triturati e cuoci dolcemente 8 minuti, mescolando, finché perde parte dell’acqua e del sapore troppo crudo. Tieni la salsa calda a fuoco basso. I 14 minuti sono indicativi; evita che asciughi o si attacchi.'],
['Apri le cozze al vapore','Mentre fai la salsa porta a bollore i 100 ml d’acqua nella pentola delle cozze. Aggiungi le cozze pulite, copri e cuoci circa 4–5 minuti, scuotendo prudentemente una volta. Togli in una ciotola pulita quelle aperte; scarta quelle rimaste chiuse alla fine senza forzarle. Conserva fino a 100 ml di liquido e filtra con un colino fine rivestito di garza pulita per togliere sabbia, poi uniscilo alla salsa. Lascia alcune cozze nel guscio per servire e togli la carne dalle altre con utensili puliti. Tieni da parte solo mentre finisci il piatto.'],
['Cuoci gamberi e calamari','Porta la salsa a lieve bollore e unisci i 250 g di gamberi e i 250 g di calamaro. Cuoci circa 3–4 minuti mescolando finché i gamberi sono sodi e opachi e il calamaro perde traslucenza. Con una sonda sottile controlla almeno 63 °C nelle parti più spesse; se manca temperatura, continua e misura ancora. Il tempo dipende da dimensione e temperatura iniziale. Togli i frutti di mare cotti in un’altra ciotola pulita per non prolungarne la cottura mentre finisce la pasta. Non usare la ciotola del crudo.'],
['Cuoci la pasta e conserva acqua','Calcola l’inizio per finire questa fase vicino ai frutti di mare, poiché la pasta può cuocere in parallelo. Versa i 320 g di spaghetti nell’acqua bollente senza sale, mescola all’inizio per separarli e cuoci 2 minuti meno del tempo al dente indicato sulla confezione: finiranno nella salsa. Prima di scolare conserva 150 ml d’acqua di cottura in una tazza. Scola senza sciacquare. Se pasta o frutti di mare richiedono più tempo, prolunga il totale; non abbreviare una cottura insufficiente.'],
['Finisci la pasta nella salsa','Unisci gli spaghetti scolati alla salsa e mescola a fuoco medio circa 2 minuti fino ad al dente. Aggiungi acqua conservata a incrementi di 30 ml solo se serve a rivestire la pasta senza pozzanghere. Negli ultimi 30 secondi unisci gamberi, calamaro, cozze e prezzemolo, mescolando delicatamente per scaldarli senza romperli. Assaggia con utensile pulito e aggiungi i 3 g di sale previsti, o meno se il liquido delle cozze è già sapido; meno sale cambia il sodio stimato. Non aggiungere gusci chiusi né frammenti di guscio.'],
['Servi subito e raffredda gli avanzi','Dividi in 4 piatti distribuendo allo stesso modo pasta e tre tipi di frutti di mare. Servi immediatamente; il calore prolungato indurisce gamberi e calamaro. Togli i gusci prima di conservare avanzi, dividi in piccoli contenitori e refrigera a 4 °C o meno entro 2 ore, o 1 ora se l’ambiente supera 32 °C. Si propone di consumare entro 24 ore per la qualità; riscalda solo la porzione da mangiare mescolando fino ad almeno 74 °C in più punti. Non si propone di congelare il piatto assemblato perché pasta e frutti di mare perdono consistenza.']],
'notes':'Il piatto comprende i tre tipi di frutti di mare; una miscela commerciale cambia quantità, procedimento e nutrizione. Compra cozze vive da fonte autorizzata e segui le istruzioni del fornitore per conservarle. Scegli gamberi crudi sgusciati e calamaro già pulito per pesi edibili. Aggiungere vino o formaggio cambia il calcolo. Regola la salsa con poca acqua di pasta per volta, non con tutta la tazza automaticamente. Non riutilizzare taglieri o ciotole del crudo senza lavarli. Contiene crostacei, molluschi e frumento; controlla anche etichette per altri ingredienti o tracce. Temperatura e segnali di cottura prevalgono sui tempi proposti.',
'faq':[['Che cosa faccio con le cozze che non si aprono?','Scarta quelle ancora chiuse dopo la cottura senza forzarle per aggiungerle. Prima di cuocere scarta anche gusci rotti e cozze aperte che non si chiudono con un leggero colpo.'],['Posso usare frutti di mare congelati?','Per gamberi e calamaro scongela in frigorifero prima di iniziare e pesa sgusciati o puliti. Lo scongelamento non rientra nei 50 minuti. Questa proposta usa cozze vive con guscio, non una sostituzione diretta con cozze congelate.'],['Come evito pasta asciutta?','Conserva 150 ml d’acqua di pasta e aggiungi solo il necessario a incrementi di 30 ml durante la finitura nella salsa. Rimetti i frutti di mare alla fine per evitare un riscaldamento prolungato.']],
'keywords':['pasta ai frutti di mare','spaghetti ai frutti di mare','pasta gamberi calamari cozze'],'cover_alt':'Spaghetti al pomodoro con gamberi sgusciati, anelli di calamaro, cozze aperte e prezzemolo',
'nutrition':{'serving_size':'1 di 4 piatti, senza gusci','method':'Dieci schede USDA verificate, peso secco della pasta e crudo edibile dei frutti di mare, totale diviso per 4. Resa proposta delle cozze: 150 g di carne da 600 g con guscio, pari al 25%, da pesare in cucina. Gamberi e calamaro approssimati con schede di specie miste; cozze con cozza blu cruda. Olio, pomodoro e sale di salsa conteggiati interamente. Pasta in acqua senza sale; acqua scolata e gusci esclusi.','note':'Stima informativa, non analisi del piatto finito. Resa reale delle cozze, scarti, specie, possibili additivi dei gamberi e marche modificano i valori. Formaggio, pane e vino esclusi; il liquido delle cozze può apportare sali non interamente rappresentati dalla resa proposta.'}
},
'ja':{
'path':'/ja/seafood-pasta','historical_path':False,'title':'魚介とトマトソースのスパゲッティ','seo_title':'魚介とトマトソースのスパゲッティ',
'excerpt':'えび、いか、ムール貝を使う4人分の魚介パスタ。トマトソース、魚介の段階的な加熱、スパゲッティの仕上げを順に紹介します。',
'summary':'スパゲッティ、えび、いか、ムール貝を、トマト、にんにく、玉ねぎ、パセリの短時間のソースでまとめる魚介パスタです。ムール貝は別鍋で開いて煮汁をこし、ほかの魚介はソースで加熱して取り出し、パスタの仕上げを待ちます。\n\n4皿分を想定し、準備25分、調理25分、合計50分が推定です。可能な範囲で湯、パスタ、ムール貝を並行して加熱します。分量、時間、出来上がり量は調理試作による確認前です。栄養計算では殻付きムール貝600 gから可食部150 gを想定し、実際の歩留まりは計量が必要です。',
'difficulty':'中級','course':'主菜','cuisine':'地中海料理の家庭向け提案',
'ingredients':['乾燥スパゲッティ','生のむきえび','下処理済みの生いか','生きた殻付きムール貝','缶詰の粉砕トマト','玉ねぎ','にんにく','オリーブオイル','生のパセリ','塩','パスタ用の水、塩なし','ムール貝を蒸す水'],
'groups':{'Pasta y marisco':'パスタと魚介','Salsa':'ソース','Cocción':'加熱用'},
'steps':[
['魚介を下処理して確認する','殻と背わたを取り除いた生えび250 g、下処理済みの生いか250 gを使います。いかの胴は皮と内臓を除き、足からはくちばしを除きます。胴を幅約0.5 cmの輪切りにし、大きな足は分けます。認可された販売元の生きた殻付きムール貝600 gを確認し、割れた貝や軽くたたいても閉じない開いた貝は捨てます。冷水を流しながらこすり、加熱直前に足糸を除きます。真水に漬けたままにしません。ソースを作る間、魚介は分けて4 °C以下で冷蔵します。えびやいかが冷凍なら先に冷蔵庫で解凍します。その待ち時間は50分に含めません。'],
['香味野菜を刻み湯を沸かす','生魚介とは別の清潔なまな板で玉ねぎ100 g、にんにく12 gを刻みます。パセリ8 gを洗って刻みます。大きめの鍋にパスタ用の水3リットルを入れ、塩を加えず沸騰させます。味付けはソース側で行います。ムール貝用のふた付き鍋とソース用の大きなフライパンも用意します。生魚介に触れたら手と器具を洗い、加熱済み魚介には清潔なボウルを使います。'],
['短時間のトマトソースを作る','フライパンでオイル30 gを中火に温めます。玉ねぎを5分、焦がさず柔らかくなるまで炒めます。にんにくを加えて1分混ぜます。粉砕トマト400 gを加え、混ぜながら穏やかに8分煮て、水分と生っぽい味を減らします。弱火で温かく保ちます。14分は目安で、乾燥や焦げつきを避けます。'],
['ムール貝を蒸して開く','ソースを作る間にムール貝用の鍋で水100 mlを沸かします。洗ったムール貝を入れてふたをし、約4–5分加熱して途中で1回慎重に鍋をゆすります。開いた貝を清潔なボウルに取り、最後まで閉じたものは無理に開けず捨てます。煮汁を最大100 ml取り、清潔なガーゼを敷いた細かいこし器で砂を除いてソースへ加えます。一部の貝は盛り付け用に殻に残し、残りは清潔な器具で身を外します。皿を仕上げる短い間だけ取り置きます。'],
['えびといかを加熱する','ソースを穏やかに沸かし、えび250 gといか250 gを加えます。混ぜながら約3–4分、えびが引き締まり不透明になり、いかの半透明感がなくなるまで加熱します。細い温度計のプローブで厚い部分が少なくとも63 °Cに達することを確認し、足りなければ加熱を続け再測定します。大きさと開始温度で時間は変わります。パスタの仕上げ中に加熱が続かないよう、魚介を別の清潔なボウルへ取り出します。生魚介のボウルは使いません。'],
['パスタをゆでて湯を取り分ける','この工程が魚介の加熱終了に近づくよう開始時点を調整します。パスタは並行してゆでられます。スパゲッティ320 gを塩なしの沸騰した湯に入れ、最初に混ぜてほぐし、袋のアルデンテ表示より2分短くゆでます。ソースで仕上げます。湯を切る前にゆで汁150 mlをカップに取り、水洗いせず湯を切ります。パスタや魚介に時間が必要なら合計時間を延長し、不十分な加熱を急いで終わらせません。'],
['ソースでパスタを仕上げる','湯を切ったスパゲッティをソースへ加え、中火で約2分混ぜてアルデンテに仕上げます。ソースがパスタに絡み、底にたまらないよう、必要な分だけゆで汁を30 mlずつ足します。最後の30秒にえび、いか、ムール貝、パセリを戻し、崩さないよう優しく混ぜて温めます。清潔な器具で味見し、予定の塩3 gを加えます。貝の煮汁で十分塩味があるなら減らしますが、推定ナトリウム量も変わります。閉じた貝や殻の破片は加えません。'],
['すぐに盛り付け残りを冷蔵する','パスタと3種類の魚介を均等に分けて4皿に盛り、すぐに食べます。加熱が長いとえびやいかが硬くなります。残りは殻を除いて小さい容器に分け、2時間以内、室温が32 °Cを超えるなら1時間以内に4 °C以下で冷蔵します。品質のため24時間以内に食べることを提案します。食べる分だけ取り、混ぜながら複数箇所で少なくとも74 °Cまで再加熱します。組み立てた皿の冷凍はパスタと魚介の食感が変わるため提案していません。']],
'notes':'この皿は3種類の魚介を含みます。市販のシーフードミックスへの置き換えは分量、工程、栄養値が変わります。認可された販売元から生きたムール貝を買い、販売元の保存指示に従います。生のむきえびと下処理済みいかを使い、重量を可食部にそろえます。ワインやチーズを足すと同じ栄養計算は使えません。ソースの調整にはゆで汁を少しずつ使い、カップ全量を必ず加えるわけではありません。生魚介用まな板やボウルは洗わず再使用しません。甲殻類、軟体動物、小麦を含みます。その他の原材料や混入の表示も確認します。推定時間より温度と加熱状態の確認を優先します。',
'faq':[['開かないムール貝はどうしますか？','加熱後も閉じた貝は無理に開いて加えず捨てます。加熱前にも割れた貝や軽くたたいても閉じない開いた貝を除きます。'],['冷凍の魚介を使えますか？','えびといかは開始前に冷蔵庫で解凍し、殻や内臓を除いた重量で量ります。解凍は50分に含めません。この提案は生きた殻付きムール貝を使い、冷凍ムール貝へ直接置き換えるものではありません。'],['パスタが乾くのを防ぐには？','ゆで汁150 mlを取り、ソースで仕上げるときに必要な分だけ30 mlずつ足します。魚介は最後に戻し、長い再加熱を避けます。']],
'keywords':['魚介のパスタ','シーフードスパゲッティ','えびいかムール貝のパスタ'],'cover_alt':'トマトソースのスパゲッティにむきえび、いかの輪切り、開いたムール貝、パセリ',
'nutrition':{'serving_size':'4皿のうち1皿、殻を除く','method':'確認済みUSDA資料10件を使い、パスタは乾燥重量、魚介は生の可食重量で合計を4で割っています。ムール貝は殻付き600 gから身150 g、25%の歩留まりを提案しており、調理時の計量前です。えびといかは混合種の資料、ムール貝は生のブルームール貝の資料で近似します。油、トマト、ソースの塩は全量計上。パスタは無塩の湯でゆで、捨てる湯と殻を除外しています。','note':'情報用の推定で完成品の分析値ではありません。貝の実際の歩留まり、廃棄、種類、えびの添加物の有無、製品により変わります。チーズ、パン、ワインは除外。貝の煮汁には提案歩留まりに完全には反映されない塩分が含まれる場合があります。'}
},
'pt':{
'path':'/pt/massa-com-frutos-do-mar','historical_path':False,'title':'Massa com frutos do mar e tomate','seo_title':'Massa com frutos do mar e tomate',
'excerpt':'Massa com frutos do mar para 4 com camarão, lula e mexilhões: molho de tomate, cozimento por etapas e passos para terminar o espaguete.',
'summary':'Esta massa combina espaguete, camarão, lula e mexilhões em um molho rápido de tomate, alho, cebola e salsinha. Os mexilhões são abertos à parte para coar o líquido; os outros frutos do mar cozinham no molho e ficam reservados enquanto a massa termina de cozinhar.\n\nA proposta rende 4 pratos e estima 25 minutos de preparo e 25 de cozimento, 50 no total, com água, massa e mexilhões em paralelo quando possível. Quantidades, tempos e rendimento aguardam teste de cozinha. A nutrição propõe 150 g de carne comestível a partir de 600 g de mexilhões com concha; o rendimento real precisa ser pesado.',
'difficulty':'Média','course':'Prato principal','cuisine':'Mediterrânea, proposta caseira',
'ingredients':['Espaguete seco','Camarão cru sem casca','Lula crua limpa','Mexilhões vivos com concha','Tomate triturado em conserva','Cebola','Alho','Azeite de oliva','Salsinha fresca','Sal','Água para a massa, sem sal','Água para abrir os mexilhões'],
'groups':{'Pasta y marisco':'Massa e frutos do mar','Salsa':'Molho','Cocción':'Cozimento'},
'steps':[
['Limpe e confira os frutos do mar','Use 250 g de camarão cru já sem casca e sem intestino e 250 g de lula limpa: corpo sem pele nem vísceras, tentáculos sem bico. Corte o corpo em anéis de cerca de 0,5 cm e divida os tentáculos grandes. Confira os 600 g de mexilhões vivos com concha de fornecedor autorizado: descarte conchas quebradas e os abertos que não se fecharem com uma batida leve. Escove sob água fria e retire as barbas pouco antes de cozinhar; não os deixe submersos em água doce. Mantenha os frutos do mar separados e refrigerados a 4 °C ou menos enquanto faz o molho. Se camarão ou lula estiverem congelados, descongele antes na geladeira; essa espera não entra nos 50 minutos.'],
['Pique os aromáticos e aqueça a água','Pique os 100 g de cebola e os 12 g de alho em uma tábua limpa diferente daquela dos frutos do mar crus. Lave e pique os 8 g de salsinha. Coloque os 3 litros de água para massa em uma panela grande e leve à fervura sem sal: o tempero vai no molho. Prepare outra panela com tampa para mexilhões e uma frigideira grande para o molho. Lave mãos e utensílios após tocar frutos do mar crus; use uma tigela limpa para os cozidos.'],
['Faça um molho rápido de tomate','Aqueça os 30 g de azeite na frigideira em fogo médio. Refogue a cebola 5 minutos até amaciar sem queimar. Acrescente o alho e mexa 1 minuto. Junte os 400 g de tomate triturado e cozinhe em fervura suave 8 minutos, mexendo, até perder parte da água e do sabor muito cru. Mantenha quente em fogo baixo. Os 14 minutos são uma referência; evite que seque ou grude.'],
['Abra os mexilhões no vapor','Enquanto faz o molho, ferva os 100 ml de água na panela de mexilhões. Acrescente os limpos, tampe e cozinhe por cerca de 4–5 minutos, sacudindo a panela cuidadosamente uma vez. Retire os abertos para uma tigela limpa; descarte os ainda fechados no final sem forçar a abertura. Guarde até 100 ml do líquido e passe por peneira fina com gaze limpa para retirar areia; acrescente ao molho. Deixe alguns nas conchas para servir e retire a carne dos outros com utensílios limpos. Reserve só enquanto termina o prato.'],
['Cozinhe camarão e lula','Leve o molho à fervura suave e acrescente os 250 g de camarão e os 250 g de lula. Cozinhe cerca de 3–4 minutos, mexendo, até o camarão ficar firme e opaco e a lula perder a transparência. Com uma sonda fina confira pelo menos 63 °C nas partes mais grossas; se faltar temperatura, continue e meça novamente. O tempo depende do tamanho e da temperatura inicial. Retire os frutos do mar cozidos para outra tigela limpa para não continuarem cozinhando enquanto a massa termina. Não use a tigela dos crus.'],
['Cozinhe a massa e reserve água','Calcule o início para terminar esta etapa perto dos frutos do mar, pois a massa pode cozinhar em paralelo. Coloque os 320 g de espaguete na água fervente sem sal, mexa no começo para separar e cozinhe 2 minutos menos que o tempo al dente indicado na embalagem: terminará no molho. Antes de escorrer, guarde 150 ml da água em uma xícara. Escorra sem enxaguar. Se massa ou frutos do mar precisarem de mais tempo, aumente o total; não apresse um cozimento insuficiente.'],
['Termine a massa no molho','Acrescente o espaguete escorrido ao molho e misture em fogo médio por cerca de 2 minutos até ficar al dente. Adicione água reservada de 30 em 30 ml só se necessário para o molho envolver a massa sem poça. Nos últimos 30 segundos incorpore camarão, lula, mexilhões e salsinha com cuidado para aquecer sem desfazer. Prove com utensílio limpo e acrescente os 3 g de sal previstos, ou menos se o líquido de mexilhão já salgar bastante; menos sal altera o sódio estimado. Não acrescente conchas fechadas nem fragmentos de concha.'],
['Sirva na hora e refrigere as sobras','Divida em 4 pratos distribuindo igualmente a massa e os três tipos de frutos do mar. Sirva imediatamente; calor prolongado endurece camarão e lula. Retire as conchas antes de guardar sobras, divida em recipientes pequenos e refrigere a 4 °C ou menos em até 2 horas, ou 1 hora se o ambiente passar de 32 °C. Propõe-se consumir em 24 horas por qualidade; reaqueça só a porção que vai comer, mexendo até pelo menos 74 °C em vários pontos. Não se propõe congelar o prato montado, pois massa e frutos do mar perdem textura.']],
'notes':'A identidade do prato inclui os três tipos de frutos do mar; uma mistura comercial muda quantidades, preparo e nutrição. Compre mexilhões vivos de origem autorizada e siga as instruções de conservação do fornecedor. Escolha camarão cru sem casca e lula já limpa para que os pesos sejam comestíveis. Acrescentar vinho ou queijo muda o cálculo. Ajuste o molho com pequenas quantidades de água da massa, não com a xícara inteira obrigatoriamente. Não reutilize tábuas ou tigelas dos crus sem lavar. Contém crustáceos, moluscos e trigo; confira também rótulos para outros ingredientes ou traços. Temperatura e sinais de cozimento prevalecem sobre o tempo proposto.',
'faq':[['O que faço com mexilhões que não abrem?','Descarte os ainda fechados depois de cozinhar sem forçá-los para acrescentar. Antes do cozimento descarte também conchas quebradas e os abertos que não se fecharem com toque suave.'],['Posso usar frutos do mar congelados?','Para camarão e lula, descongele na geladeira antes de começar e pese sem casca ou limpos. A descongelação não entra nos 50 minutos. Esta proposta usa mexilhões vivos com concha, não uma troca direta por mexilhão congelado.'],['Como evito massa seca?','Reserve 150 ml da água da massa e adicione de 30 em 30 ml só o necessário ao terminar o espaguete no molho. Devolva os frutos do mar no fim para evitar aquecimento prolongado.']],
'keywords':['massa com frutos do mar','espaguete com frutos do mar','massa com camarão lula e mexilhão'],'cover_alt':'Espaguete com molho de tomate, camarões sem casca, anéis de lula, mexilhões abertos e salsinha',
'nutrition':{'serving_size':'1 de 4 pratos, sem conchas','method':'Dez fichas USDA verificadas, peso seco da massa e cru comestível dos frutos do mar, total dividido por 4. Rendimento proposto de mexilhão: 150 g de carne a partir de 600 g com concha, equivalente a 25%, ainda a pesar em cozinha. Camarão e lula aproximados por fichas de espécies mistas; mexilhão por mexilhão azul cru. Azeite, tomate e sal do molho contados integralmente. Massa em água sem sal; água escorrida e conchas excluídas.','note':'Estimativa informativa, não análise do prato pronto. Rendimento real dos mexilhões, descartes, espécie, possíveis aditivos do camarão e marcas alteram os valores. Queijo, pão e vinho excluídos; o líquido de mexilhões pode acrescentar sais não totalmente refletidos pelo rendimento proposto.'}
}})
p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n');print('All six seafood pasta localizations authored; media QA and publication remain pending.')
