import json
from pathlib import Path
p = Path(__file__).resolve().parents[1] / 'editorial/receta-de-alfajores-de-maicena-localizaciones-20261008.json'
assert not p.exists()
data = {
 'en': {
  'path':'/en/cornstarch-alfajores-recipe','historical_path':True,
  'title':'Cornstarch alfajores with dulce de leche and coconut',
  'seo_title':'Cornstarch alfajores with dulce de leche and coconut',
  'excerpt':'Make 20 cornstarch alfajores with dulce de leche and coconut. Follow measured ingredients, chilled yolk dough and two batches of pale cookie rounds.',
  'summary':'These cornstarch alfajores sandwich thick dulce de leche between two tender cookies made with cornstarch and wheat flour. Coconut coats only the filling edge, while vanilla and lemon zest flavour the yolk dough.\n\nThe proposal makes 20 alfajores about 5 cm across, from 40 rounds rolled 6 mm thick and baked in two batches. The estimated 130 minutes include 30 minutes of chilling and 30 of cooling. Quantities, yield and times still need confirmation in a kitchen test.',
  'difficulty':'Medium','course':'Dessert','cuisine':'Argentinian',
  'ingredients':['Cornstarch','All-purpose wheat flour','Unsalted butter','White sugar','Egg yolks, about 3 large; weigh 51 g','Double-acting baking powder','Vanilla extract','Lemon zest','Dulce de leche','Unsweetened desiccated coconut'],
  'groups':{'Masa':'Dough','Relleno y acabado':'Filling and finish'},
  'steps':[
   ['Weigh and sift the dry ingredients','Wash your hands and clean the work surface. Weigh every ingredient; the 3 yolks should total about 51 g. Sift the 200 g cornstarch, 100 g flour and 6 g baking powder together into a bowl. Wash the lemon before grating only its yellow peel to obtain 3 g zest. Keep the dulce de leche and coconut separate from utensils that will touch raw dough.'],
   ['Cream the butter and add the yolks','Use the 100 g butter softened enough to yield when pressed, but not melted. Beat it with the 80 g sugar for 2–3 minutes until creamy. Add the yolks in three additions, beating each one in before adding the next. Mix in the 5 g vanilla and 3 g zest; scrape the bowl sides with a spatula.'],
   ['Bring the dough together and chill','Add the dry ingredients in two batches. Mix with a spatula, then gently bring together by hand just until no powdery patches remain; do not knead like bread. Flatten into a disc, wrap and refrigerate for 30 minutes at 4 °C or below. Do not taste raw dough: it contains uncooked flour and egg. Wash your hands, bowl and surface after handling it.'],
   ['Roll and cut forty rounds','Preheat to 180 °C in a conventional oven or 160 °C fan. Line two trays about 30 × 40 cm with baking parchment. Roll the dough between two sheets of parchment to about 6 mm thick. Cut 5 cm rounds; gently gather scraps and roll again without overworking. Aim for 40 similar rounds, about 13–14 g dough each, to make 20 pairs. Place 20 on each tray with about 2 cm gaps. If the dough softens, chill for 10 minutes and add that waiting time to the total.'],
   ['Bake the cookies in two batches','Bake one tray at a time on the middle shelf for 12–15 minutes. The tops should be matte and firm, the bases only lightly golden, with no damp centre. Check from 12 minutes; thickness and oven performance can change the time. Remove with oven gloves, then bake the second tray the same way. The cooking estimate allows 30 minutes for both batches; do not aim for a deeply toasted colour.'],
   ['Cool completely','Leave the cookies on their tray for 5 minutes because they are still fragile. Transfer with a broad spatula to a wire rack and cool for about 25 more minutes, until completely cold. Do not fill warm cookies: the dulce de leche would soften and the cookies would break more easily.'],
   ['Fill and coat the edges in coconut','Pair the 40 cookies by size and turn one of each pair bottom-side up. Divide the 350 g thick dulce de leche among the 20 bases, about 17–18 g per alfajor, using a clean spoon or piping bag. Top with the second cookie and press gently until the filling barely reaches the edge. Put the 30 g coconut in a shallow dish and roll only each alfajor’s edge in it so it sticks to the filling.'],
   ['Serve and store','Serve the 20 alfajores once the filling has settled, handling them gently. Store in a closed container with paper between layers, refrigerated at 4 °C or below, and eat within 3 days or sooner if required by the dulce de leche label. To freeze, wrap individually for up to 1 month and thaw in the refrigerator. These are conservative proposed storage periods, not shelf-life test results; coconut and cookies soften over time.']
  ],
  'notes':'Use white cornstarch, not yellow corn flour. The dulce de leche should be thick, preferably a baking variety; a runny one will escape the edges. You may omit the coconut, but the finish and nutrition will change. No untested gluten-free substitution is proposed: this dough contains wheat. If it cracks when rolled, let it warm slightly for a few minutes and press gently between parchment; do not add unmeasured flour. Contains wheat, egg and milk. Avoid tasting raw dough and clean up before handling baked cookies.',
  'faq':[['Why do the cookies break?','They are fragile straight from the oven. Leave them on the tray for 5 minutes, move them with a broad spatula and let them cool completely before filling. Overworking the dough or rolling too thin also changes the texture.'],['Can I use corn flour instead of cornstarch?','Not as a direct replacement. This recipe uses white cornstarch; yellow corn flour has a different composition and texture. The recipe also contains wheat flour.'],['What if my dulce de leche is too runny?','Use thick baking-style dulce de leche to support the cookies. Do not fill them while warm. Changing the filling can affect texture, storage and nutrition.']],
  'keywords':['cornstarch alfajores','dulce de leche sandwich cookies','coconut alfajores'],
  'cover_alt':'Pale cornstarch alfajores with dulce de leche and coconut around the edges, one broken open',
  'nutrition':{'serving_size':'1 of 20 alfajores','method':'Ten verified USDA entries per 100 g are weighted by all ingredient amounts and divided by 20. All planned filling and coconut are included; water lost during baking is not subtracted from the total nutrient contribution.','note':'An informational estimate, not an analysis of the finished alfajor. Dulce de leche, butter and baking powder brands change the result. All dough, filling and coconut are assumed eaten; leftovers on utensils would reduce the actual contribution.'}
 },
 'de': {
  'path':'/de/maisstarke-alfajores-rezept','historical_path':True,
  'title':'Maisstärke-Alfajores mit Dulce de Leche und Kokos',
  'seo_title':'Maisstärke-Alfajores mit Dulce de Leche und Kokos',
  'excerpt':'20 Alfajores mit Maisstärke, Dulce de Leche und Kokosrand: genaue Mengen, gekühlter Eigelbteig und helle Keksböden aus zwei Backdurchgängen.',
  'summary':'Diese Alfajores bestehen aus zwei zarten Keksen mit Maisstärke und Weizenmehl, dazwischen dicke Dulce de Leche. Kokos haftet nur am Füllungsrand. Zitronenabrieb und Vanille aromatisieren den Eigelbteig.\n\nDer Vorschlag ergibt 20 Alfajores von etwa 5 cm Durchmesser: 40 Kreise mit 6 mm Dicke, in zwei Durchgängen gebacken. Die geschätzten 130 Minuten enthalten 30 Minuten Kühlen und 30 Minuten Auskühlen. Mengen, Ausbeute und Zeiten wurden noch nicht durch einen Küchentest bestätigt.',
  'difficulty':'Mittel','course':'Dessert','cuisine':'Argentinisch',
  'ingredients':['Maisstärke','Weizenmehl für alle Zwecke','Ungesalzene Butter','Weißer Zucker','Eigelb, etwa 3 große; 51 g abwiegen','Doppelt wirkendes Backpulver','Vanilleextrakt','Zitronenabrieb','Dulce de Leche','Ungesüßte getrocknete Kokosraspel'],
  'groups':{'Masa':'Teig','Relleno y acabado':'Füllung und Abschluss'},
  'steps':[
   ['Trockene Zutaten wiegen und sieben','Hände waschen und die Arbeitsfläche reinigen. Alle Zutaten abwiegen; die 3 Eigelbe sollen zusammen etwa 51 g wiegen. 200 g Maisstärke, 100 g Mehl und 6 g Backpulver gemeinsam in eine Schüssel sieben. Die Zitrone waschen und nur die gelbe Schale abreiben, bis 3 g erreicht sind. Dulce de Leche und Kokos getrennt von Geräten halten, die rohen Teig berühren werden.'],
   ['Butter aufschlagen und Eigelb einarbeiten','100 g weiche Butter verwenden, die auf Druck nachgibt, aber nicht geschmolzen ist. Mit 80 g Zucker 2–3 Minuten cremig schlagen. Die Eigelbe in drei Portionen zugeben und jede vollständig einarbeiten. 5 g Vanille und 3 g Zitronenabrieb untermischen; die Schüsselwände mit einem Teigschaber abstreifen.'],
   ['Teig formen und kühlen','Die trockenen Zutaten in zwei Portionen zugeben. Mit dem Teigschaber mischen und zuletzt mit den Händen vorsichtig zusammenfügen, bis keine pulvrigen Stellen mehr bleiben; nicht wie Brot kneten. Zu einer flachen Scheibe formen, einwickeln und 30 Minuten bei höchstens 4 °C kühlen. Rohen Teig nicht probieren: Er enthält ungegartes Mehl und Ei. Danach Hände, Schüssel und Arbeitsfläche waschen.'],
   ['Vierzig Teigkreise ausstechen','Ofen auf 180 °C Ober-/Unterhitze oder 160 °C Umluft vorheizen. Zwei etwa 30 × 40 cm große Bleche mit Backpapier belegen. Teig zwischen zwei Papierbögen etwa 6 mm dick ausrollen. Kreise mit 5 cm Durchmesser ausstechen; Reste vorsichtig zusammenfügen und erneut ausrollen, ohne viel zu kneten. 40 gleichmäßige Kreise von jeweils etwa 13–14 g Teig für 20 Paare anstreben. Je 20 mit etwa 2 cm Abstand auf ein Blech legen. Wird der Teig weich, 10 Minuten kühlen und diese Wartezeit zur Gesamtzeit addieren.'],
   ['Kekse in zwei Durchgängen backen','Jeweils ein Blech auf mittlerer Schiene 12–15 Minuten backen. Die Oberseite soll matt und fest, der Boden nur leicht goldgelb sein, ohne feuchten Kern. Ab Minute 12 prüfen; Dicke und Ofen können die Zeit verändern. Mit Ofenhandschuhen herausnehmen und das zweite Blech genauso backen. Die Garzeitschätzung reserviert 30 Minuten für beide Durchgänge; keine kräftige Bräunung anstreben.'],
   ['Vollständig auskühlen lassen','Die Kekse 5 Minuten auf dem Blech lassen, weil sie noch zerbrechlich sind. Mit einem breiten Wender auf ein Gitter setzen und etwa weitere 25 Minuten vollständig abkühlen lassen. Warme Kekse nicht füllen: Dulce de Leche würde weicher und die Kekse könnten leichter brechen.'],
   ['Füllen und Rand in Kokos wenden','Die 40 Kekse nach Größe zu Paaren ordnen und jeweils einen mit dem Boden nach oben legen. 350 g dicke Dulce de Leche mit einem sauberen Löffel oder Spritzbeutel auf die 20 Böden verteilen, etwa 17–18 g je Alfajor. Zweiten Keks auflegen und vorsichtig drücken, bis die Füllung knapp am Rand sichtbar wird. 30 g Kokos in einen flachen Teller geben und nur den Rand jedes Alfajors darin rollen, sodass Kokos an der Füllung haftet.'],
   ['Servieren und aufbewahren','Die 20 Alfajores vorsichtig servieren, sobald die Füllung sitzt. In einem geschlossenen Behälter mit Papier zwischen den Lagen bei höchstens 4 °C kühlen und innerhalb von 3 Tagen verzehren, oder früher, wenn die Dulce-de-Leche-Packung es verlangt. Zum Einfrieren einzeln einwickeln, höchstens 1 Monat aufbewahren und im Kühlschrank auftauen. Diese Zeiten sind konservative Vorschläge, keine Haltbarkeitsprüfung; Kokos und Kekse werden mit der Zeit weicher.']
  ],
  'notes':'Weiße Maisstärke verwenden, kein gelbes Maismehl. Dulce de Leche soll dick sein, möglichst eine Backvariante; flüssige Füllung läuft heraus. Kokos kann entfallen, verändert aber Aussehen und Nährwerte. Ein ungetesteter glutenfreier Ersatz wird nicht vorgeschlagen: Der Teig enthält Weizen. Reißt er beim Ausrollen, einige Minuten leicht wärmer werden lassen und sanft zwischen Papier drücken; kein ungewogenes Mehl ergänzen. Enthält Weizen, Ei und Milch. Rohen Teig nicht probieren und vor dem Berühren gebackener Kekse reinigen.',
  'faq':[['Warum brechen die Kekse?','Direkt nach dem Backen sind sie zerbrechlich. 5 Minuten auf dem Blech lassen, mit einem breiten Wender bewegen und vor dem Füllen ganz abkühlen. Zu viel Kneten oder zu dünnes Ausrollen verändert ebenfalls die Textur.'],['Kann ich Maismehl statt Maisstärke verwenden?','Nicht als direkten Ersatz. Verwendet wird weiße Maisstärke; gelbes Maismehl hat eine andere Zusammensetzung und Textur. Das Rezept enthält außerdem Weizenmehl.'],['Was tun, wenn Dulce de Leche zu flüssig ist?','Dicke Dulce de Leche zum Backen verwenden, damit sie die Kekse trägt. Nicht warm füllen. Eine andere Füllung kann Konsistenz, Lagerung und Nährwerte verändern.']],
  'keywords':['Maisstärke Alfajores','Dulce de Leche Kekse','Alfajores mit Kokos'],
  'cover_alt':'Helle Maisstärke-Alfajores mit Dulce de Leche und Kokosrand, eines geöffnet mit sichtbarer Füllung',
  'nutrition':{'serving_size':'1 von 20 Alfajores','method':'Zehn überprüfte USDA-Einträge je 100 g werden mit allen Zutatengewichten gewichtet und durch 20 geteilt. Die gesamte vorgesehene Füllung und der Kokos sind enthalten; Wasserverlust beim Backen wird nicht vom gesamten Nährstoffbeitrag abgezogen.','note':'Informative Schätzung, keine Analyse des fertigen Alfajors. Marken von Dulce de Leche, Butter und Backpulver verändern das Ergebnis. Der Verzehr des gesamten Teigs, der Füllung und des Kokos wird angenommen; Reste an Geräten würden den tatsächlichen Beitrag verringern.'}
 },
 'fr': {
  'path':'/fr/recette-fecule-de-mais-alfajores','historical_path':True,
  'title':'Alfajores à la fécule de maïs, dulce de leche et coco',
  'seo_title':'Alfajores à la fécule de maïs et dulce de leche',
  'excerpt':'Préparez 20 alfajores à la fécule de maïs, dulce de leche et coco. Doses précises, pâte aux jaunes refroidie et biscuits clairs cuits en deux fournées.',
  'summary':'Ces alfajores associent deux biscuits tendres à la fécule de maïs et à la farine de blé, une garniture de dulce de leche et de la noix de coco uniquement sur le bord. Vanille et zeste de citron parfument la pâte aux jaunes.\n\nLa proposition donne 20 alfajores d’environ 5 cm : 40 disques de 6 mm, cuits en deux fournées. Les 130 minutes estimées incluent 30 minutes au froid et 30 minutes de refroidissement. Quantités, rendement et temps restent à confirmer par un essai en cuisine.',
  'difficulty':'Moyenne','course':'Dessert','cuisine':'Argentine',
  'ingredients':['Fécule de maïs','Farine de blé tous usages','Beurre doux','Sucre blanc','Jaunes d’œufs, environ 3 gros ; peser 51 g','Levure chimique à double action','Extrait de vanille','Zeste de citron','Dulce de leche','Noix de coco râpée sèche non sucrée'],
  'groups':{'Masa':'Pâte','Relleno y acabado':'Garniture et finition'},
  'steps':[
   ['Peser et tamiser les ingrédients secs','Lavez-vous les mains et nettoyez le plan de travail. Pesez tous les ingrédients ; les 3 jaunes doivent totaliser environ 51 g. Tamisez ensemble les 200 g de fécule, 100 g de farine et 6 g de levure dans un saladier. Lavez le citron avant de prélever uniquement son zeste jaune pour en obtenir 3 g. Gardez dulce de leche et coco à l’écart des ustensiles destinés à la pâte crue.'],
   ['Crémer le beurre et ajouter les jaunes','Utilisez 100 g de beurre souple sous la pression, mais non fondu. Battez avec les 80 g de sucre pendant 2–3 minutes jusqu’à obtenir une crème. Ajoutez les jaunes en trois fois, en incorporant chacun avant le suivant. Ajoutez les 5 g de vanille et 3 g de zeste ; raclez les parois avec une spatule.'],
   ['Former et refroidir la pâte','Ajoutez les ingrédients secs en deux fois. Mélangez à la spatule puis rassemblez doucement à la main, juste jusqu’à disparition des zones poudreuses ; ne pétrissez pas comme du pain. Aplatissez en disque, emballez et réfrigérez 30 minutes à 4 °C maximum. Ne goûtez pas la pâte crue : elle contient farine et œuf non cuits. Lavez ensuite mains, saladier et surface.'],
   ['Étaler et découper quarante disques','Préchauffez à 180 °C en chaleur traditionnelle ou 160 °C ventilée. Chemisez deux plaques d’environ 30 × 40 cm de papier cuisson. Étalez la pâte entre deux feuilles sur environ 6 mm d’épaisseur. Découpez des cercles de 5 cm ; rassemblez les chutes sans trop pétrir et étalez à nouveau. Visez 40 disques similaires, d’environ 13–14 g de pâte chacun, pour 20 paires. Placez-en 20 par plaque avec environ 2 cm d’écart. Si la pâte ramollit, réfrigérez 10 minutes et ajoutez cette attente au temps total.'],
   ['Cuire les biscuits en deux fournées','Cuisez une plaque à la fois au milieu du four pendant 12–15 minutes : dessus mat et ferme, dessous à peine doré, sans centre humide. Vérifiez dès 12 minutes ; l’épaisseur et le four peuvent changer la durée. Sortez avec des gants puis cuisez la deuxième plaque de la même façon. Le calcul prévoit 30 minutes pour les deux fournées ; ne cherchez pas une coloration soutenue.'],
   ['Laisser refroidir complètement','Laissez les biscuits 5 minutes sur leur plaque, car ils sont encore fragiles. Transférez avec une spatule large sur une grille et laissez refroidir environ 25 minutes de plus, jusqu’à refroidissement complet. Ne garnissez pas des biscuits tièdes : le dulce de leche ramollirait et les biscuits se casseraient plus facilement.'],
   ['Garnir et rouler les bords dans la noix de coco','Appariez les 40 biscuits par taille et retournez un biscuit de chaque paire, dessous vers le haut. Répartissez les 350 g de dulce de leche épais sur les 20 bases, environ 17–18 g par alfajor, avec une cuillère ou une poche propre. Posez le second biscuit et pressez doucement jusqu’à faire apparaître un peu de garniture au bord. Mettez les 30 g de coco dans une assiette et roulez seulement le bord de chaque alfajor pour la faire adhérer à la garniture.'],
   ['Servir et conserver','Servez les 20 alfajores une fois la garniture en place, en les manipulant avec précaution. Conservez dans une boîte fermée, avec du papier entre les couches, à 4 °C maximum, et consommez sous 3 jours ou plus tôt si l’étiquette du dulce de leche l’exige. Pour congeler, emballez individuellement jusqu’à 1 mois et décongelez au réfrigérateur. Ces durées sont des propositions prudentes, pas un essai de durée de vie ; coco et biscuits ramolliront avec le temps.']
  ],
  'notes':'Utilisez de la fécule blanche, pas de farine de maïs jaune. Le dulce de leche doit être épais, de préférence pour pâtisserie ; une version liquide déborde. La coco peut être omise, mais finition et nutrition changent. Aucune substitution sans gluten non testée n’est proposée : la pâte contient du blé. Si elle se fissure à l’étalage, laissez-la se réchauffer légèrement quelques minutes et pressez doucement entre les papiers ; n’ajoutez pas de farine non pesée. Contient blé, œuf et lait. Ne goûtez pas la pâte crue et nettoyez avant de manipuler les biscuits cuits.',
  'faq':[['Pourquoi les biscuits se cassent-ils ?','Ils sont fragiles à la sortie du four. Laissez-les 5 minutes sur la plaque, déplacez-les avec une spatule large et refroidissez-les complètement avant de garnir. Trop pétrir ou étaler trop fin modifie aussi la texture.'],['Puis-je remplacer la fécule par de la farine de maïs ?','Pas directement. Cette recette utilise de la fécule blanche ; la farine de maïs jaune a une composition et une texture différentes. Elle contient aussi de la farine de blé.'],['Que faire si le dulce de leche est trop liquide ?','Utilisez une version épaisse pour pâtisserie afin de soutenir les biscuits. Ne garnissez pas à chaud. Une autre garniture peut modifier texture, conservation et nutrition.']],
  'keywords':['alfajores fécule de maïs','biscuits au dulce de leche','alfajores noix de coco'],
  'cover_alt':'Alfajores clairs au dulce de leche et aux bords de noix de coco, un biscuit ouvert montrant la garniture',
  'nutrition':{'serving_size':'1 des 20 alfajores','method':'Dix fiches USDA vérifiées pour 100 g sont pondérées par tous les poids d’ingrédients et divisées par 20. Toute la garniture et la coco prévues sont incluses ; la perte d’eau à la cuisson n’est pas soustraite de l’apport total.','note':'Estimation informative, pas analyse de l’alfajor préparé. Les marques de dulce de leche, beurre et levure modifient le résultat. Toute la pâte, la garniture et la coco sont supposées consommées ; les restes sur les ustensiles réduiraient l’apport réel.'}
 }
}
p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
