import json
from pathlib import Path
p=Path(__file__).resolve().parents[1]/'editorial/ensalada-de-pollo-con-aguacate-y-mango-localizaciones-20261008.json'
data=json.loads(p.read_text());assert set(data)=={'en','de','fr'}
data.update({
 'it':{
  'path':'/it/insalata-di-pollo-con-avocado-e-mango-2','historical_path':True,
  'title':'Insalata di pollo con avocado e mango','seo_title':'Insalata di pollo con avocado e mango',
  'excerpt':'Insalata di pollo, avocado e mango per 4: pollo in padella e condimento al lime. Lava, cuoci, taglia e assembla senza schiacciare la frutta.',
  'summary':'Questa insalata combina pollo cotto in padella, cubetti di avocado e mango, lattuga, cetriolo e cipolla rossa. Lime, olio d’oliva e poco miele legano gli ingredienti senza una salsa densa.\n\nLa proposta rende 4 porzioni. I 55 minuti stimati comprendono 30 di preparazione, 20 di cottura in due riprese e 5 di riposo. Controlla il pollo con un termometro: almeno 74 °C. Dosi, tempi e resa sono ancora da confermare con una prova in cucina.',
  'difficulty':'Facile','course':'Insalata come piatto principale','cuisine':'Internazionale',
  'ingredients':['Petto di pollo crudo senza pelle e ossa','Polpa di avocado','Polpa di mango','Cetriolo con buccia','Lattuga romana','Cipolla rossa','Succo di lime','Olio d’oliva','Miele','Sale','Pepe nero'],
  'groups':{'Ensalada':'Insalata','Cocción y aliño':'Cottura e condimento'},
  'steps':[
   ['Lava e asciuga le verdure','Lava le mani e prepara un tagliere pulito per frutta e verdura, separato da quello del pollo. Sciacqua cetriolo, mango, avocado e lime sotto acqua corrente prima di tagliare o sbucciare, senza sapone. Lava e asciuga bene i 100 g di lattuga, salvo indicazione pronta al consumo sulla confezione. Taglia 150 g di cetriolo a mezze lune sottili e 40 g di cipolla a fettine; tieni in frigorifero con la lattuga mentre cuoci.'],
   ['Prepara quattro filetti di pollo','Non lavare il pollo crudo. Sul tagliere separato dividi 600 g di petto senza pelle e ossa in quattro filetti di circa 150 g, spessi uniformemente circa 1,5 cm. Se serve, appiattisci delicatamente tra fogli adatti agli alimenti. Condisci con 1 g di sale e 0,5 g di pepe. Elimina la carta usata e lava mani e utensili; non mettere insalata o pollo cotto sul tagliere o piatto del pollo crudo.'],
   ['Cuoci e controlla la temperatura','Scalda una padella larga a fuoco medio con 5 g d’olio. Cuoci due filetti per circa 4–5 minuti per lato, senza muoverli finché si staccano; regola il fuoco se bruciano. Controlla con un termometro alimentare che il centro più spesso di ogni filetto raggiunga almeno 74 °C, senza toccare la padella con la sonda. Se manca temperatura, continua e misura ancora: colore e orologio non bastano. Trasferisci su un piatto pulito e ripeti con gli altri due filetti e i restanti 5 g d’olio per cottura. I 20 minuti previsti sono indicativi.'],
   ['Lascia riposare e taglia a strisce','Lascia riposare il pollo cotto 5 minuti sul piatto pulito. Con coltello e tagliere puliti, taglia ogni filetto in strisce larghe circa 1 cm. Deve smettere di emettere molto vapore prima dell’insalata; aspetta ancora se serve e aggiungi l’attesa al totale. Tieni da parte solo durante il montaggio, non per ore a temperatura ambiente.'],
   ['Taglia mango e avocado','Sbuccia il mango lavato, separa la polpa dal nocciolo e pesane 250 g. Taglia a cubetti di circa 2 cm. Apri l’avocado lavato, togli il nocciolo con un cucchiaio anziché colpirlo con il coltello, estrai la polpa e pesane 200 g. Taglia anche questa a cubetti di 2 cm. Usa il tagliere da frutta pulito senza contatto con pollo crudo e prepara entrambi poco prima di mescolare per limitare l’annerimento.'],
   ['Mescola il condimento al lime','In una ciotolina mescola 40 g di succo di lime, 10 g di miele, i restanti 2 g di sale e 0,5 g di pepe. Aggiungi 20 g d’olio riservati al condimento e sbatti con una forchetta fino a una miscela temporanea. Rimescola prima dell’uso se si separa. Il condimento non sostituisce la cottura del pollo né impedisce contaminazioni incrociate.'],
   ['Assembla delicatamente','Metti lattuga, cetriolo e cipolla in una ciotola grande e mescola con metà condimento. Aggiungi mango, avocado e strisce di pollo tiepido. Incorpora il resto con due cucchiai, sollevando delicatamente dal fondo senza schiacciare l’avocado. Dividi in quattro piatti con quantità simili di pollo e frutta.'],
   ['Servi e conserva in frigorifero','Servi appena composta, sola o con un accompagnamento non incluso nella nutrizione. Copri gli avanzi e metti in frigorifero a non più di 4 °C entro 2 ore, o 1 ora se l’ambiente supera 32 °C. Come proposta prudente, consuma l’insalata assemblata entro 24 ore; lattuga e avocado perderanno consistenza. Per anticipare, conserva pollo cotto, verdure e condimento separati al freddo e assembla al servizio. Non congelare l’insalata completa perché la consistenza cambierebbe molto.']
  ],
  'notes':'Scegli mango maturo ma sodo e avocado appena cedevole, non sfatto. Puoi sostituire il lime con lo stesso peso di succo di limone: cambiano sapore e nutrizione. Senza miele il condimento è più acido e i valori non restano uguali. Asciuga la lattuga per non diluirlo. Prepara solo la frutta necessaria; l’acido rallenta un po’ l’annerimento, senza conservare l’avocado indefinitamente. Separa gli utensili del pollo crudo da quelli degli alimenti pronti. La temperatura determina la cottura, non l’assenza di rosa.',
  'faq':[['Posso preparare in anticipo?','Conserva pollo già cotto, verdure e condimento separati al freddo, poi assembla al servizio. Taglia l’avocado vicino al montaggio. L’insalata condita perde consistenza; si propone consumo refrigerato entro 24 ore.'],['Come so se il pollo è cotto?','Misura il centro più spesso di ogni filetto con un termometro alimentare: almeno 74 °C. Tempo fisso e colore da soli non lo garantiscono.'],['Perché c’è acqua sul fondo?','Lattuga bagnata, mango troppo morbido e condimento aggiunto molto prima possono rilasciare liquido. Asciuga le foglie, usa frutta soda e mescola poco prima di servire.']],
  'keywords':['insalata pollo avocado mango','insalata pollo in padella','condimento al lime'],
  'cover_alt':'Insalata con pollo dorato a strisce, mango e avocado a cubetti, lattuga, cetriolo e cipolla rossa',
  'nutrition':{'serving_size':'1 delle 4 porzioni','method':'Undici schede USDA verificate per 100 g sono ponderate con i pesi commestibili indicati e divise per 4. Pollo calcolato su 600 g di petto crudo senza pelle e ossa; cipolla rossa approssimata con cipolla cruda generica. Tutti i 30 g d’olio e il condimento sono conteggiati, anche con residui in padella o ciotola.','note':'Stima informativa, non analisi dell’insalata pronta. Succhi persi in cottura, varietà della frutta, olio trattenuto e distribuzione cambiano il risultato. Non si conteggiano pane o altri accompagnamenti.'}
 },
 'ja':{
  'path':'/ja/chicken-avocado-mango-salad','historical_path':False,
  'title':'鶏肉とアボカド、マンゴーのサラダ','seo_title':'鶏肉とアボカド、マンゴーのサラダ｜ライムドレッシング',
  'excerpt':'フライパンで焼く鶏肉、アボカド、マンゴーの4人分サラダ。ライムのドレッシングと、洗う、焼く、切る、果物をつぶさず混ぜる手順を紹介します。',
  'summary':'フライパンで焼いた鶏肉、角切りのアボカドとマンゴー、レタス、きゅうり、紫玉ねぎを合わせます。ライム、オリーブ油、少量の蜂蜜のドレッシングで、濃厚なソースにせずまとめます。\n\n4人分を想定した提案です。推定55分には準備30分、2回に分ける加熱20分、休ませる時間5分を含みます。鶏肉は温度計で中心が74 °C以上であることを確認します。分量、時間、出来上がり量は調理試験でまだ確認していません。',
  'difficulty':'簡単','course':'主菜のサラダ','cuisine':'各国料理',
  'ingredients':['生の皮なし骨なし鶏むね肉','アボカドの果肉','マンゴーの果肉','皮付ききゅうり','ロメインレタス','紫玉ねぎ','ライム果汁','オリーブ油','蜂蜜','塩','黒こしょう'],
  'groups':{'Ensalada':'サラダ','Cocción y aliño':'加熱とドレッシング'},
  'steps':[
   ['野菜を洗って乾かす','手を洗い、鶏肉用とは別に清潔な果物・野菜用まな板を用意します。きゅうり、マンゴー、アボカド、ライムは切る、または皮をむく前に流水で洗い、石けんは使いません。レタス100 gは包装にそのまま食べられると表示されていない限り洗い、よく水気を切ります。きゅうり150 gを薄い半月切り、紫玉ねぎ40 gを薄切りにし、加熱中はレタスと冷蔵します。'],
   ['鶏肉を4枚に整える','生の鶏肉は洗いません。専用のまな板で皮なし骨なしむね肉600 gを約150 gずつ4枚に分け、約1.5 cmの均一な厚さにします。必要なら食品用シートで挟んで優しく平らにします。塩1 gとこしょう0.5 gで下味をつけます。使った紙を捨て、手と器具を洗います。生の鶏肉を置いたまな板や皿に、サラダや加熱済み鶏肉を置かないでください。'],
   ['焼いて中心温度を確認する','広いフライパンを油5 gと中火で温めます。鶏肉2枚を片面約4〜5分ずつ焼き、はがれるまで動かさず、焦げる場合は火を調整します。食品用温度計で各肉の最も厚い中心が74 °C以上になったことを確認し、プローブをフライパンに触れさせません。足りなければさらに焼いて再測定します。色や時間だけでは判断できません。清潔な皿に移し、残り2枚と加熱用の残りの油5 gで繰り返します。予定20分は目安です。'],
   ['休ませて細切りにする','加熱済み鶏肉を清潔な皿で5分休ませます。清潔な包丁とまな板で幅約1 cmの細切りにします。強い湯気が出なくなってからサラダに加え、必要ならさらに待ち、その時間を合計に加えます。盛り付けを終える間だけ取り置き、室温で何時間も放置しません。'],
   ['マンゴーとアボカドを切る','洗ったマンゴーの皮をむき、種から果肉を外して250 g量り、約2 cm角に切ります。洗ったアボカドを開き、包丁で種をたたかずスプーンで取り、果肉200 gを量ります。こちらも約2 cm角にします。生の鶏肉に触れていない清潔な果物用まな板を使い、アボカドの変色を抑えるため混ぜる直前に両方を切ります。'],
   ['ライムのドレッシングを混ぜる','小さなボウルにライム果汁40 g、蜂蜜10 g、残りの塩2 gとこしょう0.5 gを混ぜます。ドレッシング用の油20 gを加え、フォークで一時的になじむまで混ぜます。分離したら使う直前に再び混ぜます。ドレッシングは鶏肉の加熱の代わりにも、交差汚染の防止にもなりません。'],
   ['つぶさずに盛り合わせる','大きなボウルにレタス、きゅうり、玉ねぎを入れ、ドレッシングの半分と混ぜます。マンゴーとアボカド、少し温かい鶏肉を加えます。残りのドレッシングをスプーン2本で底から優しく持ち上げるように混ぜ、アボカドをつぶさないようにします。鶏肉と果物を均等に分け、4皿に盛ります。'],
   ['盛り付けて冷蔵保存する','混ぜたてをそのまま、または栄養計算に含まない付け合わせと出します。残りはふたをして2時間以内、周囲が32 °Cを超える場合は1時間以内に4 °C以下で冷蔵します。控えめな提案として、混ぜたサラダは24時間以内に食べます。レタスとアボカドの食感は変わります。前もって用意する場合は加熱済み鶏肉、野菜、ドレッシングを別々に冷蔵し、出すときに混ぜます。食感が大きく変わるため、完成したサラダ全体は冷凍しません。']
  ],
  'notes':'熟していても硬さの残るマンゴーと、少し押せる程度で崩れないアボカドを選びます。ライムを同重量のレモン果汁に替えると、風味と栄養値が変わります。蜂蜜を省くと酸味が増し、栄養値も同じではなくなります。レタスの水気を切り、薄まるのを防ぎます。使う分だけ果物を準備します。酸は変色を少し遅らせますが、アボカドをいつまでも保つわけではありません。生の鶏肉とそのまま食べる食品には別々の器具を使います。加熱はピンク色の有無ではなく温度で判断します。',
  'faq':[['前もって作れますか？','加熱済み鶏肉、野菜、ドレッシングを別々に冷蔵し、食べるときに混ぜます。アボカドは直前に切ります。混ぜたサラダは食感が落ちるため、冷蔵で24時間以内の消費を提案しています。'],['鶏肉の加熱をどう確認しますか？','各肉の最も厚い中心を食品用温度計で測り、74 °C以上を確認します。決まった時間や肉の色だけでは保証できません。'],['底に水が出るのはなぜですか？','ぬれたレタス、柔らかすぎるマンゴー、早く加えたドレッシングから水分が出ます。葉の水気を切り、硬さのある果物を使い、出す直前に混ぜます。']],
  'keywords':['鶏肉 アボカド マンゴー サラダ','フライパンの鶏肉サラダ','ライムドレッシング'],
  'cover_alt':'焼いた鶏肉の細切り、マンゴーとアボカド、レタス、きゅうり、紫玉ねぎのサラダ',
  'nutrition':{'serving_size':'4人分のうち1人分','method':'確認したUSDAの11項目の100 g当たりの数値を指定の可食部重量で加重計算し、4で割っています。鶏肉は生の皮なし骨なしむね肉600 gで計算し、紫玉ねぎは一般的な生玉ねぎの値で近似します。フライパンやボウルに残る場合も油30 gとドレッシングを全量計上します。','note':'参考用の推定値で、完成したサラダの実測値ではありません。加熱で失う肉汁、果物の品種、残る油、分け方で変わります。パンや追加の付け合わせは含みません。'}
 },
 'pt':{
  'path':'/pt/salada-de-frango-abacate-e-manga','historical_path':False,
  'title':'Salada de frango com abacate e manga','seo_title':'Salada de frango com abacate e manga',
  'excerpt':'Salada de frango com abacate e manga para 4, frango na frigideira e molho de limão. Veja como lavar, cozinhar, cortar e montar sem amassar as frutas.',
  'summary':'Esta salada combina frango na frigideira, cubos de abacate e manga, alface, pepino e cebola roxa. Limão, azeite e um pouco de mel unem os ingredientes sem um molho espesso.\n\nA proposta rende 4 porções. Os 55 minutos estimados incluem 30 de preparo, 20 de cozimento em duas etapas e 5 de descanso. Confira o frango com termômetro: pelo menos 74 °C. Quantidades, tempos e rendimento ainda precisam de confirmação em teste na cozinha.',
  'difficulty':'Fácil','course':'Salada como prato principal','cuisine':'Internacional',
  'ingredients':['Peito de frango cru sem pele e osso','Polpa de abacate','Polpa de manga','Pepino com casca','Alface romana','Cebola roxa','Suco de limão-taiti','Azeite de oliva','Mel','Sal','Pimenta-do-reino'],
  'groups':{'Ensalada':'Salada','Cocción y aliño':'Cozimento e molho'},
  'steps':[
   ['Lave e seque os vegetais','Lave as mãos e prepare uma tábua limpa para frutas e verduras, separada da do frango. Lave pepino, manga, abacate e limão em água corrente antes de cortar ou descascar, sem sabão. Lave e seque bem os 100 g de alface, salvo indicação de pronta para consumo na embalagem. Corte os 150 g de pepino em meias-luas finas e os 40 g de cebola em tiras; reserve com a alface na geladeira enquanto cozinha.'],
   ['Prepare quatro filés de frango','Não lave o frango cru. Na tábua separada, divida os 600 g de peito sem pele e osso em quatro filés de cerca de 150 g e espessura uniforme de aproximadamente 1,5 cm. Se necessário, achate delicadamente entre folhas próprias para alimentos. Tempere com 1 g de sal e 0,5 g de pimenta. Descarte o papel usado e lave mãos e utensílios; não coloque salada ou frango cozido na tábua ou prato do frango cru.'],
   ['Cozinhe e confira a temperatura','Aqueça uma frigideira grande em fogo médio com 5 g de azeite. Cozinhe dois filés por cerca de 4–5 minutos de cada lado, sem mexer até soltarem; ajuste o fogo se queimarem. Confira com termômetro de alimentos que o centro mais grosso de cada filé atinge pelo menos 74 °C, sem tocar a frigideira com a sonda. Se faltar temperatura, continue e meça de novo; cor e relógio não bastam. Passe para um prato limpo e repita com os outros dois e os 5 g restantes de azeite para cozinhar. Os 20 minutos previstos são orientativos.'],
   ['Deixe descansar e corte em tiras','Deixe o frango cozido descansar 5 minutos no prato limpo. Com faca e tábua limpas, corte cada filé em tiras de cerca de 1 cm. Deve parar de soltar vapor intenso antes de ir à salada; espere mais se necessário e acrescente ao tempo total. Reserve só enquanto termina a montagem, sem deixar por horas em temperatura ambiente.'],
   ['Corte manga e abacate','Descasque a manga lavada, separe a polpa do caroço e pese 250 g. Corte em cubos de cerca de 2 cm. Abra o abacate lavado, tire o caroço com colher em vez de golpeá-lo com a faca, retire a polpa e pese 200 g. Corte também em cubos de 2 cm. Use a tábua de frutas limpa sem contato com frango cru e prepare ambos pouco antes de misturar para reduzir o escurecimento.'],
   ['Misture o molho de limão','Em uma tigela pequena misture os 40 g de suco de limão-taiti, 10 g de mel, os 2 g de sal e 0,5 g de pimenta restantes. Junte os 20 g de azeite reservados para o molho e bata com um garfo até integrar temporariamente. Mexa de novo antes de usar se separar. O molho não substitui cozinhar o frango nem evita contaminação cruzada.'],
   ['Monte com cuidado','Coloque alface, pepino e cebola em uma tigela grande e misture com metade do molho. Adicione os cubos de manga e abacate e as tiras de frango morno. Incorpore o restante com duas colheres, levantando delicadamente do fundo para não amassar o abacate. Divida entre quatro pratos com quantidades parecidas de frango e fruta.'],
   ['Sirva e guarde na geladeira','Sirva recém-montada, sozinha ou com acompanhamento que não entra na nutrição. Se sobrar, tampe e leve à geladeira a no máximo 4 °C dentro de 2 horas, ou 1 hora se o ambiente superar 32 °C. Como proposta conservadora, consuma a salada montada em até 24 horas; alface e abacate perderão textura. Para adiantar, guarde frango já cozido, vegetais e molho separados no frio e monte ao servir. Não congele a salada completa porque a textura mudará bastante.']
  ],
  'notes':'Escolha manga madura, mas firme, e abacate que ceda um pouco sem estar desmanchado. Você pode trocar o limão-taiti pelo mesmo peso de suco de limão-siciliano; sabor e nutrição mudam. Sem mel, o molho fica mais ácido e os valores nutricionais deixam de ser iguais. Seque a alface para não diluir. Prepare só as frutas que vai usar; o ácido atrasa um pouco o escurecimento, mas não preserva o abacate indefinidamente. Separe utensílios para frango cru e alimentos prontos. A temperatura determina o cozimento, não a ausência de cor rosada.',
  'faq':[['Posso preparar com antecedência?','Guarde frango já cozido, vegetais e molho separados no frio e monte ao servir. Corte o abacate perto da montagem. A salada temperada perde textura; propõe-se consumir em até 24 horas na geladeira.'],['Como sei se o frango está cozido?','Meça o centro mais grosso de cada filé com um termômetro de alimentos: deve atingir pelo menos 74 °C. Tempo fixo e cor da carne sozinhos não garantem esse ponto.'],['Por que fica água no fundo?','Alface molhada, manga muito mole e molho colocado cedo podem soltar líquido. Seque as folhas, use frutas firmes e misture pouco antes de servir.']],
  'keywords':['salada frango abacate manga','salada de frango na frigideira','molho de limão para salada'],
  'cover_alt':'Salada com tiras de frango dourado, cubos de manga e abacate, alface, pepino e cebola roxa',
  'nutrition':{'serving_size':'1 das 4 porções','method':'Onze fichas USDA verificadas por 100 g são ponderadas pelos pesos comestíveis indicados e divididas por 4. Frango calculado sobre 600 g de peito cru sem pele e osso; cebola roxa aproximada pela ficha genérica de cebola crua. Os 30 g de azeite e todo o molho são contados, mesmo com sobras na frigideira ou tigela.','note':'Estimativa informativa, não análise da salada pronta. Perdas de sucos no cozimento, variedade das frutas, azeite retido e divisão mudam o resultado. Não se conta pão nem outro acompanhamento adicional.'}
 }
})
p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
