"""Authored EN/DE/FR seafood pasta localizations with unchanged proposed yield."""
import json
from pathlib import Path
p=Path(__file__).resolve().parents[1]/'editorial/pasta-frutos-del-mar-localizaciones-20261008.json';assert not p.exists()
data={
'en':{
'path':'/en/seafood-pasta','historical_path':False,'title':'Seafood pasta with tomato sauce','seo_title':'Seafood pasta with tomato sauce',
'excerpt':'Seafood pasta for 4 with shrimp, squid and mussels: tomato sauce, cooking in stages and clear steps for finishing the spaghetti.',
'summary':'This seafood pasta combines spaghetti, shrimp, squid and mussels in a quick sauce of tomato, garlic, onion and parsley. Steam the mussels separately to filter their liquid; cook the remaining seafood in the sauce and set it aside while finishing the pasta.\n\nThe proposal makes 4 plates and estimates 25 minutes of preparation plus 25 of cooking, 50 in total, with water, pasta and mussels cooking in parallel when possible. Quantities, times and yield await a kitchen test. Nutrition proposes 150 g edible mussel flesh from 600 g shell-on mussels; the actual yield needs weighing.',
'difficulty':'Medium','course':'Main course','cuisine':'Mediterranean, home-style proposal',
'ingredients':['Dry spaghetti','Raw peeled shrimp','Raw cleaned squid','Live shell-on mussels','Canned crushed tomatoes','Onion','Garlic','Olive oil','Fresh parsley','Salt','Unsalted pasta cooking water','Water for steaming mussels'],
'groups':{'Pasta y marisco':'Pasta and seafood','Salsa':'Sauce','Cocción':'Cooking'},
'steps':[
['Clean and check the seafood','Use 250 g raw shrimp already peeled and deveined, and 250 g cleaned squid: body without skin or innards, tentacles without the beak. Slice the body into roughly 0.5 cm rings and divide large tentacles. Check the 600 g live shell-on mussels from an approved supplier: discard broken shells and open ones that do not close when gently tapped. Scrub under cold water and remove beards just before cooking; do not leave them submerged in fresh water. Keep seafood separate and refrigerated at 4 °C or below while making the sauce. If shrimp or squid are frozen, thaw in the refrigerator first; this wait is excluded from the 50 minutes.'],
['Chop aromatics and heat water','Chop the 100 g onion and 12 g garlic on a clean board separate from raw seafood. Wash and chop the 8 g parsley. Put the 3 litres pasta water in a roomy pot and bring to the boil without salt: seasoning goes into the sauce. Prepare another lidded pot for mussels and a large skillet for sauce. Wash hands and utensils after handling raw seafood; use a clean bowl for cooked seafood.'],
['Make a quick tomato sauce','Heat the 30 g oil in the skillet over medium heat. Cook onion for 5 minutes until softened without burning. Add garlic and stir for 1 minute. Add the 400 g crushed tomatoes and simmer for 8 minutes, stirring, until some water evaporates and the raw taste diminishes. Keep the sauce hot over low heat. The 14 minutes are a guide; prevent drying out or sticking.'],
['Steam the mussels open','While making sauce, bring the 100 ml water to the boil in the mussel pot. Add cleaned mussels, cover and cook for about 4–5 minutes, carefully shaking the pot once. Lift opened mussels into a clean bowl; discard ones still closed at the end without forcing them open. Save up to 100 ml liquid and pass through a fine strainer lined with clean muslin to remove sand. Add it to the sauce. Leave some mussels in shells for serving and remove flesh from the rest with clean utensils. Keep together only while finishing the dish.'],
['Cook shrimp and squid','Bring the sauce to a gentle simmer and add the 250 g shrimp and 250 g squid. Cook for about 3–4 minutes, stirring, until shrimp are firm and opaque and squid loses translucency. Use a fine thermometer probe to check that the thickest seafood parts reach at least 63 °C; if not, continue and check again. Timing depends on size and starting temperature. Transfer cooked seafood to another clean bowl so it does not keep cooking while pasta finishes. Do not use the raw-seafood bowl.'],
['Cook pasta and save water','Time the start so this stage finishes near the seafood; pasta can cook in parallel. Add the 320 g spaghetti to unsalted boiling water, stir initially to separate strands and cook 2 minutes less than the package al dente time: it will finish in sauce. Before draining, save 150 ml cooking water in a cup. Drain without rinsing. If pasta or seafood needs longer, extend the total; do not rush insufficient cooking.'],
['Finish the pasta in the sauce','Add drained spaghetti to the sauce and toss over medium heat for about 2 minutes until al dente. Add reserved water in 30 ml increments only as needed for sauce to coat pasta without a pool. In the last 30 seconds fold in shrimp, squid, mussels and parsley gently to warm them without breaking them up. Taste with a clean utensil and add the planned 3 g salt, or less if mussel liquid is salty enough; less salt changes estimated sodium. Do not add closed shells or shell fragments.'],
['Serve immediately and chill leftovers','Divide between 4 plates, distributing pasta and all three seafood types evenly. Serve immediately; prolonged heat toughens shrimp and squid. Remove shells before storing leftovers, divide into small containers and refrigerate at 4 °C or below within 2 hours, or 1 hour if ambient temperature exceeds 32 °C. Using leftovers within 24 hours is proposed for quality; reheat only the portion to be eaten, stirring until at least 74 °C in several places. Freezing the assembled dish is not proposed because pasta and seafood textures deteriorate.']],
'notes':'The dish includes all three seafood types; substituting a commercial mix changes amounts, process and nutrition. Buy live mussels from an approved source and follow supplier storage instructions. Choose raw peeled shrimp and already cleaned squid so weights are edible amounts. Adding wine or cheese changes the calculation. Adjust sauce with small amounts of pasta water, not the whole cup automatically. Do not reuse raw-seafood boards or bowls without washing. Contains crustaceans, molluscs and wheat; check package labels for other ingredients or traces. Temperature and doneness signs take precedence over proposed timing.',
'faq':[['What should I do with mussels that do not open?','Discard any still closed after cooking; do not force them open to add them. Before cooking, also discard broken shells and open ones that do not close after gentle tapping.'],['Can I use frozen seafood?','For shrimp and squid, thaw in the refrigerator before starting and weigh peeled or cleaned. Thawing is excluded from the 50 minutes. This proposal uses live shell-on mussels, not a direct substitution with frozen mussels.'],['How do I prevent dry pasta?','Save 150 ml pasta water and add in 30 ml increments only as needed while finishing spaghetti in sauce. Return seafood at the end to avoid prolonged reheating.']],
'keywords':['seafood pasta','spaghetti with seafood','shrimp squid and mussel pasta'],'cover_alt':'Spaghetti with tomato sauce, peeled shrimp, squid rings, open mussels and parsley',
'nutrition':{'serving_size':'1 of 4 plates, without shells','method':'Ten verified USDA records, dry pasta and raw edible seafood weights, total divided by 4. Proposed mussel yield is 150 g flesh from 600 g shell-on mussels, equivalent to 25%, awaiting kitchen weighing. Shrimp and squid use mixed-species records and mussels a raw blue-mussel record. Oil, tomato and sauce salt counted fully. Pasta cooked in unsalted water; drained water and shells excluded.','note':'Informational estimate, not analysis of the finished dish. Actual mussel yield, discarded items, species, possible shrimp additives and brands alter values. Cheese, bread and wine excluded; mussel liquid may add salts not fully reflected by the proposed yield.'}
},
'de':{
'path':'/de/pasta-mit-meeresfruchten','historical_path':False,'title':'Pasta mit Meeresfrüchten und Tomatensauce','seo_title':'Pasta mit Meeresfrüchten und Tomatensauce',
'excerpt':'Pasta mit Meeresfrüchten für 4: Garnelen, Tintenfisch und Miesmuscheln, Tomatensauce und klare Schritte zum Fertiggaren der Spaghetti.',
'summary':'Diese Pasta verbindet Spaghetti, Garnelen, Tintenfisch und Miesmuscheln mit einer kurzen Sauce aus Tomaten, Knoblauch, Zwiebel und Petersilie. Muscheln werden getrennt geöffnet, damit ihr Sud gefiltert werden kann; die übrigen Meeresfrüchte garen in der Sauce und werden bis zum Fertiggaren der Pasta herausgenommen.\n\nDer Vorschlag ergibt 4 Teller und schätzt 25 Minuten Vorbereitung plus 25 Minuten Garen, insgesamt 50, mit Wasser, Pasta und Muscheln möglichst parallel. Mengen, Zeiten und Ausbeute sind noch nicht im Küchentest bestätigt. Die Nährwerte setzen vorgeschlagene 150 g essbares Muschelfleisch aus 600 g Muscheln mit Schale an; die tatsächliche Ausbeute muss gewogen werden.',
'difficulty':'Mittel','course':'Hauptgericht','cuisine':'Mediterran, Vorschlag für die Hausküche',
'ingredients':['Getrocknete Spaghetti','Rohe geschälte Garnelen','Roher geputzter Tintenfisch','Lebende Miesmuscheln mit Schale','Passierte stückfreie Dosentomaten','Zwiebel','Knoblauch','Olivenöl','Frische Petersilie','Salz','Ungesalzenes Pastakochwasser','Wasser zum Muscheldämpfen'],
'groups':{'Pasta y marisco':'Pasta und Meeresfrüchte','Salsa':'Sauce','Cocción':'Garen'},
'steps':[
['Meeresfrüchte putzen und prüfen','250 g rohe bereits geschälte und entdarmte Garnelen sowie 250 g geputzten Tintenfisch verwenden: Körper ohne Haut und Innereien, Fangarme ohne Schnabel. Körper in etwa 0,5 cm breite Ringe schneiden, große Fangarme teilen. 600 g lebende Miesmuscheln mit Schale von zugelassenem Anbieter prüfen: zerbrochene Schalen und offene Muscheln, die sich bei leichtem Klopfen nicht schließen, entsorgen. Unter kaltem Wasser bürsten und Bärte unmittelbar vor dem Garen entfernen; nicht in Süßwasser liegen lassen. Meeresfrüchte während der Saucenzubereitung getrennt bei höchstens 4 °C kühlen. Gefrorene Garnelen oder Tintenfisch vorher im Kühlschrank auftauen; diese Wartezeit gehört nicht zu den 50 Minuten.'],
['Aromaten hacken und Wasser erhitzen','100 g Zwiebel und 12 g Knoblauch auf einem sauberen Brett getrennt von rohen Meeresfrüchten hacken. 8 g Petersilie waschen und hacken. 3 Liter Pastawasser in einem großen Topf ohne Salz aufkochen: Gewürzt wird in der Sauce. Einen weiteren Topf mit Deckel für Muscheln und eine große Pfanne für Sauce bereitstellen. Nach Kontakt mit rohen Meeresfrüchten Hände und Geräte waschen; für gegarte eine saubere Schüssel nehmen.'],
['Kurze Tomatensauce zubereiten','30 g Öl in der Pfanne bei mittlerer Hitze erhitzen. Zwiebel 5 Minuten weich dünsten, ohne sie zu verbrennen. Knoblauch zufügen, 1 Minute rühren. 400 g zerkleinerte Dosentomaten zufügen und 8 Minuten sanft unter Rühren köcheln, bis etwas Wasser verdampft und der rohe Geschmack abnimmt. Bei kleiner Hitze warm halten. 14 Minuten sind ein Richtwert; Austrocknen und Ansetzen verhindern.'],
['Miesmuscheln dämpfen','Während die Sauce entsteht, 100 ml Wasser im Muscheltopf aufkochen. Geputzte Muscheln zufügen, zudecken und etwa 4–5 Minuten garen, Topf einmal vorsichtig schütteln. Geöffnete Muscheln in eine saubere Schüssel heben; am Ende geschlossene entsorgen, nicht gewaltsam öffnen. Bis zu 100 ml Sud aufheben und durch ein feines Sieb mit sauberem Mull filtern, um Sand zu entfernen. Zur Sauce geben. Einige Muscheln zum Servieren in der Schale lassen, die übrigen mit sauberen Geräten auslösen. Nur während der restlichen Zubereitung zusammen bereithalten.'],
['Garnelen und Tintenfisch garen','Sauce sanft aufkochen und 250 g Garnelen sowie 250 g Tintenfisch zufügen. Etwa 3–4 Minuten unter Bewegen garen, bis Garnelen fest und undurchsichtig sind und Tintenfisch seine Durchsichtigkeit verliert. Mit feiner Thermometersonde mindestens 63 °C an den dicksten Stellen prüfen; sonst weitergaren und erneut messen. Dauer hängt von Größe und Anfangstemperatur ab. Gegarte Meeresfrüchte in eine andere saubere Schüssel heben, damit sie während des Pastafertiggarens nicht weitergaren. Nicht die Rohwarenschüssel nutzen.'],
['Pasta kochen und Wasser aufheben','Den Beginn so planen, dass dieser Schritt ungefähr mit den Meeresfrüchten endet; Pasta kann parallel kochen. 320 g Spaghetti in ungesalzenes kochendes Wasser geben, anfangs zum Trennen rühren und 2 Minuten kürzer als die Al-dente-Zeit der Packung kochen: Sie garen in der Sauce fertig. Vor dem Abgießen 150 ml Kochwasser in einer Tasse sichern. Ohne Abspülen abgießen. Wenn Pasta oder Meeresfrüchte länger brauchen, Gesamtzeit verlängern; unzureichendes Garen nicht abkürzen.'],
['Pasta in der Sauce fertig garen','Abgetropfte Spaghetti zur Sauce geben und bei mittlerer Hitze etwa 2 Minuten bis al dente mischen. Aufgehobenes Wasser nur bei Bedarf in Schritten von 30 ml zufügen, damit Sauce die Pasta ohne Pfütze überzieht. In den letzten 30 Sekunden Garnelen, Tintenfisch, Muscheln und Petersilie vorsichtig zum Erwärmen unterheben. Mit sauberem Gerät probieren und die vorgesehenen 3 g Salz oder weniger bei bereits salzigem Muschelsud zufügen; weniger Salz ändert die Natriumschätzung. Keine geschlossenen Schalen oder Schalenstücke zufügen.'],
['Sofort servieren und Reste kühlen','Auf 4 Teller verteilen, Pasta und drei Meeresfruchtarten gleichmäßig aufteilen. Sofort servieren; längere Hitze macht Garnelen und Tintenfisch zäh. Vor dem Aufbewahren Schalen entfernen, Reste in kleine Behälter teilen und binnen 2 Stunden bei höchstens 4 °C kühlen, bei Umgebung über 32 °C binnen 1 Stunde. Aus Qualitätsgründen wird Verbrauch innerhalb 24 Stunden vorgeschlagen. Nur die benötigte Menge unter Rühren an mehreren Stellen auf mindestens 74 °C erhitzen. Das fertige Gericht wird nicht zum Einfrieren vorgeschlagen, da Pasta und Meeresfrüchte an Textur verlieren.']],
'notes':'Zum Gericht gehören alle drei Meeresfruchtarten; eine Handelsmischung verändert Mengen, Ablauf und Nährwerte. Lebende Muscheln aus zugelassener Quelle kaufen und Lagerhinweise des Anbieters befolgen. Rohe geschälte Garnelen und geputzten Tintenfisch wählen, damit Gewichte essbare Mengen sind. Wein oder Käse verändern die Berechnung. Sauce mit kleinen Wassermengen einstellen, nicht automatisch mit der ganzen Tasse. Rohwarenbretter und Schüsseln erst nach dem Waschen wiederverwenden. Enthält Krebstiere, Weichtiere und Weizen; Etiketten auf weitere Zutaten oder Spuren prüfen. Temperatur und Garzeichen haben Vorrang vor Zeitvorschlägen.',
'faq':[['Was mache ich mit ungeöffneten Muscheln?','Nach dem Garen weiterhin geschlossene Muscheln entsorgen, nicht gewaltsam öffnen. Vorher auch zerbrochene und offene Muscheln, die sich bei leichtem Klopfen nicht schließen, aussortieren.'],['Kann ich tiefgekühlte Meeresfrüchte verwenden?','Garnelen und Tintenfisch vor Beginn im Kühlschrank auftauen und geschält beziehungsweise geputzt wiegen. Auftauen gehört nicht zu den 50 Minuten. Vorgesehen sind lebende Muscheln mit Schale, kein direkter Ersatz durch gefrorene Muscheln.'],['Wie bleibt die Pasta saftig?','150 ml Kochwasser aufheben und beim Fertiggaren nur nötige Mengen in Schritten von 30 ml zugeben. Meeresfrüchte am Schluss zurückgeben, um langes Wiedererhitzen zu vermeiden.']],
'keywords':['Pasta mit Meeresfrüchten','Spaghetti mit Meeresfrüchten','Pasta Garnelen Tintenfisch Miesmuscheln'],'cover_alt':'Spaghetti mit Tomatensauce, geschälten Garnelen, Tintenfischringen, geöffneten Miesmuscheln und Petersilie',
'nutrition':{'serving_size':'1 von 4 Tellern, ohne Schalen','method':'Zehn geprüfte USDA-Datensätze, trockene Pasta und rohe essbare Meeresfruchtgewichte, Summe durch 4. Vorgeschlagene Muschelausbeute: 150 g Fleisch aus 600 g mit Schale, also 25 %, noch in der Küche zu wiegen. Garnelen und Tintenfisch verwenden Datensätze gemischter Arten, Muscheln rohe Blaumuscheln. Öl, Tomaten und Saucensalz vollständig gerechnet. Pasta in ungesalzenem Wasser; abgegossenes Wasser und Schalen ausgeschlossen.','note':'Informationsschätzung, keine Analyse des fertigen Gerichts. Tatsächliche Muschelausbeute, aussortierte Stücke, Art, mögliche Garnelenzusätze und Marken beeinflussen die Zahlen. Käse, Brot und Wein ausgeschlossen; Muschelsud kann zusätzliche, vom angenommenen Ertrag nicht ganz erfasste Salze liefern.'}
},
'fr':{
'path':'/fr/pates-aux-fruits-de-mer','historical_path':False,'title':'Pâtes aux fruits de mer et à la tomate','seo_title':'Pâtes aux fruits de mer et à la tomate',
'excerpt':'Pâtes aux fruits de mer pour 4 avec crevettes, calamar et moules : sauce tomate, cuisson par étapes et finition des spaghetti expliquées.',
'summary':'Ces pâtes associent spaghetti, crevettes, calamar et moules dans une sauce courte à la tomate, ail, oignon et persil. Les moules s’ouvrent à part pour filtrer leur jus ; les autres fruits de mer cuisent dans la sauce, puis sont réservés pendant la finition des pâtes.\n\nLa proposition donne 4 assiettes : 25 minutes de préparation et 25 de cuisson estimées, 50 au total, avec eau, pâtes et moules en parallèle si possible. Quantités, durées et rendement attendent un essai en cuisine. Le calcul propose 150 g de chair comestible pour 600 g de moules avec coquille ; le rendement réel doit être pesé.',
'difficulty':'Moyenne','course':'Plat principal','cuisine':'Méditerranéenne, proposition maison',
'ingredients':['Spaghetti secs','Crevettes crues décortiquées','Calamar cru nettoyé','Moules vivantes avec coquille','Tomates concassées en conserve','Oignon','Ail','Huile d’olive','Persil frais','Sel','Eau de cuisson des pâtes sans sel','Eau pour ouvrir les moules'],
'groups':{'Pasta y marisco':'Pâtes et fruits de mer','Salsa':'Sauce','Cocción':'Cuisson'},
'steps':[
['Nettoyer et vérifier les fruits de mer','Utilisez 250 g de crevettes crues déjà décortiquées et déveinées et 250 g de calamar nettoyé : corps sans peau ni viscères, tentacules sans bec. Coupez le corps en anneaux d’environ 0,5 cm et partagez les gros tentacules. Vérifiez les 600 g de moules vivantes avec coquille venant d’un fournisseur autorisé : jetez les coquilles cassées et les moules ouvertes qui ne se ferment pas après un léger coup. Brossez sous l’eau froide, retirez les filaments juste avant cuisson ; ne laissez pas immergées en eau douce. Gardez les fruits de mer séparés au réfrigérateur à 4 °C ou moins pendant la sauce. Crevettes ou calamar congelés se décongèlent avant au réfrigérateur ; cette attente n’entre pas dans les 50 minutes.'],
['Hacher les aromates et chauffer l’eau','Hachez les 100 g d’oignon et les 12 g d’ail sur une planche propre distincte de celle des fruits de mer crus. Lavez et hachez les 8 g de persil. Portez les 3 litres d’eau pour pâtes à ébullition dans une grande casserole, sans sel : l’assaisonnement va dans la sauce. Préparez une autre casserole à couvercle pour moules et une grande poêle pour sauce. Lavez mains et ustensiles après les fruits de mer crus ; prenez un bol propre pour les cuits.'],
['Préparer une sauce tomate courte','Chauffez les 30 g d’huile dans la poêle à feu moyen. Faites revenir l’oignon 5 minutes pour l’attendrir sans brûler. Ajoutez l’ail, remuez 1 minute. Ajoutez les 400 g de tomates concassées et mijotez 8 minutes en remuant, jusqu’à perte d’une partie de l’eau et du goût trop cru. Gardez chaud à feu doux. Les 14 minutes sont indicatives ; évitez dessèchement et attachement.'],
['Ouvrir les moules à la vapeur','Pendant la sauce, portez les 100 ml d’eau à ébullition dans la casserole à moules. Ajoutez les moules propres, couvrez et cuisez environ 4–5 minutes, en secouant prudemment une fois. Sortez les moules ouvertes dans un bol propre ; jetez celles encore fermées à la fin sans les forcer. Gardez jusqu’à 100 ml de jus, filtrez à travers une passoire fine garnie de gaze propre pour enlever le sable, puis ajoutez à la sauce. Gardez quelques moules dans leur coquille pour servir et retirez la chair des autres avec des ustensiles propres. Réservez seulement le temps de finir le plat.'],
['Cuire crevettes et calamar','Faites frémir la sauce et ajoutez les 250 g de crevettes et les 250 g de calamar. Cuisez environ 3–4 minutes en remuant jusqu’à crevettes fermes et opaques et calamar non translucide. Avec une sonde fine, vérifiez au moins 63 °C dans les parties les plus épaisses ; sinon poursuivez et mesurez encore. Le temps dépend de la taille et de la température initiale. Sortez les fruits de mer cuits dans un autre bol propre pour arrêter leur cuisson pendant la finition des pâtes. N’utilisez pas le bol des produits crus.'],
['Cuire les pâtes et garder de l’eau','Calculez le départ pour finir cette étape près de celle des fruits de mer ; la cuisson peut se faire en parallèle. Versez les 320 g de spaghetti dans l’eau bouillante sans sel, remuez au début pour séparer et cuisez 2 minutes de moins que le temps al dente du paquet : la sauce terminera la cuisson. Avant d’égoutter, gardez 150 ml d’eau dans une tasse. Égouttez sans rincer. Si pâtes ou fruits de mer demandent plus de temps, prolongez le total ; ne précipitez pas une cuisson insuffisante.'],
['Terminer les pâtes dans la sauce','Ajoutez les spaghetti égouttés à la sauce et mélangez environ 2 minutes à feu moyen jusqu’à al dente. Ajoutez l’eau réservée par 30 ml seulement si besoin pour enrober sans flaque. Durant les 30 dernières secondes, incorporez délicatement crevettes, calamar, moules et persil pour réchauffer sans défaire. Goûtez avec un ustensile propre et ajoutez les 3 g de sel prévus, ou moins si le jus de moule est assez salé ; moins de sel modifie le sodium estimé. N’ajoutez ni coquilles fermées ni fragments de coquille.'],
['Servir aussitôt et refroidir les restes','Répartissez entre 4 assiettes avec les pâtes et les trois fruits de mer en parts similaires. Servez aussitôt ; une chaleur prolongée durcit crevettes et calamar. Retirez les coquilles avant de conserver, partagez en petits récipients et réfrigérez à 4 °C ou moins dans les 2 heures, ou 1 heure si l’air dépasse 32 °C. Consommer les restes en 24 heures est proposé pour la qualité ; réchauffez seulement la portion à manger, en remuant jusqu’à au moins 74 °C en plusieurs points. Congeler le plat assemblé n’est pas proposé car pâtes et fruits de mer perdent leur texture.']],
'notes':'L’identité du plat comprend les trois fruits de mer ; un mélange commercial change quantités, procédé et nutrition. Achetez des moules vivantes d’origine autorisée et suivez les conseils de conservation du fournisseur. Prenez crevettes crues décortiquées et calamar déjà nettoyé pour des poids comestibles. Ajouter vin ou fromage change le calcul. Ajustez avec de petites quantités d’eau de pâtes, pas automatiquement toute la tasse. Ne réutilisez pas planches et bols des produits crus sans lavage. Contient crustacés, mollusques et blé ; vérifiez aussi les étiquettes pour d’autres ingrédients ou traces. Température et signes de cuisson priment sur les durées proposées.',
'faq':[['Que faire des moules qui ne s’ouvrent pas ?','Jetez celles encore fermées après cuisson sans les forcer pour les ajouter. Avant cuisson, jetez aussi coquilles cassées et moules ouvertes qui ne se referment pas après un léger coup.'],['Puis-je utiliser des fruits de mer congelés ?','Décongelez crevettes et calamar au réfrigérateur avant de commencer et pesez-les décortiqués ou nettoyés. L’attente n’entre pas dans les 50 minutes. Cette proposition utilise des moules vivantes avec coquille, sans remplacement direct par des moules congelées.'],['Comment éviter des pâtes sèches ?','Gardez 150 ml d’eau de cuisson et ajoutez par 30 ml seulement si nécessaire pour terminer les spaghetti dans la sauce. Remettez les fruits de mer à la fin pour éviter un long réchauffage.']],
'keywords':['pâtes aux fruits de mer','spaghetti aux fruits de mer','pâtes crevettes calamar moules'],'cover_alt':'Spaghetti à la sauce tomate, crevettes décortiquées, anneaux de calamar, moules ouvertes et persil',
'nutrition':{'serving_size':'1 des 4 assiettes, sans coquilles','method':'Dix fiches USDA vérifiées, poids secs des pâtes et crus comestibles des fruits de mer, somme divisée par 4. Rendement proposé de 150 g de chair pour 600 g de moules avec coquille, soit 25 %, à peser en cuisine. Crevettes et calamar approximés avec fiches d’espèces mélangées, moules avec moule bleue crue. Huile, tomate et sel de sauce comptés intégralement. Pâtes dans l’eau sans sel ; eau égouttée et coquilles exclues.','note':'Estimation informative, pas analyse du plat terminé. Rendement réel des moules, rejets, espèce, éventuels additifs des crevettes et marques modifient les valeurs. Fromage, pain et vin exclus ; le jus de moules peut apporter des sels non entièrement reflétés par le rendement proposé.'}
}}
p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n');print('EN, DE and FR seafood pasta localizations authored.')
