import json
from pathlib import Path
p=Path(__file__).resolve().parents[1]/'editorial/barras-de-cereal-localizaciones-20261008.json'
data=json.loads(p.read_text());assert set(data)=={'en','de','fr'}
data.update({
 'it':{
  'path':'/it/barrette-di-cereali','historical_path':True,
  'title':'Barrette di cereali con avena, miele e arachidi','seo_title':'Barrette di cereali con avena, miele e arachidi',
  'excerpt':'Prepara 12 barrette di avena con miele, crema di arachidi e uvetta. Tostatura in padella, pressione uniforme e riposo al freddo prima del taglio.',
  'summary':'Queste barrette combinano fiocchi d’avena tostati, mandorle, semi di girasole e uvetta, legati con miele e crema di arachidi. Si compattano in uno stampo e si tagliano dopo il raffreddamento; il blocco non passa in forno.\n\nLa proposta rende 12 barrette morbide e compatte, non croccanti. I 165 minuti stimati comprendono 10 di cottura, 15 di raffreddamento e almeno 120 in frigorifero. Dosi, compattezza, resa e tempi sono ancora da confermare con una prova in cucina.',
  'difficulty':'Facile','course':'Spuntino dolce','cuisine':'Internazionale',
  'ingredients':['Fiocchi d’avena secchi','Crema di arachidi liscia non salata','Miele','Mandorle','Uvetta scura senza semi','Semi di girasole sgusciati','Estratto di vaniglia','Sale'],
  'groups':{'Mezcla seca':'Miscela secca','Para ligar':'Per legare'},
  'steps':[
   ['Prepara lo stampo e pesa','Lava le mani e pulisci il piano. Rivesti uno stampo quadrato di 20 × 20 cm con carta forno, lasciando lembi per sollevare il composto. Pesa gli ingredienti e trita 50 g di mandorle in pezzi di circa 5 mm; taglia l’uvetta grande per non rompere le barrette. Mescola la crema di arachidi nel vasetto per riunire l’olio separato. Usa fiocchi adatti a questo impiego secondo la confezione, non chicchi d’avena interi.'],
   ['Tosta avena e semi','Scalda una padella larga e asciutta a fuoco medio-basso. Aggiungi 200 g di fiocchi, 50 g di mandorle e 30 g di semi. Mescola quasi continuamente per circa 8 minuti, finché sono profumati e leggermente coloriti senza bruciare. Abbassa il fuoco se dorano troppo in fretta. Trasferisci in una ciotola grande e lascia intiepidire mentre prepari il legante.'],
   ['Scalda miele e crema di arachidi','Metti 100 g di miele e 100 g di crema di arachidi in un pentolino. Scalda a fuoco basso per circa 2 minuti, mescolando fino a un composto fluido e uniforme, senza bollire o caramellare. Togli dal fuoco e aggiungi 3 g di vaniglia e 1 g di sale. Il composto caldo può ustionare: usa una spatola, non le dita.'],
   ['Unisci uvetta e legante','Aggiungi 50 g di uvetta alla ciotola di avena tiepida. Versa tutto il composto miele-arachidi e mescola con una spatola per 1–2 minuti, raccogliendo fondo e pareti finché ogni fiocco è rivestito e non restano zone asciutte. Deve essere appiccicoso e aggregarsi premendo con la spatola, non liquido o montato.'],
   ['Compatta in uno strato uniforme','Versa nello stampo rivestito e distribuisci fino agli angoli. Copri con un altro foglio e premi con il fondo piatto di un bicchiere o una spatola per 2–3 minuti. Cerca uno strato di circa 1–1,5 cm senza vuoti, soprattutto ai bordi. La pressione aiuta a evitare che le barrette si sbriciolino; non aggiungere liquido per ammorbidirle.'],
   ['Raffredda prima di tagliare','Lascia lo stampo circa 15 minuti a temperatura ambiente per perdere il calore intenso. Copri e metti in frigorifero a non più di 4 °C per almeno 120 minuti, finché tutto il blocco è freddo e sodo. Frigorifero e spessore possono allungare il tempo; non tagliare tiepido. I 165 minuti previsti includono raffreddamento e refrigerazione.'],
   ['Taglia dodici barrette','Solleva il blocco freddo dai lembi e appoggia su un tagliere pulito. Togli la carta superiore e taglia con un coltello grande in 3 file e 4 colonne, ottenendo 12 barrette di circa 6,7 × 5 cm. Premi il coltello verso il basso senza segare e pulisci la lama tra i tagli se si attacca. Se si ammorbidisce, rimetti in frigorifero prima di continuare. Le briciole si possono servire a parte con yogurt, non incluso nella nutrizione.'],
   ['Servi e conserva al freddo','Servi fredde o lascia intiepidire solo la porzione da mangiare. Avvolgi singolarmente o conserva in un contenitore chiuso con carta tra gli strati, a non più di 4 °C fino a 5 giorni; rispetta eventuali indicazioni più brevi degli ingredienti. Per congelare, avvolgi singolarmente fino a 1 mese e scongela in frigorifero. Sono durate proposte, non prove di conservabilità. Con il caldo si ammorbidiscono e non sono progettate per restare sode per ore fuori dal frigorifero.']
  ],
  'notes':'Usa crema di arachidi liscia senza sale e zucchero aggiunto; una molto liquida o diversa cambia la compattezza. Puoi sostituire l’uvetta con lo stesso peso di albicocche secche tritate, ma consistenza e nutrizione cambiano. Sostituire miele o crema richiede una nuova verifica di legame e allergeni; non si promette lo stesso risultato. Contiene arachidi e mandorle; l’avena può avere contaminazione da glutine, controlla le confezioni se rilevante. Trasporta al freddo e non presentare come senza zucchero: ci sono miele e frutta secca.',
  'faq':[['Perché si sbriciolano al taglio?','Servono pressione e freddo. Compatta anche gli angoli e raffredda almeno 120 minuti, di più se ancora morbide. Una crema molto liquida e il taglio tiepido cambiano il risultato.'],['Si cuociono in forno?','Il blocco non viene cotto in forno. Avena, mandorle e semi si tostano in padella e il legante si scalda; poi si compatta e si refrigera.'],['Posso trasportarle senza refrigerazione?','Questa proposta si conserva al freddo e si ammorbidisce con il caldo. Usa un contenitore con ghiaccio refrigerante e tira fuori solo la porzione da mangiare; la stabilità prolungata a temperatura ambiente non è verificata.']],
  'keywords':['barrette di cereali','barrette avena miele','barrette arachidi uvetta'],
  'cover_alt':'Barrette rettangolari di avena con mandorle, semi e uvetta visibili, senza cioccolato né copertura',
  'nutrition':{'serving_size':'1 delle 12 barrette, circa 44 g prima delle perdite d’acqua','method':'Otto schede USDA verificate per 100 g sono ponderate con i pesi degli ingredienti e divise per 12. La scheda d’avena riguarda fiocchi regolari o rapidi secchi non fortificati, non avena cotta. Si suppone crema di arachidi senza sale né aggiunte; la tostatura non sottrae nutrienti dal lotto.','note':'Stima informativa, non analisi delle barrette pronte. Marca della crema, dimensione del taglio e residui cambiano il risultato. Si include tutto il miele: le cifre non costituiscono una dichiarazione di basso contenuto di zucchero.'}
 },
 'ja':{
  'path':'/ja/oat-cereal-bars','historical_path':False,
  'title':'オーツ麦と蜂蜜、ピーナッツのシリアルバー','seo_title':'オーツ麦のシリアルバー｜蜂蜜とピーナッツ入り',
  'excerpt':'オーツ麦、蜂蜜、ピーナッツバター、レーズンで作る12本分のシリアルバー。フライパンで煎り、しっかり押し固めて冷やしてから切る手順を紹介します。',
  'summary':'煎ったオーツ麦フレーク、アーモンド、ひまわりの種、レーズンを、蜂蜜とピーナッツバターでまとめるシリアルバーです。型に押し固め、冷やしてから切ります。固めた生地はオーブンで焼きません。\n\nサクサクではなく、柔らかく密にまとまった12本を想定しています。推定165分には加熱10分、冷却15分、冷蔵120分以上を含みます。分量、固さ、出来上がり数、時間は調理試験でまだ確認していません。',
  'difficulty':'簡単','course':'甘い間食','cuisine':'各国料理',
  'ingredients':['乾燥オーツ麦フレーク','無塩の滑らかなピーナッツバター','蜂蜜','アーモンド','種なしの濃色レーズン','殻を除いたひまわりの種','バニラエクストラクト','塩'],
  'groups':{'Mezcla seca':'乾燥材料','Para ligar':'つなぎ'},
  'steps':[
   ['型を用意して材料を量る','手を洗い、作業台を清潔にします。20 × 20 cmの正方形の型にオーブンシートを敷き、持ち上げるための余りを残します。材料を量り、アーモンド50 gを約5 mmに刻みます。大きなレーズンも切り、バーが裂けにくくします。ピーナッツバターは容器内で混ぜ、分離した油をなじませます。包装に従ってこの使い方に適したフレークを使い、オーツ麦の粒そのものは使いません。'],
   ['オーツ麦と種を煎る','広い乾いたフライパンを弱めの中火で温め、フレーク200 g、アーモンド50 g、ひまわりの種30 gを入れます。焦がさず香りと軽い色がつくまで、約8分ほぼ絶えず混ぜます。色づきが速ければ火を弱めます。大きなボウルに移し、つなぎを作る間に少し冷まします。'],
   ['蜂蜜とピーナッツバターを温める','蜂蜜100 gとピーナッツバター100 gを小鍋に入れます。弱火で約2分、流動性が増して均一になるまで混ぜ、沸騰やカラメル化はさせません。火から下ろし、バニラ3 gと塩1 gを加えます。熱い混合物はやけどの原因になるので、指で触れずへらを使います。'],
   ['レーズンとつなぎを混ぜる','少し温かいオーツ麦のボウルにレーズン50 gを加えます。蜂蜜とピーナッツの混合物をすべて注ぎ、底と側面をこそげながらへらで1〜2分混ぜます。すべてのフレークが覆われ、乾いた部分が残らないようにします。へらで押すとまとまる粘りのある状態にし、液体状や泡立てた生地にはしません。'],
   ['均一に押し固める','シートを敷いた型に移し、隅まで広げます。別のシートを上に置き、平らなグラスの底かへらで2〜3分押します。約1〜1.5 cm厚で、特に端に隙間がない層を目指します。しっかり押すと崩れにくくなります。柔らかくするために液体を足さないでください。'],
   ['冷蔵してから切る','型を室温で約15分置き、強い熱を逃がします。ふたをし、4 °C以下で120分以上冷蔵し、全体が冷たく固くなるまで待ちます。冷蔵庫や厚さでさらに時間が必要な場合があり、温かいまま切りません。予定の合計165分にはこの冷却と冷蔵を含みます。'],
   ['12本に切る','冷えた生地をシートの余りで持ち上げ、清潔なまな板に置きます。上のシートを外し、大きな包丁で3行4列に切り、約6.7 × 5 cmの12本にします。のこぎりのように動かさず下に押し、付着する場合は切るたびに刃を拭きます。柔らかくなったら再び冷蔵してから続けます。くずは別にヨーグルトと食べられますが、ヨーグルトは栄養計算に含みません。'],
   ['盛り付けて冷蔵保存する','冷たいまま出すか、食べる分だけ少し室温に戻します。1本ずつ包むか、紙を挟んで密閉容器に入れ、4 °C以下で最長5日保存します。材料の表示がより短い期間を求める場合は従います。冷凍は個別に包んで最長1か月とし、冷蔵庫で解凍します。保存期間は提案で、保存試験の結果ではありません。熱で柔らかくなり、冷蔵庫の外で何時間も固さを保つようには設計していません。']
  ],
  'notes':'無塩、砂糖無添加の滑らかなピーナッツバターを使います。非常に緩い製品や配合の違いは固さを変えます。レーズンを同重量の刻んだ干しあんずに替えられますが、食感と栄養値は変わります。蜂蜜を別のシロップに、ピーナッツを別のペーストに替える場合は、結着性とアレルゲンを再確認する必要があり、同じ結果は保証しません。ピーナッツとアーモンドを含み、オーツ麦はグルテンと交差接触している場合があるので必要に応じて包装を確認します。持ち運びは冷やし、蜂蜜と乾燥果物を含むため砂糖不使用とは表示しません。',
  'faq':[['切ると崩れるのはなぜですか？','十分に押し固めて冷やす必要があります。隅も押し、120分以上、まだ柔らかければさらに冷蔵します。緩いピーナッツバターや温かい状態での切断も仕上がりを変えます。'],['オーブンで焼きますか？','固めた生地は焼きません。オーツ麦、アーモンド、種をフライパンで煎り、つなぎを温めた後、押し固めて冷蔵します。'],['冷やさずに持ち歩けますか？','この提案は冷蔵保存で、熱により柔らかくなります。保冷剤入りの容器で運び、食べる分だけ取り出します。室温での長時間の安定性は未確認です。']],
  'keywords':['シリアルバー','オーツ麦 蜂蜜 バー','ピーナッツ レーズン バー'],
  'cover_alt':'アーモンド、種、レーズンが見える長方形のオーツ麦バー、チョコレートやコーティングなし',
  'nutrition':{'serving_size':'12本のうち1本、水分損失前で約44 g','method':'確認したUSDAの8項目の100 g当たりの数値を材料重量で加重計算し、12で割っています。オーツ麦は調理済みではなく、栄養強化していない乾燥の通常またはクイックタイプのフレークです。ピーナッツバターは無塩で添加物なしと想定し、煎る工程で総栄養量を差し引きません。','note':'参考用の推定値で、完成品の実測値ではありません。ピーナッツバターの製品、切る大きさ、残る混合物で変わります。蜂蜜を全量含めており、低糖の表示を意味しません。'}
 },
 'pt':{
  'path':'/pt/barras-de-cereal','historical_path':False,
  'title':'Barras de cereal com aveia, mel e amendoim','seo_title':'Barras de cereal com aveia, mel e amendoim',
  'excerpt':'Prepare 12 barras de aveia com mel, pasta de amendoim e passas. Veja o tostado na frigideira, a compactação e o tempo na geladeira antes de cortar.',
  'summary':'Estas barras combinam aveia em flocos tostada, amêndoas, sementes de girassol e passas, ligadas com mel e pasta de amendoim. A mistura é compactada em uma forma e cortada depois de esfriar; a placa não vai ao forno.\n\nA proposta rende 12 barras macias e compactas, não crocantes. Os 165 minutos estimados incluem 10 de cozimento, 15 de resfriamento e pelo menos 120 na geladeira. Quantidades, firmeza, rendimento e tempos ainda precisam de confirmação em teste na cozinha.',
  'difficulty':'Fácil','course':'Lanche doce','cuisine':'Internacional',
  'ingredients':['Aveia em flocos seca','Pasta de amendoim lisa sem sal','Mel','Amêndoas','Uvas-passas escuras sem sementes','Sementes de girassol sem casca','Extrato de baunilha','Sal'],
  'groups':{'Mezcla seca':'Mistura seca','Para ligar':'Para dar liga'},
  'steps':[
   ['Prepare a forma e pese','Lave as mãos e limpe a bancada. Forre uma forma quadrada de 20 × 20 cm com papel próprio para forno, deixando abas para levantar a mistura. Pese os ingredientes e pique os 50 g de amêndoas em pedaços de cerca de 5 mm; corte passas grandes para não romper as barras. Mexa a pasta de amendoim no pote até incorporar o óleo separado. Use flocos adequados a esse preparo conforme a embalagem, não grãos inteiros de aveia.'],
   ['Toste a aveia e as sementes','Aqueça uma frigideira grande e seca em fogo médio-baixo. Adicione os 200 g de flocos, 50 g de amêndoas e 30 g de sementes. Mexa quase continuamente por cerca de 8 minutos, até soltarem aroma e ganharem um pouco de cor sem queimar. Abaixe o fogo se dourarem rápido demais. Passe para uma tigela grande e deixe amornar enquanto prepara o ligante.'],
   ['Aqueça o mel e a pasta de amendoim','Coloque os 100 g de mel e 100 g de pasta de amendoim em uma panela pequena. Aqueça em fogo baixo por cerca de 2 minutos, mexendo até ficar fluido e uniforme, sem ferver nem caramelizar. Retire do fogo e adicione os 3 g de baunilha e 1 g de sal. A mistura quente pode queimar; use espátula, sem tocar com os dedos.'],
   ['Misture as passas e o ligante','Adicione os 50 g de passas à tigela de aveia morna. Despeje toda a mistura de mel e amendoim e mexa com espátula por 1–2 minutos, raspando fundo e laterais até cobrir cada floco sem partes secas. Deve ser uma mistura pegajosa que se una ao pressionar com a espátula, não um líquido nem uma massa aerada.'],
   ['Compacte em uma camada uniforme','Passe para a forma forrada e espalhe até os cantos. Cubra com outra folha e pressione com o fundo plano de um copo ou uma espátula por 2–3 minutos. Busque uma camada de cerca de 1–1,5 cm sem espaços, principalmente nas bordas. A pressão ajuda a não esfarelar; não acrescente líquido para amolecer.'],
   ['Esfrie e leve à geladeira antes de cortar','Deixe a forma cerca de 15 minutos em temperatura ambiente para perder o calor intenso. Tampe e leve à geladeira a no máximo 4 °C por pelo menos 120 minutos, até toda a placa ficar fria e firme. Geladeira e espessura podem aumentar o tempo; não corte morna. Os 165 minutos previstos incluem esse resfriamento e a refrigeração.'],
   ['Corte doze barras','Levante a placa fria pelas abas e coloque em uma tábua limpa. Retire o papel superior e corte com uma faca grande em 3 fileiras e 4 colunas, formando 12 barras de cerca de 6,7 × 5 cm. Pressione a faca para baixo em vez de serrar; limpe a lâmina entre cortes se grudar. Se amolecer, volte à geladeira antes de continuar. As migalhas podem ser servidas à parte com iogurte, que não entra na nutrição calculada.'],
   ['Sirva e conserve na geladeira','Sirva frias ou deixe amornar apenas a porção que vai comer. Embrulhe cada uma ou guarde em recipiente fechado com papel entre camadas, a no máximo 4 °C por até 5 dias; siga qualquer prazo menor indicado nos ingredientes. Para congelar, embrulhe individualmente por até 1 mês e descongele na geladeira. São durações propostas, não testes de validade. Amolecem com calor e não foram feitas para ficar firmes por horas fora da geladeira.']
  ],
  'notes':'Use pasta de amendoim lisa sem sal nem açúcar adicionado; uma muito líquida ou com outra formulação muda a firmeza. Você pode trocar passas pelo mesmo peso de damasco seco picado, mas textura e nutrição mudam. Trocar o mel por outro xarope ou o amendoim por outra pasta exige conferir novamente a liga e os alérgenos; não se promete o mesmo resultado. Contém amendoim e amêndoas; a aveia pode ter contato com glúten, confira as embalagens se relevante. Mantenha as barras frias no transporte e não apresente como sem açúcar: levam mel e frutas secas.',
  'faq':[['Por que se desfazem ao cortar?','A mistura precisa de pressão e frio. Compacte também os cantos e leve à geladeira por pelo menos 120 minutos, mais se ainda estiver macia. Pasta muito líquida e corte com a placa morna mudam o resultado.'],['As barras vão ao forno?','A placa não é assada. Aveia, amêndoas e sementes são tostadas na frigideira e o ligante aquecido; depois a mistura é compactada e refrigerada.'],['Posso levar sem refrigeração?','Esta proposta é conservada no frio e amolece com calor. Transporte em recipiente com acumulador de frio e retire só a porção que vai comer; a estabilidade prolongada em temperatura ambiente não foi verificada.']],
  'keywords':['barras de cereal','barras de aveia e mel','barras de amendoim e passas'],
  'cover_alt':'Barras retangulares de aveia com amêndoas, sementes e passas visíveis, sem chocolate nem cobertura',
  'nutrition':{'serving_size':'1 das 12 barras, cerca de 44 g antes da perda de água','method':'Oito fichas USDA verificadas por 100 g são ponderadas pelos pesos dos ingredientes e divididas por 12. A ficha de aveia é de flocos regulares ou rápidos secos sem fortificação, não de aveia cozida. Considera-se pasta de amendoim sem sal nem adições; o tostado não desconta nutrientes do lote.','note':'Estimativa informativa, não análise das barras prontas. Marca da pasta, tamanho do corte e sobras mudam o resultado. Todo o mel é incluído; as cifras não constituem uma alegação de baixo teor de açúcar.'}
 }
})
p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
