"""Authored EN/DE/FR localizations of frozen home-style feijoada."""
import json
from pathlib import Path
p=Path(__file__).resolve().parents[1]/'editorial/receta-de-feijoada-localizaciones-20261008.json'
assert not p.exists()
data={
'en':{
'path':'/en/feijoada-recipe','historical_path':True,'title':'Home-style black bean and pork feijoada','seo_title':'Home-style black bean and pork feijoada',
'excerpt':'Home-style feijoada for 8 with black beans, pork, bacon and smoked sausage: soaking, an initial boil, slow simmering and storage step by step.',
'summary':'This home-style feijoada combines black beans, fresh pork shoulder, bacon and fully cooked smoked sausage in a dark broth thickened with some of the beans themselves. It is an adaptation with clearly identified ingredients and no salted meats requiring desalting; it does not represent every Brazilian version.\n\nThe proposal makes 8 portions of stew. The estimated 680 minutes include 8 hours of refrigerated soaking, 30 minutes of preparation, 160 of cooking and 10 of resting. Brown the aromatics while the beans boil. Quantities, yield and timing await confirmation in a kitchen test; tenderness and temperature matter more than the clock.',
'difficulty':'Medium','course':'Main course','cuisine':'Brazilian, home-style adaptation',
'ingredients':['Dry black beans','Fresh boneless pork shoulder','Fully cooked smoked pork sausage','Raw bacon','Onion','Garlic','Olive oil','Salt','Black pepper','Cooking water','Dried bay leaves, to remove'],
'groups':{'Alubias y cocción':'Beans and cooking','Carnes':'Meats','Sofrito y sazón':'Aromatics and seasoning'},'units':{'hojas':'leaves'},
'steps':[
['Soak the beans in the refrigerator','Sort the 500 g dry black beans, removing stones or damaged beans, and rinse. Put them in a roomy container with about 1.5 litres water, covered by several centimetres. Cover and soak for 8 hours in the refrigerator at 4 °C or below; add more water if absorbed. Discard all soaking water and rinse afterwards. This water is additional to the 2.5 litres used for cooking.'],
['Prepare ingredients and separate raw meat','Chop the 200 g onion and 20 g garlic on a clean produce board. Cut the 400 g fresh boneless pork shoulder into roughly 3 cm cubes and the 100 g bacon into short strips on a separate raw-meat board. Slice the 250 g sausage into 1 cm rounds; use a product whose package says fully cooked, not fresh sausage or cured meat needing desalting. Keep meats refrigerated until cooking and wash hands and utensils after handling raw pork.'],
['Boil the beans before lowering the heat','Put the drained beans in a pot of at least 6 litres with the 2.5 litres fresh water and 2 bay leaves. Bring to the boil, about 15 minutes as a guide, then maintain a clear rolling boil for at least 30 minutes without a lid to control foam and overflow. Skim foam with a spoon; add boiling water if beans become exposed. Do not taste raw or hard beans or replace this stage with a slow cooker.'],
['Brown the meat and aromatics','During the boil, heat a wide skillet over medium heat with the 15 g oil. Cook the bacon for about 5 minutes, stirring, until it begins to brown. Add the pork in two batches for about 4 minutes each, only browning the surface; it must finish cooking in the stew. Remove meats to a plate reserved for them. Cook the onion in the same pan for 7 minutes, garlic for 1 minute and sausage for 4 minutes. Keep everything, including the rendered fat: the nutrition estimate counts it all.'],
['Simmer the stew until tender','After the 30-minute boil, add meat, sausage, aromatics and pan juices to the pot, scraping the pan with a little hot broth. Add 1 g pepper; leave salt until the end. Return to a gentle simmer and cook for about 100 minutes with the lid partly open, stirring from the bottom every 15–20 minutes. Keep beans and meats barely covered, adding boiling water in 100 ml increments if needed. Prevent sticking and avoid a hard boil that breaks all the beans.'],
['Check temperature and tenderness','With a clean food thermometer, check the centres of several pork cubes: this stew uses a practical target of at least 74 °C, above the minimum for whole cuts. The meat must also yield easily under a fork, and a bean lifted with a spoon must be creamy inside without a hard core. If anything remains firm or below temperature, cook longer and check again; times are a proposal, not a guarantee. Do not taste with utensils that touched raw meat.'],
['Thicken, season and rest','Lift out a ladleful of tender beans without meat, mash them in a bowl and return the paste to the pot. Simmer for about 15 more minutes, stirring, until broth lightly coats the back of a spoon; add boiling water if too thick. Remove the 2 bay leaves. Taste only now and add the planned 4 g salt, or less if the sausage and bacon are already salty; less salt changes estimated sodium. Turn off the heat and rest for 10 minutes with the lid on.'],
['Portion and cool promptly','Divide the stew into 8 portions with similar amounts of beans, meats and broth. Rice, orange or farofa can accompany it but are not included in ingredients or nutrition. For storage, promptly divide leftovers into small shallow containers and refrigerate at 4 °C or below within 2 hours, or 1 hour if ambient temperature exceeds 32 °C; do not leave the whole large pot outside to cool. Use within 3–4 days or freeze portions; 2 months is a proposed quality limit. Thaw in the refrigerator and reheat while stirring to at least 74 °C in several places.']],
'notes':'Use dry black beans; do not substitute cooked beans while retaining these times and quantities. This version contains no dried beef, pig ear or trotter; adding them requires a different process and nutrition calculation. The sausage must be fully cooked according to its package: smoked does not always mean cooked. Cooked linguiça or comparable smoked pork sausage is suitable; the brand changes flavour and sodium. Fresh shoulder needs no desalting. For a thinner broth add boiling water; thicken with mashed cooked beans rather than flour. Do not add acidic ingredients before beans are tender. Resting off the heat does not replace prompt refrigeration of leftovers.',
'faq':[['Can I skip soaking?','This proposal starts with 8 hours of refrigerated soaking and fresh cooking water. No equivalent unsoaked timing is provided; that changes the process and does not remove the initial 30-minute boil.'],['Why are the beans still hard?','Old beans, hard water or acidic ingredients added early can prolong cooking. Keep enough hot water in the pot and cook until there is no hard core; add the planned salt at the end.'],['How can I thicken the broth without flour?','Mash a ladleful of tender beans without meat and return it to the stew. Simmer for another 15 minutes, stirring; add boiling water if excessively thick.']],
'keywords':['home-style feijoada','black bean feijoada','pork and black bean stew'],
'cover_alt':'Black bean feijoada with pork cubes, bacon and smoked sausage slices in dark broth',
'nutrition':{'serving_size':'1 of 8 portions of stew, without sides','method':'Ten verified USDA records, raw edible weights for beans, pork and bacon, and weight of the already cooked sausage; total divided by 8. Smoked sausage is approximated using a generic smoked pork sausage record, not a specific Brazilian linguiça record. All fat and retained broth are counted. Removed bay leaves and discarded soaking water are excluded.','note':'Informational estimate, not analysis of finished stew. Sausage and bacon brands and salt levels, soaking, yield and broth distribution change the values. Rice, orange, farofa and vegetable sides are excluded.'}
},
'de':{
'path':'/de/feijoada-rezept','historical_path':True,'title':'Feijoada mit schwarzen Bohnen und Schweinefleisch','seo_title':'Feijoada mit schwarzen Bohnen und Schweinefleisch',
'excerpt':'Hausgemachte Feijoada für 8 mit schwarzen Bohnen, Schweinefleisch, Speck und Räucherwurst: Einweichen, Aufkochen, Schmoren und Aufbewahren.',
'summary':'Diese Feijoada für die Hausküche verbindet schwarze Bohnen, frische Schweineschulter, Speck und vollständig gegarte Räucherwurst in einer dunklen Brühe, die mit einem Teil der Bohnen angedickt wird. Es ist eine Anpassung mit klar benannten Zutaten, ohne Salzfleisch, das entsalzt werden muss; sie steht nicht für alle brasilianischen Varianten.\n\nDer Vorschlag ergibt 8 Eintopfportionen. Die geschätzten 680 Minuten enthalten 8 Stunden gekühltes Einweichen, 30 Minuten Vorbereitung, 160 Minuten Garen und 10 Minuten Ruhe. Die Pfannenzutaten werden während des Bohnenkochens angebraten. Mengen, Ausbeute und Zeiten sind noch nicht im Küchentest bestätigt; entscheidend sind Zartheit und Temperatur.',
'difficulty':'Mittel','course':'Hauptgericht','cuisine':'Brasilianisch, für die Hausküche angepasst',
'ingredients':['Getrocknete schwarze Bohnen','Frische Schweineschulter ohne Knochen','Vollständig gegarte geräucherte Schweinswurst','Roher Speck','Zwiebel','Knoblauch','Olivenöl','Salz','Schwarzer Pfeffer','Kochwasser','Getrocknete Lorbeerblätter, zum Entfernen'],
'groups':{'Alubias y cocción':'Bohnen und Kochwasser','Carnes':'Fleisch','Sofrito y sazón':'Aromaten und Würzung'},'units':{'hojas':'Blätter'},
'steps':[
['Bohnen gekühlt einweichen','500 g getrocknete schwarze Bohnen verlesen, Steinchen und beschädigte Bohnen entfernen und abspülen. In einem großen Behälter mit ungefähr 1,5 Litern Wasser mehrere Zentimeter bedecken. Zugedeckt 8 Stunden im Kühlschrank bei höchstens 4 °C einweichen; bei aufgesogenem Wasser mehr zugeben. Danach das gesamte Einweichwasser wegschütten und Bohnen abspülen. Dieses Wasser kommt zusätzlich zu den 2,5 Litern Kochwasser hinzu.'],
['Zutaten vorbereiten und Rohes trennen','200 g Zwiebel und 20 g Knoblauch auf einem sauberen Gemüsebrett hacken. 400 g frische knochenlose Schweineschulter in etwa 3 cm große Würfel und 100 g Speck in kurze Streifen schneiden, auf einem getrennten Brett für rohes Fleisch. 250 g Wurst in 1 cm dicke Scheiben schneiden; die Packung muss vollständig gegart ausweisen, keine rohe Wurst oder zu entsalzendes Pökelfleisch. Fleisch bis zum Garen kühlen, nach Kontakt mit rohem Schweinefleisch Hände und Geräte reinigen.'],
['Bohnen zuerst sprudelnd kochen','Abgetropfte Bohnen in einen mindestens 6 Liter großen Topf mit 2,5 Litern frischem Wasser und 2 Lorbeerblättern geben. Aufkochen, als Richtwert etwa 15 Minuten, und mindestens 30 Minuten deutlich sprudelnd kochen lassen, ohne Deckel zur Kontrolle von Schaum und Überlaufen. Schaum abschöpfen; kochendes Wasser zugeben, falls die Bohnen nicht mehr bedeckt sind. Rohe oder harte Bohnen nicht probieren und diesen Schritt nicht durch einen Schongarer ersetzen.'],
['Fleisch und Zwiebeln anbraten','Während die Bohnen kochen, 15 g Öl in einer breiten Pfanne bei mittlerer Hitze erhitzen. Speck etwa 5 Minuten unter Rühren anbraten, bis er leicht bräunt. Schweinefleisch in zwei Durchgängen jeweils etwa 4 Minuten nur außen anbraten; fertig garen muss es im Eintopf. Fleisch auf einen dafür reservierten Teller geben. Zwiebel in derselben Pfanne 7 Minuten, Knoblauch 1 Minute und Wurst 4 Minuten braten. Alles einschließlich Fett aufbewahren: Die Nährwertschätzung zählt es vollständig.'],
['Eintopf weich köcheln lassen','Nach 30 Minuten sprudelndem Kochen Fleisch, Wurst, Aromaten und Pfannensaft in den Topf geben; Pfanne mit etwas heißer Brühe auskratzen. 1 g Pfeffer zugeben, Salz erst am Ende. Wieder sanft aufkochen und etwa 100 Minuten mit leicht geöffnetem Deckel köcheln, alle 15–20 Minuten vom Boden her umrühren. Bohnen und Fleisch knapp bedeckt halten, bei Bedarf kochendes Wasser in Schritten von 100 ml nachgießen. Ansetzen verhindern und nicht so stark kochen, dass alle Bohnen zerfallen.'],
['Gargrad und Konsistenz prüfen','Mit sauberem Lebensmittelthermometer die Mitte mehrerer Fleischwürfel messen: Als praktisches Ziel dieses Eintopfs gelten mindestens 74 °C, über dem Minimum für ganze Fleischstücke. Fleisch muss außerdem unter einer Gabel leicht nachgeben; eine herausgehobene Bohne muss innen cremig ohne harten Kern sein. Bei fester Konsistenz oder zu niedriger Temperatur länger garen und erneut prüfen; Zeiten sind ein Vorschlag, keine Garantie. Nicht mit Geräten probieren, die rohes Fleisch berührt haben.'],
['Andicken, würzen und ruhen lassen','Eine Kelle weiche Bohnen ohne Fleisch herausheben, in einer Schüssel zerdrücken und zurückgeben. Etwa weitere 15 Minuten sanft unter Rühren köcheln, bis die Brühe den Löffelrücken leicht überzieht; bei zu dicker Konsistenz kochendes Wasser zugeben. Beide Lorbeerblätter entfernen. Erst jetzt probieren und die vorgesehenen 4 g Salz oder weniger bei bereits salzigen Fleischwaren zugeben; weniger Salz verändert die Natriumschätzung. Herd ausschalten und 10 Minuten zugedeckt ruhen lassen.'],
['Portionieren und rasch kühlen','In 8 Portionen mit ähnlichen Mengen Bohnen, Fleisch und Brühe teilen. Reis, Orange oder Farofa passen dazu, sind aber weder Zutaten noch Nährwerten zugerechnet. Reste rasch in kleine flache Behälter aufteilen und innerhalb von 2 Stunden bei höchstens 4 °C kühlen, bei Umgebung über 32 °C innerhalb 1 Stunde; nicht den ganzen großen Topf draußen abkühlen lassen. Binnen 3–4 Tagen verbrauchen oder portionsweise einfrieren; 2 Monate sind ein Qualitätsvorschlag. Im Kühlschrank auftauen und unter Rühren an mehreren Stellen auf mindestens 74 °C erhitzen.']],
'notes':'Getrocknete schwarze Bohnen verwenden; gegarte Bohnen können bei diesen Mengen und Zeiten nicht einfach eingesetzt werden. Diese Variante enthält kein Trockenfleisch, Schweineohr oder Schweinefuß; dafür wären anderer Ablauf und Nährwertberechnung nötig. Laut Packung vollständig gegarte Wurst wählen: geräuchert bedeutet nicht immer gegart. Gegarte Linguiça oder entsprechende geräucherte Schweinswurst passt; die Marke beeinflusst Geschmack und Natrium. Frische Schulter muss nicht entsalzt werden. Für dünnere Brühe kochendes Wasser zugeben, zum Andicken gekochte Bohnen statt Mehl zerdrücken. Saure Zutaten erst zugeben, wenn Bohnen weich sind. Ruhe abseits der Hitze ersetzt keine schnelle Kühlung der Reste.',
'faq':[['Kann ich das Einweichen weglassen?','Dieser Vorschlag setzt 8 Stunden gekühltes Einweichen und frisches Kochwasser voraus. Eine gleichwertige Zeit ohne Einweichen wird nicht angegeben; der Ablauf ändert sich, und das erste 30-minütige Kochen entfällt dadurch nicht.'],['Warum bleiben die Bohnen hart?','Alte Bohnen, hartes Wasser oder früh zugegebene Säure können die Garzeit verlängern. Genug heißes Wasser halten und bis ohne harten Kern kochen; vorgesehenes Salz am Ende zugeben.'],['Wie dicke ich ohne Mehl an?','Eine Kelle weiche Bohnen ohne Fleisch zerdrücken und in den Eintopf zurückgeben. Weitere 15 Minuten sanft unter Rühren kochen; bei zu dicker Konsistenz kochendes Wasser zufügen.']],
'keywords':['hausgemachte Feijoada','Feijoada schwarze Bohnen','Schweinefleisch Bohnen Eintopf'],
'cover_alt':'Feijoada aus schwarzen Bohnen mit Schweinefleischwürfeln, Speck und geräucherten Wurstscheiben in dunkler Brühe',
'nutrition':{'serving_size':'1 von 8 Eintopfportionen, ohne Beilagen','method':'Zehn geprüfte USDA-Datensätze, rohe essbare Gewichte von Bohnen, Schweinefleisch und Speck sowie Gewicht der bereits gegarten Wurst; Summe durch 8. Räucherwurst wird mit dem allgemeinen Datensatz für geräucherte Schweinswurst angenähert, nicht mit einem speziellen Linguiça-Datensatz. Fett und verbleibende Brühe vollständig gerechnet; entfernte Lorbeerblätter und Einweichwasser ausgeschlossen.','note':'Informationsschätzung, keine Analyse des fertigen Eintopfs. Marke und Salzgehalt von Wurst und Speck, Einweichen, Ausbeute und Brühenverteilung ändern die Werte. Reis, Orange, Farofa und Gemüsebeilagen nicht enthalten.'}
},
'fr':{
'path':'/fr/recette-de-feijoada','historical_path':True,'title':'Feijoada maison aux haricots noirs et au porc','seo_title':'Feijoada maison aux haricots noirs et au porc',
'excerpt':'Feijoada maison pour 8 aux haricots noirs, porc, lard et saucisse fumée : trempage, ébullition initiale, mijotage et conservation expliqués.',
'summary':'Cette feijoada maison associe haricots noirs, épaule de porc fraîche, lard et saucisse fumée entièrement cuite dans un bouillon sombre épaissi avec une partie des haricots. C’est une adaptation aux ingrédients clairement identifiés, sans viandes salées à dessaler ; elle ne représente pas toutes les variantes brésiliennes.\n\nLa proposition donne 8 portions de ragoût. Les 680 minutes estimées comprennent 8 heures de trempage au réfrigérateur, 30 minutes de préparation, 160 de cuisson et 10 de repos. Les aromates sont revenus pendant que les haricots bouillent. Quantités, rendement et durées restent à confirmer par un essai en cuisine ; tendreté et température priment sur le minuteur.',
'difficulty':'Moyenne','course':'Plat principal','cuisine':'Brésilienne, adaptation maison',
'ingredients':['Haricots noirs secs','Épaule de porc fraîche désossée','Saucisse de porc fumée entièrement cuite','Lard cru','Oignon','Ail','Huile d’olive','Sel','Poivre noir','Eau de cuisson','Laurier séché, à retirer'],
'groups':{'Alubias y cocción':'Haricots et cuisson','Carnes':'Viandes','Sofrito y sazón':'Aromates et assaisonnement'},'units':{'hojas':'feuilles'},
'steps':[
['Faire tremper les haricots au froid','Triez les 500 g de haricots noirs secs, retirez cailloux et grains abîmés, puis rincez. Placez dans un grand récipient avec environ 1,5 litre d’eau, recouverts de plusieurs centimètres. Couvrez et laissez tremper 8 heures au réfrigérateur à 4 °C ou moins ; ajoutez de l’eau si elle est absorbée. Jetez toute l’eau de trempage et rincez ensuite. Cette eau s’ajoute aux 2,5 litres réservés à la cuisson.'],
['Préparer et séparer la viande crue','Hachez les 200 g d’oignon et les 20 g d’ail sur une planche propre pour légumes. Sur une autre planche pour viande crue, coupez les 400 g d’épaule fraîche désossée en cubes d’environ 3 cm et les 100 g de lard en courtes lanières. Coupez les 250 g de saucisse en rondelles de 1 cm ; choisissez un produit étiqueté entièrement cuit, pas une saucisse fraîche ni une viande salée à dessaler. Gardez les viandes au froid jusqu’à cuisson et lavez mains et ustensiles après le porc cru.'],
['Faire bouillir les haricots avant de réduire le feu','Mettez les haricots égouttés dans une marmite d’au moins 6 litres avec les 2,5 litres d’eau fraîche et les 2 feuilles de laurier. Portez à ébullition, environ 15 minutes à titre indicatif, puis maintenez une franche ébullition au moins 30 minutes sans couvercle pour surveiller mousse et débordement. Écumez à la cuillère ; ajoutez de l’eau bouillante si les grains ne sont plus couverts. Ne goûtez pas de haricots crus ou durs et ne remplacez pas cette étape par une mijoteuse.'],
['Dorer les viandes et les aromates','Pendant l’ébullition, chauffez une grande poêle à feu moyen avec les 15 g d’huile. Faites revenir le lard environ 5 minutes en remuant, jusqu’au début de coloration. Ajoutez le porc en deux fois, environ 4 minutes par tournée, pour dorer seulement la surface ; la cuisson finira dans le ragoût. Réservez les viandes dans une assiette dédiée. Faites revenir dans la même poêle l’oignon 7 minutes, l’ail 1 minute et la saucisse 4 minutes. Gardez tout, graisse comprise : l’estimation nutritionnelle la compte entièrement.'],
['Mijoter jusqu’à tendreté','Après les 30 minutes d’ébullition, ajoutez viandes, saucisse, aromates et jus de poêle à la marmite, en grattant la poêle avec un peu de bouillon chaud. Ajoutez 1 g de poivre ; réservez le sel pour la fin. Retrouvez un léger frémissement et cuisez environ 100 minutes, couvercle entrouvert, en remuant depuis le fond toutes les 15–20 minutes. Gardez haricots et viandes à peine couverts, ajoutez de l’eau bouillante par 100 ml si nécessaire. Évitez qu’ils attachent ou que trop forte ébullition défasse tous les grains.'],
['Vérifier cuisson et texture','Avec un thermomètre propre, mesurez le cœur de plusieurs cubes de porc : ce ragoût fixe un objectif pratique d’au moins 74 °C, supérieur au minimum pour les morceaux entiers. La viande doit aussi céder facilement sous une fourchette ; un haricot sorti à la cuillère doit être crémeux à cœur, sans noyau dur. Si quelque chose reste ferme ou insuffisamment chaud, prolongez et vérifiez encore ; les durées sont proposées, pas garanties. Ne goûtez pas avec des ustensiles ayant touché la viande crue.'],
['Épaissir, saler et laisser reposer','Prélevez une louche de haricots tendres sans viande, écrasez-les dans un bol puis remettez la pâte dans la marmite. Mijotez environ 15 minutes supplémentaires en remuant, jusqu’à ce que le bouillon nappe légèrement le dos d’une cuillère ; ajoutez de l’eau bouillante s’il épaissit trop. Retirez les 2 feuilles de laurier. Goûtez seulement maintenant et ajoutez les 4 g de sel prévus, ou moins si les charcuteries salent déjà suffisamment ; moins de sel modifie le sodium estimé. Coupez le feu et laissez reposer 10 minutes à couvert.'],
['Partager et refroidir rapidement','Répartissez en 8 portions avec des quantités similaires de haricots, viandes et bouillon. Riz, orange ou farofa peuvent accompagner, mais ne sont inclus ni aux ingrédients ni aux valeurs nutritionnelles. Pour conserver, répartissez rapidement les restes en petits récipients peu profonds et réfrigérez à 4 °C ou moins dans les 2 heures, ou 1 heure si l’air dépasse 32 °C ; n’attendez pas que toute la grosse marmite refroidisse dehors. Consommez en 3–4 jours ou congelez par portions ; 2 mois est une proposition de qualité. Décongelez au réfrigérateur et réchauffez en remuant jusqu’à au moins 74 °C en plusieurs points.']],
'notes':'Utilisez des haricots noirs secs ; les remplacer par des haricots cuits en conservant ces quantités et durées ne convient pas. Cette version ne contient ni viande séchée, ni oreille, ni pied de porc ; leur ajout demande un autre procédé et calcul nutritionnel. La saucisse doit être entièrement cuite selon l’emballage : fumée ne signifie pas toujours cuite. Linguiça cuite ou saucisse de porc fumée équivalente convient ; la marque change saveur et sodium. L’épaule fraîche ne se dessale pas. Allongez avec de l’eau bouillante, épaississez en écrasant des haricots cuits plutôt qu’avec de la farine. N’ajoutez pas d’ingrédients acides avant tendreté des haricots. Le repos hors du feu ne remplace pas la réfrigération rapide des restes.',
'faq':[['Puis-je supprimer le trempage ?','Cette proposition commence par 8 heures de trempage au froid et de l’eau fraîche pour cuire. Aucune durée équivalente sans trempage n’est donnée ; cela change le procédé et ne supprime pas les 30 minutes d’ébullition initiale.'],['Pourquoi les haricots restent-ils durs ?','Des grains anciens, une eau dure ou des ingrédients acides ajoutés tôt peuvent prolonger la cuisson. Maintenez assez d’eau chaude et cuisez jusqu’à disparition du cœur dur ; salez à la fin comme prévu.'],['Comment épaissir sans farine ?','Écrasez une louche de haricots tendres sans viande et remettez au ragoût. Mijotez encore 15 minutes en remuant ; ajoutez de l’eau bouillante si trop épais.']],
'keywords':['feijoada maison','feijoada haricots noirs','ragoût de porc et haricots noirs'],
'cover_alt':'Feijoada de haricots noirs avec porc, lard et rondelles de saucisse fumée dans un bouillon sombre',
'nutrition':{'serving_size':'1 des 8 portions de ragoût, sans accompagnement','method':'Dix fiches USDA vérifiées, poids crus comestibles des haricots, porc et lard, poids de la saucisse déjà cuite ; somme divisée par 8. La saucisse fumée est approximée avec une fiche générique de saucisse de porc fumée, pas une fiche spécifique de linguiça brésilienne. Toute la graisse et le bouillon conservé comptent. Laurier retiré et eau de trempage jetée sont exclus.','note':'Estimation informative, pas analyse du ragoût terminé. Marque et sel des charcuteries, trempage, rendement et répartition du bouillon modifient les chiffres. Riz, orange, farofa et légumes d’accompagnement exclus.'}
}}
p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
print('Authored EN, DE and FR feijoada localizations; publication pending.')
