import json
from pathlib import Path
p=Path(__file__).resolve().parents[1]/'editorial/barras-de-cereal-localizaciones-20261008.json'
assert not p.exists()
data={
 'en':{
  'path':'/en/cereal-bars','historical_path':True,
  'title':'Oat cereal bars with honey and peanut butter','seo_title':'Oat cereal bars with honey and peanut butter',
  'excerpt':'Make 12 oat cereal bars with honey, peanut butter and raisins. Follow pan-toasting, firm pressing and thorough chilling before cutting, step by step.',
  'summary':'These cereal bars combine toasted rolled oats, almonds, sunflower seeds and raisins, bound with honey and peanut butter. The mixture is pressed into a tin and cut after chilling; the slab is not baked.\n\nThe proposal makes 12 soft, compact bars rather than crunchy ones. The estimated 165 minutes include 10 minutes of cooking, 15 of cooling and at least 120 in the refrigerator. Quantities, firmness, yield and times still need confirmation in a kitchen test.',
  'difficulty':'Easy','course':'Sweet snack','cuisine':'International',
  'ingredients':['Dry rolled oats','Smooth unsalted peanut butter','Honey','Almonds','Dark seedless raisins','Shelled sunflower seeds','Vanilla extract','Salt'],
  'groups':{'Mezcla seca':'Dry mixture','Para ligar':'Binder'},
  'steps':[
   ['Prepare the tin and weigh','Wash your hands and clean the work surface. Line a 20 × 20 cm square tin with baking parchment, leaving handles to lift the mixture. Weigh the ingredients and chop the 50 g almonds into about 5 mm pieces; cut large raisins so they do not tear the bars apart. Stir the peanut butter in its jar to reincorporate separated oil. Use rolled oats suitable for this preparation according to their label, not whole oat groats.'],
   ['Toast the oats and seeds','Heat a wide dry frying pan over medium-low heat. Add the 200 g rolled oats, 50 g almonds and 30 g sunflower seeds. Stir almost continuously for about 8 minutes until fragrant and lightly coloured, without burning. Lower the heat if they brown too quickly. Transfer to a large bowl and let cool slightly while preparing the binder.'],
   ['Warm the honey and peanut butter','Put the 100 g honey and 100 g peanut butter in a small saucepan. Heat gently for about 2 minutes, stirring until fluid and smooth, without boiling or caramelising. Remove from the heat and add the 3 g vanilla and 1 g salt. The hot mixture can burn; handle it with a spatula rather than your fingers.'],
   ['Mix in the raisins and binder','Add the 50 g raisins to the bowl of warm oats. Pour in all the honey-peanut mixture and stir with a spatula for 1–2 minutes, scraping the bottom and sides, until every flake is coated and no dry pockets remain. The sticky mixture should hold together when pressed with the spatula; it should not be liquid or a whipped batter.'],
   ['Press into an even layer','Transfer to the lined tin and spread into the corners. Lay another sheet of parchment on top and press with the flat bottom of a glass or a spatula for 2–3 minutes. Aim for a layer about 1–1.5 cm thick without gaps, especially around the edges. Firm pressure helps the bars hold together; do not add liquid to soften them.'],
   ['Cool and refrigerate before cutting','Leave the tin at room temperature for about 15 minutes to lose its intense heat. Cover and refrigerate at 4 °C or below for at least 120 minutes, until the entire slab is cold and firm. It may take longer depending on the refrigerator and thickness; do not cut while warm. The proposed 165-minute total includes this cooling and chilling.'],
   ['Cut twelve bars','Lift the cold slab out by the parchment handles and put it on a clean board. Remove the top paper and cut with a large knife into 3 rows and 4 columns, making 12 bars about 6.7 × 5 cm. Press the knife down rather than sawing; wipe the blade between cuts if sticky. If the slab softens, refrigerate again before continuing. Crumbs can be served separately with yogurt, which is not included in the nutrition calculation.'],
   ['Serve and store chilled','Serve the bars cold, or let only the portion you will eat warm slightly. Wrap individually or store in a closed container with paper between layers at 4 °C or below for up to 5 days; follow any shorter ingredient-label limit. To freeze, wrap individually for up to 1 month and thaw in the refrigerator. These are proposed storage periods, not shelf-life test results. The bars soften in heat and were not designed to stay firm for hours outside the refrigerator.']
  ],
  'notes':'Use smooth unsalted peanut butter without added sugar; a very runny product or different formula changes firmness. You can replace raisins with the same weight of chopped dried apricots, but nutrition and texture change. Switching honey to another syrup or peanut butter to another spread requires checking binding and allergens again; the same result is not promised. Contains peanuts and almonds; oats can have gluten cross-contact, so check labels when relevant. Keep bars chilled for transport and do not present them as sugar-free: they contain honey and dried fruit.',
  'faq':[['Why do they fall apart when cut?','The mixture needs firm pressing and thorough chilling. Press the corners too and refrigerate for at least 120 minutes, longer if still soft. Very runny peanut butter and cutting while warm change the result.'],['Are the bars baked?','The slab is not baked. Oats, almonds and seeds are toasted in a pan and the binder is warmed; the mixture is then pressed and refrigerated.'],['Can I carry them without refrigeration?','This proposal is stored chilled and softens in heat. Use a container with an ice pack for transport and take out only the portion you will eat; prolonged room-temperature stability has not been verified.']],
  'keywords':['cereal bars','oat and honey bars','peanut butter raisin bars'],
  'cover_alt':'Rectangular oat cereal bars with visible almonds, seeds and raisins, without chocolate or coating',
  'nutrition':{'serving_size':'1 of 12 bars, about 44 g before water loss','method':'Eight verified USDA entries per 100 g are weighted by ingredient amounts and divided by 12. The oat entry is for dry unfortified regular or quick oats, not cooked oats. Unsalted peanut butter without additions is assumed; toasting does not subtract nutrients from the batch.','note':'An informational estimate, not an analysis of the finished bars. Peanut butter brand, cut size and leftover mixture affect the result. All honey is included; these values do not constitute a low-sugar claim.'}
 },
 'de':{
  'path':'/de/musliriegel','historical_path':True,
  'title':'Müsliriegel mit Hafer, Honig und Erdnuss','seo_title':'Müsliriegel mit Hafer, Honig und Erdnuss',
  'excerpt':'12 Müsliriegel mit Hafer, Honig, Erdnussmus und Rosinen: Rösten in der Pfanne, festes Andrücken und gründliches Kühlen vor dem Schneiden.',
  'summary':'Diese Müsliriegel verbinden geröstete Haferflocken, Mandeln, Sonnenblumenkerne und Rosinen mit Honig und Erdnussmus. Die Mischung wird in eine Form gedrückt und nach dem Kühlen geschnitten; die Platte wird nicht gebacken.\n\nDer Vorschlag ergibt 12 weiche, kompakte Riegel, keine knusprigen. Die geschätzten 165 Minuten enthalten 10 Minuten Garen, 15 Minuten Abkühlen und mindestens 120 Minuten im Kühlschrank. Mengen, Festigkeit, Ausbeute und Zeiten sind noch nicht durch einen Küchentest bestätigt.',
  'difficulty':'Einfach','course':'Süßer Snack','cuisine':'International',
  'ingredients':['Trockene Haferflocken','Glattes ungesalzenes Erdnussmus','Honig','Mandeln','Dunkle kernlose Rosinen','Geschälte Sonnenblumenkerne','Vanilleextrakt','Salz'],
  'groups':{'Mezcla seca':'Trockene Mischung','Para ligar':'Zum Binden'},
  'steps':[
   ['Form vorbereiten und Zutaten wiegen','Hände waschen und die Arbeitsfläche reinigen. Eine quadratische Form von 20 × 20 cm mit Backpapier auslegen und überstehende Laschen zum Herausheben lassen. Zutaten wiegen und 50 g Mandeln in etwa 5 mm große Stücke hacken; große Rosinen zerkleinern, damit sie die Riegel nicht aufreißen. Erdnussmus im Glas verrühren, bis abgesetztes Öl wieder eingebunden ist. Laut Packung für diese Verwendung geeignete Haferflocken verwenden, keine ganzen Haferkörner.'],
   ['Hafer und Kerne rösten','Eine breite trockene Pfanne bei mittlerer bis niedriger Hitze erwärmen. 200 g Haferflocken, 50 g Mandeln und 30 g Sonnenblumenkerne zugeben. Etwa 8 Minuten fast ständig rühren, bis sie duften und etwas Farbe annehmen, ohne zu verbrennen. Bei schneller Bräunung die Hitze senken. In eine große Schüssel geben und leicht abkühlen lassen, während die Bindemischung entsteht.'],
   ['Honig und Erdnussmus erwärmen','100 g Honig und 100 g Erdnussmus in einen kleinen Topf geben. Bei niedriger Hitze etwa 2 Minuten unter Rühren erwärmen, bis die Mischung flüssiger und gleichmäßig ist, ohne Kochen oder Karamellisieren. Vom Herd nehmen und 3 g Vanille sowie 1 g Salz zugeben. Die heiße Mischung kann verbrennen; mit einem Teigschaber statt den Fingern bearbeiten.'],
   ['Rosinen und Bindemischung einarbeiten','50 g Rosinen zum lauwarmen Hafer geben. Die gesamte Honig-Erdnuss-Mischung zugießen und 1–2 Minuten mit einem Teigschaber rühren, dabei Boden und Wände abstreifen, bis jede Flocke überzogen ist und keine trockenen Stellen bleiben. Die klebrige Mischung soll beim Drücken mit dem Teigschaber zusammenhaften, nicht flüssig oder aufgeschlagen sein.'],
   ['Gleichmäßig festdrücken','In die vorbereitete Form geben und bis in die Ecken verteilen. Einen zweiten Papierbogen auflegen und 2–3 Minuten mit dem flachen Glasboden oder einem Teigschaber festdrücken. Eine etwa 1–1,5 cm dicke Schicht ohne Lücken, besonders an den Rändern, anstreben. Druck verhindert Zerbröseln; keine Flüssigkeit zum Weichmachen ergänzen.'],
   ['Abkühlen und vor dem Schneiden kühlen','Die Form etwa 15 Minuten bei Raumtemperatur stehen lassen, damit die starke Hitze entweicht. Abdecken und mindestens 120 Minuten bei höchstens 4 °C kühlen, bis die ganze Platte fest und kalt ist. Kühlschrank und Dicke können längeres Kühlen erfordern; nicht lauwarm schneiden. Die vorgeschlagenen 165 Minuten Gesamtzeit enthalten Abkühlen und Kühlen.'],
   ['Zwölf Riegel schneiden','Die kalte Platte an den Papierlaschen herausheben und auf ein sauberes Brett legen. Oberes Papier entfernen und mit einem großen Messer in 3 Reihen und 4 Spalten schneiden: 12 Riegel von etwa 6,7 × 5 cm. Messer nach unten drücken statt sägen; bei Kleben zwischen Schnitten reinigen. Wird die Platte weich, vor dem Fortfahren erneut kühlen. Krümel können separat mit Joghurt serviert werden; dieser Zusatz ist nicht in den Nährwerten enthalten.'],
   ['Servieren und kalt aufbewahren','Riegel kalt servieren oder nur die zu essende Portion kurz temperieren. Einzeln einwickeln oder in einem geschlossenen Behälter mit Papier zwischen Lagen bei höchstens 4 °C bis zu 5 Tage lagern; kürzere Vorgaben einer Zutatenpackung beachten. Zum Einfrieren einzeln verpacken, höchstens 1 Monat lagern und im Kühlschrank auftauen. Dies sind vorgeschlagene Zeiten, keine Haltbarkeitsprüfung. Bei Wärme werden sie weich und sollen nicht stundenlang außerhalb des Kühlschranks fest bleiben.']
  ],
  'notes':'Glattes ungesalzenes Erdnussmus ohne Zuckerzusatz verwenden; sehr flüssige Produkte oder andere Rezepturen ändern die Festigkeit. Rosinen können durch dieselbe Menge gehackter getrockneter Aprikosen ersetzt werden, aber Textur und Nährwerte ändern sich. Honig durch anderen Sirup oder Erdnussmus durch andere Creme zu ersetzen erfordert eine neue Prüfung von Bindung und Allergenen; gleiches Ergebnis wird nicht zugesagt. Enthält Erdnüsse und Mandeln; Hafer kann Glutenkontakt haben, daher bei Bedarf Packungen prüfen. Zum Transport kalt halten und nicht als zuckerfrei darstellen: Honig und Trockenfrüchte sind enthalten.',
  'faq':[['Warum zerfallen sie beim Schneiden?','Die Mischung braucht Druck und Kälte. Auch die Ecken festdrücken und mindestens 120 Minuten kühlen, länger wenn noch weich. Sehr flüssiges Erdnussmus und lauwarmes Schneiden verändern das Ergebnis.'],['Werden die Riegel gebacken?','Die Platte wird nicht gebacken. Hafer, Mandeln und Kerne werden in der Pfanne geröstet, die Bindemischung erwärmt; anschließend wird festgedrückt und gekühlt.'],['Kann ich sie ohne Kühlung mitnehmen?','Dieser Vorschlag wird kalt gelagert und bei Wärme weich. Für den Transport einen Behälter mit Kühlakku nutzen und nur die zu essende Portion herausnehmen; längere Stabilität bei Raumtemperatur ist nicht geprüft.']],
  'keywords':['Müsliriegel','Hafer Honig Riegel','Erdnuss Rosinen Riegel'],
  'cover_alt':'Rechteckige Haferriegel mit sichtbaren Mandeln, Kernen und Rosinen, ohne Schokolade oder Überzug',
  'nutrition':{'serving_size':'1 von 12 Riegeln, etwa 44 g vor Wasserverlust','method':'Acht überprüfte USDA-Einträge je 100 g werden nach Zutatengewichten gewichtet und durch 12 geteilt. Der Hafereintrag gilt für trockene, nicht angereicherte normale oder schnelle Flocken, nicht gekochten Hafer. Ungesalzenes Erdnussmus ohne Zusätze wird angenommen; Rösten zieht keine Nährstoffe vom gesamten Ansatz ab.','note':'Informative Schätzung, keine Analyse der fertigen Riegel. Marke des Erdnussmuses, Schnittgröße und Reste verändern das Ergebnis. Der gesamte Honig ist eingerechnet; die Zahlen sind keine Aussage über niedrigen Zuckergehalt.'}
 },
 'fr':{
  'path':'/fr/barres-de-cereales','historical_path':True,
  'title':'Barres de céréales à l’avoine, miel et cacahuète','seo_title':'Barres de céréales à l’avoine, miel et cacahuète',
  'excerpt':'Préparez 12 barres d’avoine au miel, cacahuète et raisins. Torréfaction à la poêle, tassement ferme et refroidissement avant la découpe, pas à pas.',
  'summary':'Ces barres réunissent flocons d’avoine torréfiés, amandes, graines de tournesol et raisins secs, liés au miel et à la purée de cacahuète. La préparation est tassée dans un moule puis coupée après refroidissement ; la plaque n’est pas cuite au four.\n\nLa proposition donne 12 barres souples et compactes, pas croustillantes. Les 165 minutes estimées comprennent 10 minutes de cuisson, 15 de refroidissement et au moins 120 au réfrigérateur. Doses, fermeté, rendement et temps restent à confirmer par un essai en cuisine.',
  'difficulty':'Facile','course':'Goûter sucré','cuisine':'Internationale',
  'ingredients':['Flocons d’avoine secs','Purée de cacahuète lisse non salée','Miel','Amandes','Raisins secs noirs sans pépins','Graines de tournesol décortiquées','Extrait de vanille','Sel'],
  'groups':{'Mezcla seca':'Mélange sec','Para ligar':'Pour lier'},
  'steps':[
   ['Préparer le moule et peser','Lavez-vous les mains et nettoyez le plan de travail. Chemisez un moule carré de 20 × 20 cm de papier cuisson, en laissant des rabats pour soulever la préparation. Pesez les ingrédients et hachez les 50 g d’amandes en morceaux d’environ 5 mm ; coupez les gros raisins pour qu’ils ne déchirent pas les barres. Remuez la purée de cacahuète dans son pot pour réincorporer l’huile séparée. Utilisez des flocons adaptés à cet usage selon leur emballage, pas des grains d’avoine entiers.'],
   ['Torréfier l’avoine et les graines','Chauffez une grande poêle sèche à feu moyen-doux. Ajoutez les 200 g de flocons, 50 g d’amandes et 30 g de graines. Remuez presque continuellement environ 8 minutes, jusqu’à ce qu’ils sentent bon et se colorent légèrement sans brûler. Baissez le feu s’ils dorent trop vite. Transférez dans un grand saladier et laissez tiédir pendant la préparation du liant.'],
   ['Chauffer le miel et la purée de cacahuète','Mettez les 100 g de miel et 100 g de purée de cacahuète dans une petite casserole. Chauffez à feu doux environ 2 minutes en remuant, jusqu’à obtenir un mélange fluide et uniforme, sans ébullition ni caramélisation. Retirez du feu et ajoutez les 3 g de vanille et 1 g de sel. Le mélange chaud peut brûler ; manipulez-le avec une spatule, pas avec les doigts.'],
   ['Ajouter les raisins et le liant','Ajoutez les 50 g de raisins à l’avoine tiède. Versez tout le mélange miel-cacahuète et remuez à la spatule 1–2 minutes, en raclant fond et parois, jusqu’à enrober chaque flocon sans poche sèche. La préparation doit coller et s’agglomérer sous la spatule, sans être liquide ni mousseuse.'],
   ['Tasser en couche régulière','Versez dans le moule chemisé et répartissez jusque dans les coins. Posez une autre feuille dessus et pressez 2–3 minutes avec le fond plat d’un verre ou une spatule. Visez une couche d’environ 1–1,5 cm sans trous, surtout aux bords. La pression évite l’émiettement ; n’ajoutez pas de liquide pour assouplir.'],
   ['Refroidir et réfrigérer avant de couper','Laissez le moule environ 15 minutes à température ambiante pour dissiper la forte chaleur. Couvrez et réfrigérez à 4 °C maximum au moins 120 minutes, jusqu’à ce que toute la plaque soit froide et ferme. Le réfrigérateur et l’épaisseur peuvent demander plus de temps ; ne découpez pas tiède. Les 165 minutes prévues incluent ce refroidissement et la réfrigération.'],
   ['Découper douze barres','Soulevez la plaque froide par les rabats et posez-la sur une planche propre. Retirez le papier supérieur et découpez avec un grand couteau en 3 rangées et 4 colonnes, soit 12 barres d’environ 6,7 × 5 cm. Appuyez vers le bas sans scier ; nettoyez la lame entre les coupes si elle colle. Si la plaque ramollit, réfrigérez à nouveau. Les miettes peuvent se servir à part avec du yaourt, non inclus dans le calcul nutritionnel.'],
   ['Servir et conserver au froid','Servez froid ou laissez tempérer uniquement la portion à manger. Emballez chaque barre ou conservez dans une boîte fermée avec papier entre les couches, à 4 °C maximum jusqu’à 5 jours ; respectez toute indication plus courte d’un ingrédient. Pour congeler, emballez individuellement jusqu’à 1 mois et décongelez au réfrigérateur. Ces durées sont proposées, pas testées en conservation. Les barres ramollissent à la chaleur et ne sont pas conçues pour rester fermes des heures hors du réfrigérateur.']
  ],
  'notes':'Utilisez une purée de cacahuète lisse sans sel ni sucre ajouté ; une version très liquide ou de formulation différente change la fermeté. Remplacez éventuellement les raisins par le même poids d’abricots secs hachés, mais texture et nutrition changent. Remplacer miel ou purée de cacahuète demande de revérifier liaison et allergènes ; le résultat identique n’est pas garanti. Contient cacahuètes et amandes ; l’avoine peut avoir un contact avec le gluten, vérifiez les emballages si nécessaire. Transportez au froid et ne présentez pas les barres comme sans sucre : elles contiennent miel et fruits secs.',
  'faq':[['Pourquoi s’émiettent-elles à la découpe ?','Il faut pression et froid. Tassez aussi les coins et réfrigérez au moins 120 minutes, davantage si la préparation reste souple. Une purée très liquide et une découpe tiède changent le résultat.'],['Les barres sont-elles cuites au four ?','La plaque ne passe pas au four. Avoine, amandes et graines sont torréfiées à la poêle et le liant chauffé ; ensuite la préparation est tassée et réfrigérée.'],['Puis-je les transporter sans réfrigération ?','Cette proposition se conserve au froid et ramollit à la chaleur. Utilisez un contenant avec accumulateur de froid et sortez uniquement la portion à manger ; la stabilité prolongée à température ambiante n’est pas vérifiée.']],
  'keywords':['barres de céréales','barres avoine miel','barres cacahuète raisins'],
  'cover_alt':'Barres rectangulaires d’avoine aux amandes, graines et raisins visibles, sans chocolat ni nappage',
  'nutrition':{'serving_size':'1 des 12 barres, environ 44 g avant perte d’eau','method':'Huit fiches USDA vérifiées pour 100 g sont pondérées par les poids d’ingrédients et divisées par 12. La fiche d’avoine concerne des flocons réguliers ou rapides secs non enrichis, pas de l’avoine cuite. La purée est supposée sans sel ni ajouts ; la torréfaction ne déduit pas de nutriments du lot.','note':'Estimation informative, pas analyse des barres préparées. Marque de purée, taille de découpe et restes modifient le résultat. Tout le miel est inclus ; ces chiffres ne constituent pas une allégation de faible teneur en sucre.'}
 }
}
p.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
