"""Freeze original chocolate custard, primary nutrition evidence and photo briefs."""
import copy
import hashlib
import html
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
slug = 'receta-de-flan-de-chocolate'
destination = root / 'editorial' / f'{slug}-20261008.json'
assert not destination.exists(), 'Do not replace a frozen recipe'
registry = json.loads((root / 'editorial/lote03-identidades-rutas-20261008.json').read_text())
identity = next(r for r in registry['recipes'] if r['slug'] == slug)
foods = json.loads(Path('/workspace/scratch/cda9798a16b5/tmp/usda-foods.json').read_text())
mapping = {1008: 'calories', 1003: 'protein_g', 1005: 'carbs_g', 1004: 'fat_g', 1258: 'saturated_fat_g', 1079: 'fiber_g', 2000: 'sugar_g', 1093: 'sodium_mg'}
selected = [('leche entera pasteurizada', 750, 171265), ('huevo entero crudo sin cáscara', 300, 171287), ('azúcar total entre caramelo y mezcla', 180, 169655), ('cacao natural en polvo sin azúcar', 45, 169593)]
inputs = []
for name, grams, food_id in selected:
    food = foods[str(food_id)]
    values = {mapping[n['nutrient']['id']]: n['amount'] for n in food['foodNutrients'] if n['nutrient']['id'] in mapping}
    assert set(values) == set(mapping.values()), (food_id, values)
    inputs.append({'ingredient': name, 'edible_grams': grams, 'fdc_id': food_id, 'fdc_description': food['description'], 'per_100g': values, 'source_url': f'https://fdc.nal.usda.gov/food-details/{food_id}/nutrients'})
nutrition = {k: round(sum(a['edible_grams'] / 100 * a['per_100g'][k] for a in inputs) / 8, 1) for k in mapping.values()}
nutrition.update(estimated=True, source='USDA FoodData Central — SR Legacy (abril de 2018)', source_url='https://fdc.nal.usda.gov/download-datasets/', inputs=inputs,
    serving_size='Un flan y su octava parte del caramelo; 8 porciones propuestas',
    method='Suma los nutrientes de 750 g de leche entera, 300 g de huevo sin cáscara, 180 g de azúcar total y 45 g de cacao natural sin azúcar, según cuatro fichas USDA verificadas, y divide entre 8. El agua del caramelo no aporta energía y el agua del baño María no se consume. Se incluye todo el caramelo servido; no se inventan pérdidas de azúcar o nutrientes por evaporación.',
    note='Estimación por ingredientes, no análisis ni prueba de cocina. Leche 3,25 % de grasa y cacao natural sin azúcar; bebidas vegetales, leche condensada, cacao azucarado o chocolate en tableta requieren otra fórmula. Ocho raciones y peso final pendientes de medir; no se afirma un peso servido. No incluye nata, fruta, bizcocho ni adornos. Los ocho nutrientes están presentes en las cuatro fichas; no se rellenan ausencias con cero.')
ingredients = [
    {'name': 'azúcar blanco granulado para el caramelo', 'amount': '60', 'unit': 'g', 'group': 'Caramelo'},
    {'name': 'agua potable para el caramelo', 'amount': '30', 'unit': 'ml', 'group': 'Caramelo'},
    {'name': 'leche entera pasteurizada de 3,25 % de grasa', 'amount': '750', 'unit': 'g', 'group': 'Flan'},
    {'name': 'huevo entero crudo, pesado sin cáscara', 'amount': '300', 'unit': 'g', 'group': 'Flan'},
    {'name': 'azúcar blanco granulado para la mezcla', 'amount': '120', 'unit': 'g', 'group': 'Flan'},
    {'name': 'cacao natural en polvo sin azúcar', 'amount': '45', 'unit': 'g', 'group': 'Flan'},
    {'name': 'agua caliente para el baño María, sin incorporarla al flan', 'amount': '1000', 'unit': 'ml', 'group': 'Baño María'},
]
steps = [
    ('Prepara los moldes y pesa los ingredientes', 'Prepara 8 moldes individuales de cerámica apta para horno, de unos 180–200 ml, una bandeja profunda estable, báscula, varillas, termómetro alimentario, cazo y guantes secos. Precalienta el horno a 160°C, calor arriba y abajo, durante unos 15 minutos mientras preparas los ingredientes; ese tiempo se solapa con los 25 minutos de preparación y no se suma otra vez. Pesa la leche en gramos y los 300 g de huevo sin cáscara; no supongas un número fijo de huevos. Mantén leche y huevos refrigerados hasta usarlos y lava manos y superficies después de manipular cáscaras. Los 8 moldes, porciones y tiempos son propuestas sin prueba de cocina.'),
    ('Cocina y reparte el caramelo', 'Pon 60 g de azúcar y 30 ml de agua potable en un cazo limpio. Calienta a fuego medio unos 10 minutos, hasta obtener un ámbar claro, sin remover con cuchara una vez disuelto; inclina suavemente el cazo si hace falta. Retira antes de que oscurezca y amargue. Reparte enseguida entre los 8 moldes y gira cada uno con guantes para cubrir el fondo. El caramelo causa quemaduras graves: no lo pruebes, no lo toques y no añadas líquido frío al azúcar caliente. Déjalo endurecer mientras preparas la mezcla. Se cuenta todo el azúcar y se servirá todo el caramelo; si queda una cantidad sin usar, registra la diferencia y recalcula.'),
    ('Disuelve el cacao en la leche', 'Mezcla los 45 g de cacao natural sin azúcar con 150 g de los 750 g de leche, hasta formar una pasta lisa. Incorpora los 600 g restantes y calienta en cazo limpio a fuego bajo unos 5 minutos, removiendo, hasta que esté bien templada y sin grumos, aproximadamente 55–60°C; no la hiervas. Raspa el cazo para incorporar toda la leche y el cacao, sin añadir chocolate en tableta, café ni vainilla a esta fórmula. El cacao alcalinizado o azucarado y las bebidas vegetales no comparten necesariamente los datos de esta receta.'),
    ('Mezcla el huevo con el azúcar', 'En un cuenco limpio mezcla los 300 g de huevo entero sin cáscara con los 120 g de azúcar de la mezcla. Remueve con varillas de forma suave hasta homogeneizar, sin montar una espuma espesa. No pruebes la mezcla cruda y no reutilices utensilios de cáscaras sucias. El azúcar total de la receta es 180 g: 60 g en el caramelo y 120 g aquí. Usa huevo entero, no solo yemas o claras, pues cambia cuajado y cálculo nutricional.'),
    ('Templa el huevo e incorpora la leche', 'Añade primero una pequeña parte de la leche con cacao templada al huevo, en hilo y removiendo suavemente. Incorpora el resto poco a poco, sin verter leche hirviendo ni batir aire en exceso. Raspa ambos recipientes para aprovechar toda la mezcla. Deja desaparecer la espuma superficial antes de llenar. No filtres ni deseches sólidos de cacao manteniendo el mismo cálculo: si un lote tiene grumos persistentes o huevo cuajado prematuramente, registra el fallo en lugar de presentarlo como mezcla correcta.'),
    ('Llena los moldes y monta el baño María', 'Reparte toda la mezcla sobre el caramelo endurecido de los 8 moldes, dejando margen superior. Coloca los moldes en la bandeja y lleva la bandeja a una rejilla estable del horno antes de añadir agua, para no transportar una carga de agua hirviendo. Vierte con cuidado unos 1000 ml de agua caliente alrededor de los moldes, hasta aproximadamente media altura, sin mojar la mezcla. La cantidad puede variar con la bandeja: registra el agua real, que no se consume ni se incluye en nutrición. No llenes hasta el borde ni uses recipientes no aptos para choque térmico.'),
    ('Hornea y comprueba el cuajado', 'Hornea a 160°C durante unos 60 minutos propuestos. Según horno, molde y temperatura inicial puede requerir aproximadamente 50–70 minutos: empieza a comprobar antes y registra el tiempo real. El baño María debe mantenerse suave, sin hervir violentamente. Busca bordes firmes y centro ligeramente tembloroso, no líquido. Comprueba con termómetro limpio que el centro supera al menos 71°C para una preparación con huevo; el cuajado de esta propuesta se busca alrededor de 80–85°C, sin convertir esa textura en prueba de cocina. Si aún está líquido o no llega a la temperatura mínima, prolonga y vuelve a medir. No sirvas flan crudo ni tomes solo el reloj como garantía.'),
    ('Enfría y refrigera los flanes', 'Con guantes secos y sin inclinar agua caliente sobre ti, saca los moldes del baño María y colócalos en una rejilla unos 20 minutos como propuesta de enfriado inicial. Después refrigera en recipientes protegidos durante al menos 4 horas, a 4°C o menos, antes de desmoldar. No dejes un postre de leche y huevo toda la noche a temperatura ambiente: debe entrar al frío antes de 2 horas fuera del control térmico, o 1 hora si el ambiente supera 32°C; desecha lo que exceda. El enfriado inicial y la refrigeración se cuentan: 25 preparación + 75 cocción (10 caramelo, 5 leche, 60 horno) + 20 enfriado + 240 refrigeración = 360 minutos propuestos; puede cambiar con la cocción real.'),
    ('Desmolda y sirve con el caramelo', 'Cuando los 8 flanes estén fríos y firmes, pasa un cuchillo fino por el borde sin cortar profundamente. Invierte cada molde sobre un plato con borde, retíralo y deja caer su caramelo. Sirve 1 flan por porción incluyendo su caramelo; no añadas nata, fruta, virutas ni bizcocho dentro de los valores. Si se rompe o no ha cuajado, no ocultes el resultado como una prueba aprobada. Conserva tapado a 4°C o menos y consume dentro de 2 días como propuesta prudente, no vida útil ensayada. Contiene huevo, leche y lactosa; revisa el cacao y evita contaminación cruzada. No se presenta como sin azúcar, sin lácteos ni postre terapéutico.'),
]
prefix = '/recetas/' + slug + '/'
record = {k: identity[k] for k in ['id', 'recipe_group_id', 'slug', 'public_path', 'source_url']}
record.update(language='es', title='Flan de chocolate con cacao y caramelo al baño María', excerpt='Flanes individuales de cacao con caramelo: mezcla suave, baño María y enfriado completo, con nutrición estimada y ocho porciones propuestas.', summary='Flan de chocolate original con leche entera, huevo, cacao natural sin azúcar y caramelo. Ocho porciones propuestas y 6 horas totales, incluyendo enfriado y refrigeración; cantidades, rendimiento y tiempos pendientes de prueba de cocina.', category='Postres', category_slug='postres', difficulty='Media', course='Postre', cuisine='Casera', prep_time_minutes=25, cook_time_minutes=75, total_time_minutes=360, servings=8, ingredients=ingredients, steps=[{'title': title, 'content': content, 'image_url': prefix + f'paso-{i:02d}.webp', 'image_alt': 'Flan de chocolate: ' + title} for i, (title, content) in enumerate(steps, 1)], nutrition=nutrition, image_url=prefix+'portada.webp', gallery=[{'url':prefix+'portada.webp','alt':'Flan individual de chocolate con caramelo'}], published=False, editorial_status='ready', keywords=['flan de chocolate', 'cacao', 'caramelo', 'baño María'])
record['notes'] = 'Usa leche entera pasteurizada, huevo entero pesado sin cáscara y cacao natural sin azúcar; no equivale a chocoflan con bizcocho, flan instantáneo ni receta con leche condensada. Las sustituciones cambian cuajado y nutrición y requieren nuevas cantidades. Los 180 g de azúcar se reparten 60 g para caramelo y 120 g para mezcla; los 750 g de leche se reparten 150 g para cacao y 600 g para completar. Todo se incorpora y el caramelo se sirve; el agua externa del baño María no se consume. Caramelo caliente y agua del horno pueden causar quemaduras: usa guantes secos y mantén niños alejados. No pruebes huevo crudo. El centro debe superar 71°C y estar cuajado, no basta con el reloj; 80–85°C es objetivo de textura propuesto. La espera de 4 horas en frío está incluida en los 360 minutos propuestos. Refrigera a 4°C o menos dentro de los límites de 2 horas, o 1 hora por encima de 32°C. Las 8 porciones, tiempo y consumo dentro de 2 días son propuestas sin ensayo; no se afirma peso final. Contiene leche y huevo; revisa etiquetas. No incluye adornos ni afirmaciones de salud.'
record['seo'] = {'title': 'Flan de chocolate con cacao y caramelo: paso a paso', 'description': record['excerpt'], 'image_alt': 'Flan individual de chocolate de textura lisa con caramelo brillante en un plato blanco, sin bizcocho ni adornos', 'image_variants': [prefix+'portada-'+r+'.webp' for r in ['1x1','4x3','16x9']], 'faq': [
    {'q': '¿Por qué no está listo en una hora?', 'a': 'La cocción no es el tiempo total. Se proponen 25 minutos de preparación, 75 de cocción, 20 de enfriado y al menos 240 de refrigeración: 360 minutos. El precalentamiento se solapa con la preparación y no se cuenta dos veces; ajusta según la cocción real.'},
    {'q': '¿Puedo cambiar el cacao por chocolate o leche condensada?', 'a': 'Es otra fórmula. El cacao natural sin azúcar, la leche entera y los pesos indicados definen este cálculo y el cuajado. Chocolate en tableta, cacao azucarado o leche condensada cambian azúcar, grasa y textura; requieren cantidades y nutrición revisadas.'},
    {'q': '¿Cómo compruebo el cuajado y guardo los flanes?', 'a': 'Comprueba bordes firmes, centro que no esté líquido y al menos 71°C con termómetro limpio; el objetivo de textura propuesto es 80–85°C. Saca del baño María con protección, enfría brevemente y refrigera 4 horas a 4°C o menos. Consume en 2 días como propuesta prudente no ensayada y respeta los límites fuera del frío.'},
]}
record['content_html'] = '<p>'+html.escape(record['summary'])+'</p><p>'+html.escape(record['notes'])+'</p>'
steps_hash = hashlib.sha256(json.dumps(record['steps'], ensure_ascii=False, separators=(',', ':')).encode()).hexdigest()
sources = [
    {'url': 'https://www.gastronomiavasca.net/en/gastro/recipes/364', 'purpose': 'Primary culinary school: caramelised mould, chocolate custard and gentle waterbath technique only; no recipe text, quantities, images or nutrition copied.', 'accessed': '2026-10-08'},
    {'url': 'https://www.egginfo.co.uk/recipes/creme-caramel', 'purpose': 'Primary egg recipe publisher: custard handling and caramel technique cross-check; independently authored formula.', 'accessed': '2026-10-08'},
    {'url': 'https://www.foodsafety.gov/food-safety-charts/safe-minimum-internal-temperatures', 'purpose': 'Official eggdish minimum71C, food thermometer.', 'accessed': '2026-10-08'},
    {'url': 'https://www.foodsafety.gov/keep-food-safe/4-steps-to-food-safety', 'purpose': 'Official refrigeration and2h/1h limits; conservative2dayproposal nottested shelf life.', 'accessed': '2026-10-08'},
    {'url': 'https://fdc.nal.usda.gov/fdc-datasets/FoodData_Central_sr_legacy_food_json_2018-04.zip', 'purpose': 'Four exact FDC records/eight nutrient fields; archiveSHA256 checked against dataset.', 'accessed': '2026-10-08'},
]
package = {'scope':'Manual de Cocina only; lote03','state':'ES_FROZEN_MEDIA_AND_LOCALIZATIONS_PENDING','provenance':'Original editorial reconstruction; no WordPress text, translations or images reused','ai_owner_confirmation':'Original content and ImageGen authorized; no kitchen test claimed','category_slug':'postres','cover':prefix+'portada.webp','steps_frozen':True,'steps_sha256':steps_hash,'time_notes':'25prep+75cook+20cool+240refrigeration=360min;15preheat overlaps prep; actualbaking range50–70 and delays recorded','publication_blockers':['Originalmedia pending','Sixlocalizations pending','Full15CI/deploy/DB/cache/liveQA pending'],'sources':sources,'records':[record],'yield_proposal':{'portions':8,'measured':False}}
destination.write_text(json.dumps(package, ensure_ascii=False, indent=2)+'\n')
evidence = {'source_url':sources[-1]['url'],'dataset_sha256':'0fe8ae486a2c8eb42cb96413f058deb51863a46c8fb8eeb4b1fb45006dd338ef','verified_date':'2026-10-08','foods':[{'fdc_id':food_id, 'description':foods[str(food_id)]['description'], 'data_type':'SR Legacy','food_nutrients':foods[str(food_id)]['foodNutrients']} for _,_,food_id in selected]}
(root/'editorial'/f'{slug}-usda-verificado-20261008.json').write_text(json.dumps(evidence, ensure_ascii=False, indent=2)+'\n')
visuals = [
    'One smooth dark cocoa custard flan unmoulded on a plainwhite rimmedplate, translucent amber caramelpool overtop andaroundbase. Entireplate withincentre50percent, generousemptycounter for squareandwidecrops. No cake, cream, fruit,chocolate chips or garnish.',
    'Eight empty small roundwhite ceramic ramekins and separate bowls of wholemilk, whole eggs stillseparate, white sugar andnaturalcocoapowder; kitchen scales blankdisplay, thermometer. Cleanmiseenplace only no cookedflan.',
    'Clear amberhot sugarcaramel poured carefully fromsmall stainless saucepan intowhite ceramicramekin usingdryovenmitts, other emptyramekins nearby. No handtouchinghotcaramel, no addedcoldwater, no chocolateyet.',
    'Clean whisk stirs smoothbrowncocoaandwholemilk inasmall stainless saucepan atgentleheat, no boiling. Only milk/cocoaingredients, nocream,chocolatebar orcoffee.',
    'Cleanhands gentlywhisk yellowwholeegg andwhitesugar mixture incleanglassbowl, nomeringue orwhippedfoam, nogarnishes. Wholeeggcontents notshellsinmixture.',
    'Warmfluidcocoamilk pouredin thin stream intoyellowegg/sugarmixture whilecleanwhisk stirs; resultingmixture smoothmediumbrown, no scrambledlumps.',
    'Eight whiteceramicramekins containingfluidbrowncocoacustard overcaramel arranged indeepmetal ovenpan. Cleanjug pours hotclearwater BETWEEN ramekins upto halfway, never intocustard. Safeovenrack setupwithmitts.',
    'Eight small whiteceramicramekins withsetbrowncocoacustard in gentlewaterbath ovenpan; cleanfoodthermometer probe checks centre ofoneflan, screenunreadable. No boilingorrawrunnycustard andnoburnedcrust.',
    'Eight smallwhiteceramicramekins ofsmoothsetbrowncocoacustard onstablefridgeshelf incoveredshallow foodcontainer, transparent lid shows them. No waterbath in fridge, no garnish orcake.'
]
common = 'Photorealistic culinary editorial photograph, landscape4:3, same softlylit pale clean kitchen, consistent smoothwhiteceramicramekins and real chocolate EGG CUSTARD, notcake. No text,labels,logos,watermark,collage, healthclaims, extraingredients or dangeroushotliquidhandling. '
manifest = {'slug':slug,'recipe_group_id':record['recipe_group_id'],'date':'2026-10-08','steps_frozen':True,'steps_sha256':steps_hash,'directory':'public/recetas/'+slug+'/','image_source':'Built-in ImageGen; distinct original per phase, coverratios from sameoriginal','prompts':[{'asset':'portada.webp' if i==0 else f'paso-{i:02d}.webp','step':9 if i==0 else i,'prompt':common+v} for i,v in enumerate(visuals)],'images':[],'originals':[],'state':'FROZEN_BRIEF_IMAGES_PENDING','last_step_reuses_cover':True}
(root/'editorial'/f'{slug}-imagenes.json').write_text(json.dumps(manifest, ensure_ascii=False, indent=2)+'\n')
print(json.dumps({'slug':slug,'steps':9,'originals_pending':9,'webp_required':13,'steps_sha256':steps_hash,'nutrition':{k:v for k,v in nutrition.items()if isinstance(v,(int,float))},'state':package['state']}))
