"""Original home-style feijoada; source identity is preserved, no legacy body reused."""
import csv,hashlib,html,json,sys
from pathlib import Path
from editorial_nutrition import calculate
root=Path(__file__).resolve().parents[1]; slug='receta-de-feijoada'
assert not (root/f'editorial/{slug}-20261008.json').exists()
foods=[('alubias negras secas',500,173734),('paleta de cerdo fresca sin hueso',400,167843),('salchicha ahumada de cerdo completamente cocida',250,174584),('bacon crudo',100,168277),('cebolla',200,170000),('ajo',20,169230),('aceite de oliva',15,171413),('sal',4,173468),('pimienta negra',1,170931),('agua para cocción',2500,173647)]
n=calculate(sys.argv[1],foods,8)
n.update(serving_size='1 de 8 porciones de guiso, sin acompañamientos',method='Diez fichas USDA verificadas, pesos crudos comestibles para alubias, cerdo y bacon, y peso de la salchicha ya cocida; suma dividida entre 8. La salchicha ahumada se aproxima con la ficha genérica de salchicha ahumada de cerdo, no con una ficha específica de linguiça brasileña. Se cuenta toda la grasa y el caldo retenido. Laurel retirado y agua de remojo desechada no se incluyen.',note='Estimación informativa, no análisis del guiso terminado. Marca y sal de salchicha y bacon, remojo, rendimiento y reparto del caldo alteran las cifras. No se incluyen arroz, naranja, farofa ni verduras de acompañamiento.')
ing=[{'name':name,'amount':str(g),'unit':'ml' if i==9 else 'g','group':'Alubias y cocción' if i in [0,9] else 'Carnes' if i in [1,2,3] else 'Sofrito y sazón'} for i,(name,g,fdc) in enumerate(foods)]
ing.append({'name':'laurel seco, para retirar','amount':'2','unit':'hojas','group':'Sofrito y sazón'})
data=[
('Remoja las alubias en frío','Revisa los 500 g de alubias negras secas, retira piedrecitas o granos dañados y enjuaga. Ponlas en un recipiente amplio con aproximadamente 1,5 litros de agua, cubiertas por varios centímetros. Tapa y remoja 8 horas en la nevera a 4 °C o menos; si absorben el agua, añade más. Al terminar, desecha toda el agua de remojo y enjuaga. Ese agua es adicional a los 2,5 litros de cocción.'),
('Prepara ingredientes y separa el crudo','Pica los 200 g de cebolla y los 20 g de ajo sobre una tabla limpia. Corta los 400 g de paleta fresca sin hueso en dados de unos 3 cm y los 100 g de bacon en tiras cortas sobre otra tabla para carne cruda. Corta los 250 g de salchicha en rodajas de 1 cm; usa un producto cuyo envase indique que está completamente cocido, no salchicha fresca ni carne curada que precise desalado. Mantén las carnes en frío hasta cocinar y lava manos y utensilios tras manipular cerdo crudo.'),
('Hierve las alubias antes de bajar el fuego','Pon las alubias escurridas en una olla de al menos 6 litros con los 2,5 litros de agua fresca y las 2 hojas de laurel. Lleva a ebullición, unos 15 minutos orientativos, y mantén hervor claro durante al menos 30 minutos, sin tapa para controlar espuma y desbordamiento. Retira espuma con una cuchara; añade agua hirviendo si los granos dejan de estar cubiertos. No pruebes alubias crudas o duras ni sustituyas esta fase por una olla de cocción lenta.'),
('Dora las carnes y el sofrito','Durante el hervor, calienta una sartén amplia a fuego medio con los 15 g de aceite. Cocina el bacon unos 5 minutos, moviendo, hasta que empiece a dorarse. Añade el cerdo en dos tandas, unos 4 minutos cada una, solo para dorar la superficie; todavía debe terminar de cocinarse en el guiso. Retira las carnes a un plato reservado para ello. Sofríe la cebolla en la misma sartén 7 minutos, el ajo 1 minuto y la salchicha 4 minutos. Reserva todo el contenido, incluida la grasa: la estimación nutricional la cuenta completa.'),
('Cuece el guiso hasta que esté tierno','Tras los 30 minutos de hervor, incorpora a la olla carnes, salchicha, sofrito y jugos de la sartén, raspando con un poco de caldo caliente. Añade 1 g de pimienta; deja la sal para el final. Recupera un hervor suave y cocina unos 100 minutos con la tapa entreabierta, removiendo desde el fondo cada 15–20 minutos. Mantén alubias y carnes apenas cubiertas y añade agua hirviendo de 100 en 100 ml si hace falta. No dejes que se peguen; evita hervir tan fuerte que todas las alubias se deshagan.'),
('Comprueba cocción y textura','Comprueba con termómetro limpio el centro de varios dados de cerdo: se fija como objetivo práctico de este guiso al menos 74 °C, por encima del mínimo para cortes enteros. La carne debe además ceder fácilmente a la presión de un tenedor, y una alubia sacada con cuchara debe estar cremosa por dentro, sin núcleo duro. Si cualquiera sigue firme o falta temperatura, cocina más y vuelve a comprobar; los tiempos son una propuesta, no una garantía. No pruebes con utensilios que hayan tocado carne cruda.'),
('Espesa, sazona y deja reposar','Saca un cucharón de alubias ya blandas sin trozos de carne, aplástalas en un cuenco y devuelve la pasta a la olla. Cuece unos 15 minutos más a fuego suave, removiendo, hasta que el caldo cubra ligeramente el dorso de una cuchara; agrega agua hirviendo si está demasiado espeso. Retira las 2 hojas de laurel. Prueba solo ahora y añade los 4 g de sal previstos, o menos si los embutidos ya salan bastante; si usas menos, cambia la estimación de sodio. Apaga y deja reposar 10 minutos con la olla tapada.'),
('Reparte y conserva sin enfriar la olla entera','Reparte el guiso en 8 porciones con cantidades similares de alubias, carnes y caldo. Puedes acompañar con arroz, naranja o farofa, que no se incluyen en los ingredientes ni en la nutrición. Para guardar, divide pronto las sobras en recipientes pequeños y poco profundos y refrigera a 4 °C o menos dentro de 2 horas, o 1 hora si el ambiente supera 32 °C; no esperes a que toda la olla grande se enfríe fuera. Consume en 3–4 días o congela porciones; 2 meses es una propuesta de calidad. Descongela en la nevera y recalienta removiendo hasta al menos 74 °C en varios puntos.')]
steps=[{'title':t,'content':c,'image_url':'','image_alt':'Feijoada casera: '+t.lower()} for t,c in data]
summary='Esta propuesta casera de feijoada combina alubias negras, paleta de cerdo fresca, bacon y salchicha ahumada completamente cocida en un caldo oscuro que se espesa con parte de las propias alubias. Es una adaptación con ingredientes fáciles de identificar, sin carnes saladas que necesiten desalado; no pretende representar todas las variantes brasileñas.\n\nRinde 8 porciones de guiso. Los 680 minutos estimados incluyen 8 horas de remojo refrigerado, 30 de preparación, 160 de cocción y 10 de reposo. El sofrito se hace mientras hierven las alubias. Cantidades, rendimiento y tiempos están pendientes de confirmar mediante prueba de cocina; manda la ternura y la temperatura, no solo el reloj.'
excerpt='Feijoada casera para 8 con alubias negras, cerdo, bacon y salchicha ahumada: remojo, hervor inicial, guiso lento y conservación paso a paso.'
notes='Usa alubias negras secas, no sustituir por alubias cocidas manteniendo estos tiempos y cantidades. Esta versión no incluye carne seca, oreja ni pata de cerdo; incorporarlas requiere otro proceso y otro cálculo nutricional. La salchicha debe estar completamente cocida según su envase: ahumado no siempre significa cocido. Puede ser linguiça cocida o salchicha ahumada de cerdo equivalente; la marca cambia sabor y sodio. La paleta fresca no se desala. Para un caldo más ligero añade agua hirviendo; para espesar, aplasta alubias ya cocidas en vez de añadir harina. No añadas ingredientes ácidos antes de que las alubias estén tiernas. El reposo fuera del fuego no sustituye la refrigeración rápida de las sobras.'
r={'id':'baa74cdf-fb7d-4607-9cb1-0a4e135f81b6','recipe_group_id':'592ace5b-ac32-4d7d-91f4-09002a1456aa','slug':slug,'public_path':'/'+slug,'source_url':'https://manualdecocina.com/'+slug+'/','language':'es','title':'Feijoada casera de alubias negras y cerdo','excerpt':excerpt,'summary':summary,'category':'Platos principales','category_slug':'platos-principales','difficulty':'Media','course':'Plato principal','cuisine':'Brasileña, adaptación casera','prep_time_minutes':30,'cook_time_minutes':160,'total_time_minutes':680,'servings':8,'ingredients':ing,'steps':steps,'notes':notes,'nutrition':n,'keywords':['feijoada casera','feijoada de alubias negras','guiso de cerdo y alubias'],'image_url':None,'gallery':[],'seo':{'title':'Feijoada casera de alubias negras y cerdo','description':excerpt,'image_alt':'Feijoada de alubias negras en caldo oscuro con dados de cerdo, bacon y rodajas de salchicha ahumada','image_variants':[],'faq':[{'q':'¿Puedo saltarme el remojo?','a':'Esta propuesta parte de 8 horas de remojo refrigerado y agua nueva para cocinar. No se ofrece un tiempo equivalente sin remojo; cambia el proceso y no elimina el hervor inicial de 30 minutos.'},{'q':'¿Por qué las alubias siguen duras?','a':'Las alubias viejas, el agua dura o ingredientes ácidos tempranos pueden alargar la cocción. Mantén suficiente agua caliente y cocina hasta que no haya núcleo duro; añade la sal prevista al final.'},{'q':'¿Cómo espeso el caldo sin harina?','a':'Aplasta un cucharón de alubias blandas, sin carne, y devuélvelo al guiso. Cuece 15 minutos más a fuego suave, removiendo; si queda excesivamente espeso añade agua hirviendo.'}]},'published':False,'editorial_status':'draft','content_html':''.join('<p>'+html.escape(p)+'</p>' for p in summary.split('\n\n'))}
titles={'es':r['title'],'de':'Feijoada mit schwarzen Bohnen und Schweinefleisch','en':'Home-style black bean and pork feijoada','fr':'Feijoada maison aux haricots noirs et au porc','it':'Feijoada casalinga con fagioli neri e maiale','ja':'黒豆と豚肉の家庭風フェイジョアーダ','pt':'Feijoada caseira de feijão preto e porco'}
st={'es':[t for t,c in data],'de':['Bohnen gekühlt einweichen','Zutaten vorbereiten und Rohes trennen','Bohnen zuerst sprudelnd kochen','Fleisch und Zwiebeln anbraten','Eintopf weich köcheln lassen','Gargrad und Konsistenz prüfen','Andicken, würzen und ruhen lassen','Portionieren und rasch kühlen'],'en':['Soak the beans in the refrigerator','Prepare ingredients and separate raw meat','Boil the beans before lowering the heat','Brown the meat and aromatics','Simmer the stew until tender','Check temperature and tenderness','Thicken, season and rest','Portion and cool promptly'],'fr':['Faire tremper les haricots au froid','Préparer et séparer la viande crue','Faire bouillir les haricots avant de réduire le feu','Dorer les viandes et les aromates','Mijoter jusqu’à tendreté','Vérifier cuisson et texture','Épaissir, saler et laisser reposer','Partager et refroidir rapidement'],'it':['Ammolla i fagioli in frigorifero','Prepara e separa la carne cruda','Fai bollire i fagioli prima di abbassare il fuoco','Rosola carni e aromi','Cuoci lo stufato finché è tenero','Controlla temperatura e consistenza','Addensa, sala e lascia riposare','Porziona e raffredda rapidamente'],'ja':['豆を冷蔵庫で浸水する','材料を準備して生肉を分ける','火を弱める前に豆を沸騰させる','肉と香味野菜を炒める','柔らかくなるまで煮込む','温度と柔らかさを確認する','とろみをつけて味を調え休ませる','分けて速やかに冷蔵する'],'pt':['Deixe o feijão de molho na geladeira','Prepare os ingredientes e separe a carne crua','Ferva o feijão antes de baixar o fogo','Doure as carnes e o refogado','Cozinhe até ficar macio','Confira a temperatura e a textura','Engrosse, ajuste o sal e deixe descansar','Divida e refrigere rapidamente']}
covers={'es':r['seo']['image_alt'],'de':'Feijoada aus schwarzen Bohnen mit Schweinefleischwürfeln, Speck und geräucherten Wurstscheiben in dunkler Brühe','en':'Black bean feijoada with pork cubes, bacon and smoked sausage slices in dark broth','fr':'Feijoada de haricots noirs avec porc, lard et rondelles de saucisse fumée dans un bouillon sombre','it':'Feijoada di fagioli neri con maiale, pancetta e rondelle di salsiccia affumicata in brodo scuro','ja':'黒豆、豚肉、ベーコン、燻製ソーセージを黒い煮汁で煮たフェイジョアーダ','pt':'Feijoada de feijão preto com cubos de porco, bacon e rodelas de linguiça defumada em caldo escuro'}
alts={lang:{'title':t,'cover':covers[lang],'steps':[t+': '+s for s in st[lang]]} for lang,t in titles.items()}
scenes=[
'Soaking stage: a plain large glass bowl containing only dry black beans submerged beneath several centimetres of clear water on a clean refrigerator shelf. Beans intact, no cooked stew, meat or onion, lid beside bowl for visibility. Other food sealed and separate.',
'Preparation stage: separate small plain bowls of chopped white onion and finely minced garlic on a clean produce board; adjacent separate nonporous raw-meat board holds raw pork shoulder cubes about 3 cm and short raw bacon strips. Separate bowl of fully cooked smoked pork sausage cut into 1 cm rounds. No shared knives between raw meat and produce. Do not show assembled stew.',
'Initial boiling stage: a deep plain large stainless steel pot of intact black beans in darkening purple water, two bay leaves, visible full rolling boil with large bubbles and some natural pale foam, lid off. No pork, bacon, sausage or onion has been added yet. No slow cooker or pressure cooker.',
'Browning stage: a wide plain skillet with lightly browned pork cubes, small bacon strips, softened chopped onion, tiny garlic bits and smoked sausage rounds. Pork cubes are browned only on surfaces, not represented as a finished stew. No beans in this pan, no herbs or extra vegetables.',
'Slow simmer stage: a deep plain large pot containing black beans, roughly 3 cm pork chunks, smoked sausage rounds about 1 cm thick and short bacon pieces in dark purple-brown broth, a few small simmer bubbles, lid partly open at side. Beans and meat barely covered, no rice or extra vegetables in pot.',
'Doneness checking stage: a plain clean small plate holds a cooked opaque tender pork cube lifted from the stew, a plain food thermometer probe inserted in its centre with display unreadable. Beside it a spoon with a fully softened black bean split open revealing creamy cooked inside, no hard dry centre. Pot of dark black bean and pork stew softly behind. No pink raw pork, no readable numbers.',
'Thickening stage: a small plain bowl holding a ladleful of soft cooked black beans being mashed with a fork, thick dark bean paste, no meat in this bowl. Behind, a pot of black bean and pork stew with smoked sausage rounds; two removed bay leaves resting on small plate. No flour or cream, no extra garnish.'
]
visuals=['Alubias negras en remojo refrigerado con abundante agua.','Cebolla y ajo separados de dados de cerdo crudo, bacon y salchicha cocida cortada.','Alubias con laurel en hervor claro, aún sin carnes.','Carnes, cebolla, ajo y salchicha dorándose en sartén.','Alubias y carnes en caldo oscuro a hervor suave.','Temperatura del cerdo cocinado y alubia blanda comprobadas con utensilios limpios.','Alubias blandas aplastadas para espesar, laurel retirado.','Feijoada terminada con alubias negras, dados de cerdo, bacon y salchicha en caldo oscuro.']
base='Use case: photorealistic-natural. Asset type: original Manual de Cocina home-style feijoada recipe photograph. ONE realistic photograph, landscape 4:3, soft natural light, clean neutral kitchen, plain unbranded cookware, natural edible textures and realistic food safety stage. No text, label, logo, watermark, collage, parsley, garnish, carrots, tomato, pepper vegetables, cream, rice, orange or side dishes. '
cover=base+'Finished home-style feijoada served as one portion in a plain shallow ceramic bowl: glossy intact cooked black beans in thick dark purple-brown broth, tender opaque cooked pork shoulder cubes around 3 cm, short small cooked bacon pieces and smoked pork sausage rounds about 1 cm thick. The broth barely covers the beans and meat, thickened naturally with mashed beans, not a watery soup and not dry beans. No whole bay leaves in serving. Generous central framing margins for square, 4:3 and 16:9 responsive cover crops.'
h=hashlib.sha256(json.dumps(steps,ensure_ascii=False,sort_keys=True).encode()).hexdigest()
item={'category_slug':'platos-principales','cover':visuals[-1],'step_visuals':visuals,'ai_owner_confirmation':{'status':'delegated_editorial_authority','fields_are_estimated':['ingredients.amount','servings','prep_time_minutes','cook_time_minutes','total_time_minutes','nutrition'],'human_kitchen_confirmation':'not_performed'},'time_notes':'480 minutos de remojo + 30 de preparación + 160 de cocción (15 para llegar al hervor, 30 de hervor, 100 de guiso y 15 de espesado) + 10 de reposo = 680. Sofrito de 25 minutos paralelo al hervor. Ampliar si los granos o carnes siguen firmes.','steps_frozen':True,'steps_sha256':h,'publication_blockers':['FINAL_IMAGES_PENDING','FULL_LOCALIZATION_PENDING','BATCH_15_COMPLETION_PENDING','PREVIEW_QA_PENDING'],'image_alts_by_language':alts,'scope':'preview.manualdecocina.com','state':'ES_PREPARED_IMAGES_AND_LOCALIZATIONS_PENDING','provenance':'Original from preserved culinary identity. P2 classification REBUILD CANDIDATE verified; no legacy WordPress bodies, translations or images used. One unpublished ES identity, no duplicate group or prior new draft found. Historical five routes preserved; JA and PT-BR proposed without collisions. No kitchen test performed.','sources':[{'url':'https://www.fda.gov/food/chemical-contaminants-pesticides/natural-toxins-food','purpose':'Remojo y hervor inicial de alubias en agua nueva; aplicación conservadora del método a alubias negras.','accessed':'2026-10-08'},{'url':'https://www.foodsafety.gov/food-safety-charts/safe-minimum-internal-temperatures','purpose':'Termómetro, temperatura de cortes de cerdo y recalentado; objetivo de guiso 74 °C elegido por encima del mínimo.','accessed':'2026-10-08'},{'url':'https://www.foodsafety.gov/blog/leftovers-gift-keeps-giving','purpose':'Refrigeración pronta en recipientes poco profundos, conservación y recalentado.','accessed':'2026-10-08'},{'url':'https://fdc.nal.usda.gov/fdc-datasets/FoodData_Central_sr_legacy_food_csv_2018-04.zip','purpose':'Diez fichas verificadas; salchicha genérica como aproximación explícita, laurel retirado excluido.','accessed':'2026-10-08'}],'records':[r]}
manifest={'slug':slug,'recipe_group_id':r['recipe_group_id'],'date':'2026-10-08','steps_frozen':True,'steps_sha256':h,'directory':f'public/recetas/{slug}/','image_source':'built-in image generation; one call per distinct original; cover crops from same original','prompts':[{'asset':'portada.webp','step':8,'prompt':cover}]+[{'asset':f'paso-{i:02d}.webp','step':i,'prompt':base+s} for i,s in enumerate(scenes,1)],'images':[],'state':'GENERATION_PENDING','last_step_reuses_cover':True}
gsc=Path(sys.argv[2]);paths={'/receta-de-feijoada','/de/feijoada-rezept','/en/feijoada-recipe','/fr/recette-de-feijoada','/it/feijoada-ricetta'}
routes={'date':'2026-10-08','classification':'REBUILD_CANDIDATE_VALIDATED','classification_source':'docs/P2-CATALOG-20260924.md','historical_rows':[r for r in csv.DictReader(gsc.open()) if r['Path normalizado'] in paths],'source_matrix_sha256':hashlib.sha256(gsc.read_bytes()).hexdigest(),'new_proposed_paths':{'ja':'/ja/feijoada','pt':'/pt/feijoada'},'collision_check':{'recipes':'Only expected unpublished ES identity, no other feijoada group','content_pages':'No path or slug collisions across seven routes','content_redirects':'ES temporary catalogue fallback only; published recipe must serve HTTP200'},'decision':'Preserve all five historical paths and original ES ID/group/source URL; no redirect changes. Relevant P2 rebuild candidate, original home adaptation, no salted-meat desalting claims.'}
for name,obj in [(f'{slug}-20261008.json',item),(f'{slug}-imagenes.json',manifest),(f'{slug}-rutas-20261008.json',routes)]: (root/'editorial'/name).write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'slug':slug,'steps':len(steps),'nutrition':{k:v for k,v in n.items() if isinstance(v,(int,float))}}))
