"""Original oat, peanut and raisin bars; freeze Spanish before media."""
import csv,hashlib,html,json,sys
from pathlib import Path
from editorial_nutrition import calculate
root=Path(__file__).resolve().parents[1];slug='barras-de-cereal'
assert not (root/f'editorial/{slug}-20261008.json').exists()
foods=[('copos de avena secos',200,173904),('crema de cacahuete suave sin sal',100,172470),('miel',100,169640),('almendras',50,170567),('pasas oscuras sin semillas',50,168165),('semillas de girasol peladas',30,170562),('extracto de vainilla',3,173471),('sal',1,173468)]
n=calculate(sys.argv[1],foods,12)
n.update(serving_size='1 de 12 barras, unos 44 g antes de pérdidas de agua',method='Ocho fichas USDA verificadas por 100 g, ponderadas por los pesos de ingredientes y divididas entre 12. La ficha de avena corresponde a copos regulares o rápidos secos sin fortificar; no a avena cocida. Se supone crema de cacahuete sin sal y sin añadidos; el tostado no descuenta nutrientes del lote.',note='Estimación informativa, no análisis del producto preparado. Marca de la crema, tamaño de corte y restos de mezcla alteran el resultado. Las cifras incluyen toda la miel y no equivalen a una declaración de bajo contenido de azúcar.')
ingredients=[{'name':name,'amount':str(g),'unit':'g','group':'Mezcla seca' if i in (0,3,4,5) else 'Para ligar'} for i,(name,g,f) in enumerate(foods)]
steps_data=[
 ('Prepara el molde y pesa','Lávate las manos y limpia la superficie. Forra un molde cuadrado de 20 × 20 cm con papel de horno, dejando solapas para levantar la mezcla. Pesa los ingredientes y pica los 50 g de almendras en trozos de unos 5 mm; corta las pasas grandes para que no rompan las barras. Remueve la crema de cacahuete en su envase hasta integrar el aceite separado. Usa copos de avena aptos para este uso según su envase, no grano de avena entero.'),
 ('Tuesta la avena y las semillas','Calienta una sartén amplia y seca a fuego medio-bajo. Añade los 200 g de copos de avena, 50 g de almendras y 30 g de semillas de girasol. Remueve casi continuamente durante unos 8 minutos, hasta que desprendan aroma y tomen algo de color sin quemarse. Si se doran demasiado rápido, baja el fuego. Pasa a un cuenco grande y deja templar mientras preparas la mezcla ligante.'),
 ('Calienta la miel con la crema','Pon los 100 g de miel y 100 g de crema de cacahuete en un cazo. Calienta a fuego bajo unos 2 minutos, removiendo hasta que estén fluidos y uniformes, sin hervir ni caramelizar. Retira del fuego y añade los 3 g de vainilla y 1 g de sal. La mezcla caliente puede quemar; manéjala con una espátula, sin tocarla con los dedos.'),
 ('Integra las pasas y el ligante','Añade los 50 g de pasas al cuenco de avena templada. Vierte toda la mezcla de miel y cacahuete y remueve con una espátula durante 1–2 minutos, raspando fondo y paredes, hasta que cada copo esté recubierto y no queden bolsas secas. Debe ser una mezcla pegajosa que se aglomere al presionar con la espátula, no un líquido ni una masa batida.'),
 ('Compacta en una capa uniforme','Vuelca en el molde forrado y reparte hasta las esquinas. Coloca otra hoja de papel encima y presiona con la base plana de un vaso o una espátula durante 2–3 minutos. Busca una capa de alrededor de 1–1,5 cm sin huecos, especialmente en los bordes. La presión es importante para que las barras no se desmiguen; no añadas líquido para ablandarlas.'),
 ('Enfría y refrigera antes de cortar','Deja el molde unos 15 minutos a temperatura ambiente para perder el calor intenso. Tapa y refrigera a 4 °C o menos durante al menos 120 minutos, hasta que toda la placa esté firme y fría. El tiempo puede aumentar según la nevera y el grosor; no cortes mientras esté tibia. Los 165 minutos totales previstos incluyen este enfriado y la refrigeración.'),
 ('Corta doce barras','Levanta la placa fría por las solapas y colócala en una tabla limpia. Retira el papel superior y corta con un cuchillo grande en 3 filas y 4 columnas, obteniendo 12 barras de unos 6,7 × 5 cm. Presiona el cuchillo hacia abajo en lugar de serrar; limpia la hoja entre cortes si se pega. Si la placa se ablanda, vuelve a refrigerarla antes de continuar. Las migas se pueden servir aparte con yogur, sin contar ese añadido en la nutrición.'),
 ('Sirve y conserva en frío','Sirve las barras frías o deja templar solo la porción que vas a comer. Envuelve cada una o guarda en un recipiente cerrado con papel entre capas, a 4 °C o menos, hasta 5 días; respeta una indicación más corta de cualquiera de los ingredientes. Para congelar, envuelve individualmente hasta 1 mes y descongela en la nevera. Son duraciones propuestas, no un ensayo de vida útil. Se ablandan con calor y no se diseñaron para permanecer firmes durante horas fuera de la nevera.')
]
steps=[{'title':t,'content':c,'image_url':'','image_alt':'Barras de cereal: '+t.lower()} for t,c in steps_data]
summary='Estas barras de cereal combinan copos de avena tostados, almendras, semillas de girasol y pasas, ligados con miel y crema de cacahuete. Se compactan en un molde y se cortan después de enfriar; la placa no se hornea.\n\nLa propuesta rinde 12 barras blandas y compactas, no crujientes. Los 165 minutos estimados incluyen 10 de cocción, 15 de enfriado y al menos 120 en la nevera. Cantidades, firmeza, rendimiento y tiempos están pendientes de confirmar con una prueba de cocina.'
excerpt='Barras de cereal con avena, miel, cacahuete y pasas: cantidades para 12, tostado en sartén, compactado y enfriado antes de cortar, paso a paso.'
notes='Usa crema de cacahuete suave, sin sal y sin azúcar añadido; una muy líquida o con otra formulación cambia la firmeza. Puedes sustituir las pasas por la misma cantidad de albaricoque seco picado, pero cambiarán nutrición y textura. Cambiar la miel por otro jarabe o el cacahuete por otra crema requiere comprobar de nuevo el ligado y los alérgenos; no se promete el mismo resultado. Contiene cacahuete y almendras, y la avena puede tener contaminación con gluten: comprueba los envases si es relevante. Mantén las barras frías para transportarlas y no las presentes como alimento sin azúcar: llevan miel y fruta seca.'
r={'id':'9fb02391-f9aa-4dd1-bc03-eb8abe6a67f8','recipe_group_id':'b67728b9-bce4-4c97-b366-528cd318140a','slug':slug,'public_path':'/'+slug,'source_url':'https://manualdecocina.com/'+slug+'/','language':'es','title':'Barras de cereal con avena, miel y cacahuete','excerpt':excerpt,'summary':summary,'category':'Postres','category_slug':'postres','difficulty':'Fácil','course':'Merienda dulce','cuisine':'Internacional','prep_time_minutes':20,'cook_time_minutes':10,'total_time_minutes':165,'servings':12,'ingredients':ingredients,'steps':steps,'notes':notes,'nutrition':n,'keywords':['barras de cereal','barritas de avena y miel','barras de cacahuete y pasas'],'image_url':None,'gallery':[],'seo':{'title':'Barras de cereal con avena, miel y cacahuete','description':excerpt,'image_alt':'Barras rectangulares de avena con almendras, semillas y pasas visibles, sin chocolate ni cobertura','image_variants':[],'faq':[{'q':'¿Por qué se deshacen al cortarlas?','a':'La mezcla necesita suficiente presión y frío. Compacta también las esquinas y refrigera al menos 120 minutos, o más si sigue blanda. Una crema de cacahuete muy líquida y cortes tibios cambian el resultado.'},{'q':'¿Se hornean las barras?','a':'No se hornea la placa. Se tuestan avena, almendras y semillas en sartén y se calienta el ligante; después se compacta y se refrigera.'},{'q':'¿Puedo llevarlas sin refrigeración?','a':'Esta propuesta se conserva en frío y se ablanda con calor. Para transportarla usa un recipiente con acumulador de frío y saca solo la porción que vayas a comer; no se verificó estabilidad prolongada a temperatura ambiente.'}]},'published':False,'editorial_status':'draft','content_html':''.join('<p>'+html.escape(x)+'</p>' for x in summary.split('\n\n'))}
titles={'es':r['title'],'de':'Müsliriegel mit Hafer, Honig und Erdnuss','en':'Oat cereal bars with honey and peanut butter','fr':'Barres de céréales à l’avoine, miel et cacahuète','it':'Barrette di cereali con avena, miele e arachidi','ja':'オーツ麦と蜂蜜、ピーナッツのシリアルバー','pt':'Barras de cereal com aveia, mel e amendoim'}
st={'es':[t for t,c in steps_data],'de':['Form vorbereiten und Zutaten wiegen','Hafer und Kerne rösten','Honig und Erdnussmus erwärmen','Rosinen und Bindemischung einarbeiten','Gleichmäßig festdrücken','Abkühlen und vor dem Schneiden kühlen','Zwölf Riegel schneiden','Servieren und kalt aufbewahren'],'en':['Prepare the tin and weigh','Toast the oats and seeds','Warm the honey and peanut butter','Mix in the raisins and binder','Press into an even layer','Cool and refrigerate before cutting','Cut twelve bars','Serve and store chilled'],'fr':['Préparer le moule et peser','Torréfier l’avoine et les graines','Chauffer le miel et la purée de cacahuète','Ajouter les raisins et le liant','Tasser en couche régulière','Refroidir et réfrigérer avant de couper','Découper douze barres','Servir et conserver au froid'],'it':['Prepara lo stampo e pesa','Tosta avena e semi','Scalda miele e crema di arachidi','Unisci uvetta e legante','Compatta in uno strato uniforme','Raffredda prima di tagliare','Taglia dodici barrette','Servi e conserva al freddo'],'ja':['型を用意して材料を量る','オーツ麦と種を煎る','蜂蜜とピーナッツバターを温める','レーズンとつなぎを混ぜる','均一に押し固める','冷蔵してから切る','12本に切る','盛り付けて冷蔵保存する'],'pt':['Prepare a forma e pese','Toste a aveia e as sementes','Aqueça o mel e a pasta de amendoim','Misture as passas e o ligante','Compacte em uma camada uniforme','Esfrie e leve à geladeira antes de cortar','Corte doze barras','Sirva e conserve na geladeira']}
covers={'es':r['seo']['image_alt'],'de':'Rechteckige Haferriegel mit sichtbaren Mandeln, Kernen und Rosinen, ohne Überzug','en':'Rectangular oat cereal bars with visible almonds, sunflower seeds and raisins, without a coating','fr':'Barres rectangulaires d’avoine avec amandes, graines et raisins visibles, sans nappage','it':'Barrette rettangolari di avena con mandorle, semi e uvetta visibili, senza copertura','ja':'アーモンド、ひまわりの種、レーズンが見える長方形のオーツ麦バー','pt':'Barras retangulares de aveia com amêndoas, sementes e passas visíveis, sem cobertura'}
alts={lang:{'title':t,'cover':covers[lang],'steps':[t+': '+s for s in st[lang]]} for lang,t in titles.items()}
visuals=['Molde cuadrado forrado e ingredientes pesados separados; almendras picadas, pasas, avena y semillas.','Avena, almendras picadas y semillas tostándose juntas en sartén seca; sin miel ni pasas todavía.','Miel y crema de cacahuete suaves en cazo a fuego bajo, sin caramelo oscuro.','Avena, almendras, semillas y pasas recubiertas con mezcla ligante en un cuenco.','Mezcla compactada en molde cuadrado forrado con papel, presionada a través de otra hoja.','Placa completa tapada en molde forrado, enfriándose en nevera antes del corte.','Placa fría en tabla cortada en 3 filas y 4 columnas con cuchillo, 12 barras sin cobertura.','Barras de avena terminadas con almendras, semillas de girasol y pasas visibles, sin chocolate.']
scenes=[
 'Preparation phase: a square 20 cm metal baking tin lined with parchment and overhanging handles; separate bowls of plain rolled oats, chopped almonds in 5 mm pieces, dark seedless raisins, shelled sunflower seeds, smooth peanut butter and amber honey. Tiny vanilla and salt dishes. No mixed dough, shaped bars or chocolate. Ingredients separated clearly.',
 'Toasting phase: a wide dry frying pan on low-medium heat holding plain rolled oats, small chopped almond pieces and shelled sunflower seeds only, lightly golden not burned, a wooden spatula gently resting on the mixture. No raisins, honey, peanut butter or finished bars in the pan.',
 'Binder phase: a small plain saucepan with a smooth glossy tan mixture of honey and peanut butter at low heat, a silicone spatula resting inside. No dark burnt caramel, bubbling boil, oats, nuts, raisins or cereal bars in the saucepan.',
 'Mixing phase: a large glass bowl with rolled oats, chopped almonds, sunflower seeds and dark raisins completely coated in a sticky light tan honey-peanut binder. A spatula folding the coarse mixture. Whole ingredients visible, not a smooth blended dough. No shaped bars or chocolate.',
 'Pressing phase: sticky coarse oat-almond-sunflower-raisin mixture in a square parchment-lined 20 cm metal tin, being pressed firmly through a top parchment sheet with the flat bottom of a plain glass, one anatomically correct hand. Half of the upper parchment lifted to show an evenly compacted approximately 1 cm slab. No cut bars yet.',
 'Chilling phase: square parchment-lined 20 cm metal tin holding a single uncut compact oat-raisin slab covered with transparent food-safe film, resting on a clean refrigerator shelf. Rolled oats, chopped almonds, sunflower seeds and dark raisins visible through cover. No knife, cut bars or raw egg.',
 'Cutting phase: cold square oat-raisin slab lifted out of its tin onto a clean cutting board with parchment underneath. The slab is neatly cut into exactly 3 rows and 4 columns, twelve rectangular pieces, one slightly pulled away to show the cut edges. A large plain kitchen knife safely resting beside the slab, no hands, chocolate or coating.'
]
base='Use case: photorealistic-natural. Asset type: original Manual de Cocina cereal bar recipe photograph. One single realistic photo, 4:3 landscape composition, soft natural window light, light neutral clean kitchen, simple unbranded utensils. Natural coarse edible textures and accurate phases. No text, watermark, logo, collage, extra ingredients, chocolate, coconut, coloured sprinkles or sugar dusting. '
cover=base+'Finished oat cereal bars: six compact rectangular bars about 6.7 by 5 cm and around 1 to 1.5 cm thick on a plain off-white plate. Rolled oat flakes, small chopped almond pieces, shelled sunflower seeds and dark raisins clearly visible, bound with light tan honey-peanut butter. Natural dense chewy texture, not loose granola, not crumbly cereal, not a frosted cake. Some bars slightly overlapped, one close cut edge in focus. No drizzle or coating. Centre the composition with generous margins for square, 4:3 and 16:9 responsive crops.'
h=hashlib.sha256(json.dumps(steps,ensure_ascii=False,sort_keys=True).encode()).hexdigest()
item={'category_slug':'postres','cover':visuals[-1],'step_visuals':visuals,'ai_owner_confirmation':{'status':'delegated_editorial_authority','fields_are_estimated':['ingredients.amount','servings','prep_time_minutes','cook_time_minutes','total_time_minutes','nutrition'],'human_kitchen_confirmation':'not_performed'},'time_notes':'20 minutos activos + 8 de tostado + 2 de calentado + 15 de enfriado + 120 de refrigeración = 165 minutos propuestos; aumentar si la placa no está firme.','steps_frozen':True,'steps_sha256':h,'publication_blockers':['FINAL_IMAGES_PENDING','FULL_LOCALIZATION_PENDING','BATCH_15_COMPLETION_PENDING','PREVIEW_QA_PENDING'],'image_alts_by_language':alts,'scope':'preview.manualdecocina.com','state':'ES_PREPARED_IMAGES_AND_LOCALIZATIONS_PENDING','provenance':'Propuesta original de barras culinarias de avena, miel y cacahuete, con pasas y semillas. Candidato de cola vigente revisado contra exclusiones y clasificación, sin duplicado ni alegaciones saludables. No se usa contenido ni imágenes WordPress. Guía primaria informa principios de tostado, ligado, compactado y frío; cantidades y textos propios. Sin prueba de cocina.','sources':[{'url':'https://www.canada.ca/en/health-canada/services/food-guide/eating-support/kitchen/recipes/no-bake-toasted-oat-granola-bars.html','purpose':'Principios culinarios de tostar copos, calentar miel y crema, compactar y enfriar. Receta propia sin dátiles ni copos de salvado; no copiar cantidades ni alegaciones saludables.','accessed':'2026-10-08'},{'url':'https://fdc.nal.usda.gov/fdc-datasets/FoodData_Central_sr_legacy_food_csv_2018-04.zip','purpose':'Ocho fichas USDA verificadas para cálculo ponderado por ración.','accessed':'2026-10-08'}],'records':[r]}
manifest={'slug':slug,'recipe_group_id':r['recipe_group_id'],'date':'2026-10-08','steps_frozen':True,'steps_sha256':h,'directory':f'public/recetas/{slug}/','image_source':'built-in image generation; one call per distinct original; cover crops from same original','prompts':[{'asset':'portada.webp','step':8,'prompt':cover}]+[{'asset':f'paso-{i:02d}.webp','step':i,'prompt':base+s} for i,s in enumerate(scenes,1)],'images':[],'state':'GENERATION_PENDING','last_step_reuses_cover':True}
gsc=Path(sys.argv[2]); paths={'/barras-de-cereal','/de/musliriegel','/en/cereal-bars','/fr/barres-de-cereales','/it/barrette-di-cereali'}
rows=[r for r in csv.DictReader(gsc.open()) if r['Path normalizado'] in paths]
routes={'date':'2026-10-08','classification':'CULINARY_QUEUE_CANDIDATE_VALIDATED','classification_sources':['editorial/automation-queue.json','docs/CATALOG-FINAL-V1-20260924.md','docs/P4-CLOSEOUT-20260924.md'],'historical_rows':rows,'source_matrix_sha256':hashlib.sha256(gsc.read_bytes()).hexdigest(),'new_proposed_paths':{'ja':'/ja/oat-cereal-bars','pt':'/pt/barras-de-cereal'},'collision_check':{'recipes':'Only preserved ES identity; no other cereal/granola/muesli group','content_pages':'No seven-route or slug collisions','content_redirects':'ES temporary catalogue fallback only; recipe resolver takes precedence; verify HTTP200 after publication'},'decision':'Preserve candidate classification. Relevant original sweet culinary preparation, no duplicate, archive, REVIEW, OUT or health entity found in current queue/documents. User authorized eligible candidates; no classification rewrite or rejected content revived. Proposed category postres because canonical taxonomy has no snack category.'}
for name,obj in [(f'{slug}-20261008.json',item),(f'{slug}-imagenes.json',manifest),(f'{slug}-rutas-20261008.json',routes)]: (root/'editorial'/name).write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'slug':slug,'steps':len(steps),'nutrition':{k:v for k,v in n.items() if isinstance(v,(int,float))}}))
