"""Original alfajores proposal, preserved identity and verified USDA inputs."""
import csv, hashlib, html, json, sys
from pathlib import Path
from editorial_nutrition import calculate
root = Path(__file__).resolve().parents[1]
slug = 'receta-de-alfajores-de-maicena'
destination = root / f'editorial/{slug}-20261008.json'
assert not destination.exists(), 'Never replace a frozen editorial package'
foods = [('almidón de maíz',200,169698),('harina de trigo de todo uso',100,168936),('mantequilla sin sal',100,173430),('azúcar blanco',80,169655),('yemas de huevo',51,172184),('polvo de hornear de doble acción',6,172804),('extracto de vainilla',5,173471),('ralladura de limón',3,167749),('dulce de leche',350,173461),('coco rallado seco sin azúcar',30,170170)]
n = calculate(sys.argv[1], foods, 20)
n.update(serving_size='1 de 20 alfajores',method='Suma de diez fichas USDA verificadas por 100 g, ponderadas por los pesos de todos los ingredientes y dividida entre 20. Se incluyen todo el relleno y el coco previstos; la pérdida de agua durante el horneado no se descuenta del aporte total.',note='Estimación informativa, no análisis del alfajor preparado. Las marcas de dulce de leche, mantequilla y polvo de hornear cambian el resultado. Se supone que toda la masa, el relleno y el coco se consumen; restos en utensilios reducirían el aporte real.')
ingredients = [{'name': name,'amount':str(g),'unit':'g','group':'Masa' if i<8 else 'Relleno y acabado'} for i,(name,g,fdc) in enumerate(foods)]
ingredients[4]['name']='yemas de huevo, unas 3 grandes; pesar 51 g'
step_data = [
 ('Pesa y tamiza los ingredientes secos','Lávate las manos y limpia la superficie. Pesa todos los ingredientes; las 3 yemas deben sumar unos 51 g. Tamiza juntos los 200 g de almidón de maíz, 100 g de harina y 6 g de polvo de hornear en un cuenco. Lava el limón antes de rallar solo la parte amarilla hasta obtener 3 g. Mantén el dulce de leche y el coco separados de los utensilios que tocarán masa cruda.'),
 ('Bate la mantequilla y añade las yemas','Usa los 100 g de mantequilla blanda, que ceda al presionarla pero no esté derretida. Bátela con los 80 g de azúcar durante 2–3 minutos hasta que quede cremosa. Incorpora las yemas en tres adiciones, batiendo hasta integrar cada una. Añade los 5 g de vainilla y los 3 g de ralladura; raspa las paredes del cuenco con una espátula.'),
 ('Forma la masa y enfría','Añade los ingredientes secos en dos tandas. Mezcla con espátula y termina juntando suavemente con las manos, solo hasta que no queden zonas de polvo; no amases como pan. Aplana la masa en un disco, envuelve y refrigera 30 minutos a 4 °C o menos. No pruebes masa cruda: contiene harina y huevo sin cocinar. Lava manos, cuenco y superficie después de manipularla.'),
 ('Estira y corta cuarenta discos','Precalienta el horno a 180 °C con calor arriba y abajo, o 160 °C con ventilador. Forra dos bandejas de unos 30 × 40 cm con papel de horno. Estira la masa entre dos hojas de papel hasta unos 6 mm de grosor. Corta círculos de 5 cm de diámetro; junta los recortes sin amasar mucho y vuelve a estirar. Busca 40 discos de tamaño similar, unos 13–14 g de masa cada uno, para formar 20 parejas. Reparte 20 por bandeja con unos 2 cm de separación. Si la masa se ablanda, enfría 10 minutos y añade esa espera al tiempo total.'),
 ('Hornea las tapas en dos tandas','Hornea una bandeja cada vez en la zona central durante 12–15 minutos: la superficie debe estar mate y firme y la base apenas dorada, sin un centro húmedo. Empieza a revisar a los 12 minutos; el grosor y el horno pueden cambiar el tiempo. Retira con guantes y hornea la segunda bandeja del mismo modo. El cálculo de cocción reserva 30 minutos para las dos tandas; no busques un color tostado intenso.'),
 ('Deja enfriar por completo','Deja las tapas 5 minutos en su bandeja porque aún son frágiles. Pásalas con una espátula ancha a una rejilla y enfría unos 25 minutos más, hasta que estén completamente frías. No pongas relleno en tapas tibias: el dulce de leche se ablandaría y las galletas se romperían con más facilidad.'),
 ('Rellena y cubre el borde con coco','Empareja las 40 tapas por tamaño y coloca una de cada pareja con la base hacia arriba. Reparte los 350 g de dulce de leche espeso entre las 20 bases, unos 17–18 g por alfajor, con una cuchara o manga limpia. Cubre con la segunda tapa y presiona suavemente hasta que el relleno asome apenas. Pon los 30 g de coco en un plato y rueda solo el borde de cada alfajor para que se adhiera al relleno.'),
 ('Sirve y guarda los alfajores','Sirve los 20 alfajores cuando el relleno esté asentado y manipúlalos con cuidado. Guárdalos en un recipiente cerrado, separados por papel, en la nevera a 4 °C o menos y consúmelos dentro de 3 días, o antes si lo indica el envase del dulce de leche. Para congelar, envuelve individualmente hasta 1 mes y descongela en la nevera. Estas duraciones son una propuesta conservadora, no un ensayo de vida útil; el coco y las tapas se ablandarán con el tiempo.')
]
steps=[{'title':t,'content':c,'image_url':'','image_alt':'Alfajores de maicena: '+t.lower()} for t,c in step_data]
summary='Estos alfajores de maicena se forman con dos tapas tiernas de almidón de maíz y harina, relleno de dulce de leche y coco solo en el borde. La ralladura de limón y la vainilla aromatizan una masa con yemas.\n\nLa propuesta rinde 20 alfajores de unos 5 cm: 40 tapas de 6 mm, horneadas en dos tandas. Los 130 minutos estimados incluyen 30 minutos de frío y 30 de enfriado; cantidades, rendimiento y tiempos están pendientes de confirmar mediante prueba de cocina.'
excerpt='Alfajores de maicena con dulce de leche y coco: cantidades para 20 unidades, masa con yemas, reposo en frío y horneado de las tapas paso a paso.'
notes='Usa almidón de maíz blanco, no harina de maíz amarilla. El dulce de leche debe ser espeso, preferiblemente de repostería; uno líquido se saldrá del borde. Puedes omitir el coco, aunque cambiarán acabado y nutrición. No se propone una sustitución sin gluten sin probarla: esta masa lleva trigo. Si se agrieta al estirar, deja que pierda algo de frío unos minutos y presiona suavemente entre papeles; no añadas harina sin medir. Contiene trigo, huevo y leche. Evita probar masa cruda y limpia antes de manipular las tapas ya horneadas.'
record={'id':'669e4cf8-2a80-4cf2-8c5e-e13f78796117','recipe_group_id':'c934c115-46a8-4009-ae75-fb10bd3d184f','slug':slug,'public_path':'/'+slug,'source_url':'https://manualdecocina.com/'+slug+'/','language':'es','title':'Alfajores de maicena con dulce de leche y coco','excerpt':excerpt,'summary':summary,'category':'Postres','category_slug':'postres','difficulty':'Media','course':'Postre','cuisine':'Argentina','prep_time_minutes':40,'cook_time_minutes':30,'total_time_minutes':130,'servings':20,'ingredients':ingredients,'steps':steps,'notes':notes,'nutrition':n,'keywords':['alfajores de maicena','alfajores con dulce de leche','galletas rellenas con coco'],'image_url':None,'gallery':[],'seo':{'title':'Alfajores de maicena con dulce de leche y coco','description':excerpt,'image_alt':'Alfajores de maicena claros con dulce de leche y coco en el borde, uno partido mostrando el relleno','image_variants':[],'faq':[{'q':'¿Por qué se rompen las tapas?','a':'Son frágiles al salir del horno. Déjalas 5 minutos en la bandeja, muévelas con una espátula ancha y espera a que estén totalmente frías para rellenar. Amasar demasiado o estirar muy fino también cambia la textura.'},{'q':'¿Puedo usar harina de maíz en lugar de maicena?','a':'No como sustitución directa. Esta receta usa almidón de maíz blanco; la harina de maíz amarilla tiene otra composición y textura. La receta también contiene harina de trigo.'},{'q':'¿Qué hago si el dulce de leche está muy líquido?','a':'Usa un dulce de leche espeso de repostería para que sostenga las tapas. No rellenes con las galletas calientes. Cambiar de relleno puede alterar consistencia, conservación y nutrición.'}]},'published':False,'editorial_status':'draft','content_html':''.join('<p>'+html.escape(p)+'</p>' for p in summary.split('\n\n'))}
titles={'es':record['title'],'de':'Maisstärke-Alfajores mit Dulce de Leche und Kokos','en':'Cornstarch alfajores with dulce de leche and coconut','fr':'Alfajores à la fécule de maïs, dulce de leche et coco','it':'Alfajores all’amido di mais con dulce de leche e cocco','ja':'ドゥルセ・デ・レチェとココナッツのアルファホーレス','pt':'Alfajores de amido de milho com doce de leite e coco'}
step_titles={
 'es':[t for t,c in step_data],
 'de':['Trockene Zutaten wiegen und sieben','Butter aufschlagen und Eigelb einarbeiten','Teig formen und kühlen','Vierzig Teigkreise ausstechen','Kekse in zwei Durchgängen backen','Vollständig auskühlen lassen','Füllen und Rand in Kokos wenden','Servieren und aufbewahren'],
 'en':['Weigh and sift the dry ingredients','Cream the butter and add the yolks','Bring the dough together and chill','Roll and cut forty rounds','Bake the cookies in two batches','Cool completely','Fill and coat the edges in coconut','Serve and store'],
 'fr':['Peser et tamiser les ingrédients secs','Crémer le beurre et ajouter les jaunes','Former et refroidir la pâte','Étaler et découper quarante disques','Cuire les biscuits en deux fournées','Laisser refroidir complètement','Garnir et rouler les bords dans la noix de coco','Servir et conserver'],
 'it':['Pesa e setaccia gli ingredienti secchi','Lavora il burro e aggiungi i tuorli','Forma e raffredda l’impasto','Stendi e ritaglia quaranta dischi','Cuoci i biscotti in due infornate','Lascia raffreddare completamente','Farcisci e ricopri i bordi di cocco','Servi e conserva'],
 'ja':['粉類を量ってふるう','バターに卵黄を加える','生地をまとめて冷やす','生地をのばして40枚抜く','2回に分けて焼く','完全に冷ます','詰めて側面にココナッツをつける','盛り付けて保存する'],
 'pt':['Pese e peneire os ingredientes secos','Bata a manteiga e acrescente as gemas','Junte a massa e leve à geladeira','Abra e corte quarenta discos','Asse os biscoitos em duas fornadas','Deixe esfriar completamente','Recheie e cubra a borda com coco','Sirva e guarde']}
covers={'es':record['seo']['image_alt'],'de':'Helle Maisstärke-Alfajores mit Dulce de Leche und Kokosrand, eines geöffnet mit sichtbarer Füllung','en':'Pale cornstarch alfajores filled with dulce de leche and coconut-coated edges, one broken open','fr':'Alfajores clairs garnis de dulce de leche, bords à la noix de coco, un biscuit ouvert','it':'Alfajores chiari con dulce de leche e bordi al cocco, uno aperto con ripieno visibile','ja':'淡い色のアルファホーレスとドゥルセ・デ・レチェの断面、側面のココナッツ','pt':'Alfajores claros com doce de leite e coco na borda, um partido mostrando o recheio'}
alts={lang:{'title':t,'cover':covers[lang],'steps':[t+': '+x for x in step_titles[lang]]} for lang,t in titles.items()}
visuals=['Almidón, harina y polvo de hornear tamizados en cuenco; ingredientes pesados separados.','Mantequilla y azúcar cremosos con yemas incorporadas, vainilla y ralladura en cuenco.','Disco de masa pálida envuelto listo para refrigerar, sin alfajores hechos.','Masa de 6 mm cortada en discos de 5 cm sobre papel, cortador redondo y bandeja sin hornear.','Tapas claras recién horneadas con base apenas dorada sobre bandeja, sin relleno.','Tapas horneadas separadas enfriando en rejilla, sin dulce de leche.','Tapas frías con dulce de leche, segunda tapa al lado y borde rodado en coco rallado.','Alfajores terminados con dos tapas pálidas, dulce de leche espeso visible y coco solo en el borde.']
scenes=[
 'Preparation phase: separate plain small bowls of weighed white cornstarch, white wheat flour and baking powder beside a large bowl with the sifted white dry mixture and a fine sieve. Other accurately separated ingredients nearby: soft butter, white sugar, a bowl of three egg yolks, tiny vanilla and fine yellow lemon zest. No dough, baked cookies or filling visible yet. No ingredient labels or readable numbers.',
 'Mixing phase: a glass mixing bowl containing pale yellow creamed butter, sugar and incorporated egg yolks, a silicone spatula resting inside, tiny yellow lemon zest flecks visible. An unbranded handheld mixer with beaters safely resting switched off beside the bowl. No dry dough, baked cookies, coconut or caramel filling yet.',
 'Chilling phase: a single pale yellow shortbread dough disk wrapped fully in transparent food-safe plastic wrap on a plain plate, ready to go into a refrigerator. Slightly flat disk, smooth but natural edges. No cookie discs, filling, baked pastries or extra ingredients.',
 'Cutting phase: pale raw shortbread dough rolled about 6 mm thick between parchment, top parchment removed. A plain round 5 cm metal cutter, several cut raw circular dough discs, dough scrap area and rolling pin. Unbaked discs on a parchment-lined tray nearby with gaps. No filling, coconut or completed alfajores.',
 'Baking phase: a parchment-lined metal tray of separate pale round 5 cm baked shortbread cookie discs, matte firm tops and just faintly golden edges. One disc lifted with a broad spatula shows a very lightly golden underside. No caramel filling, coconut, burnt brown cookies or finished sandwich cookies.',
 'Cooling phase: separate pale 5 cm baked shortbread cookie discs cooling on a plain wire rack, not stacked, no filling or coconut yet. Matte dry pale tops with subtly golden base edges. Light neutral kitchen counter.',
 'Assembly phase: cold pale shortbread discs, several lower discs topped with thick caramel-brown dulce de leche, matching upper discs nearby. One assembled sandwich cookie has its edge being gently rolled in a shallow dish of finely grated unsweetened white coconut by anatomically correct hands. Coconut only on caramel edge, not sprinkled on cookie tops. No powdered sugar or chocolate.'
]
base='Use case: photorealistic-natural. Asset type: one original Manual de Cocina recipe photograph. A single realistic food photo in 4:3 landscape framing, soft natural window light, clean light neutral kitchen counter, plain unbranded utensils. Precise edible textures, no text, logo, label, watermark, collage, extra ingredients, chocolate, sprinkles or powdered-sugar dusting. '
cover=base+'Finished cornstarch alfajores: six small 5 cm sandwich cookies on a simple matte off-white plate, each made of TWO pale tender round shortbread discs around a generous thick caramel-brown dulce de leche layer. Finely grated white coconut adheres only around the exposed filling edge. One cookie is broken into two pieces to show the tender interior and actual filling cross-section. Natural pale baked tops, not browned or chocolate-coated. Clean crumb detail. Composition centred with generous crop margins for square, 4:3 and 16:9 variants. No raw dough, hand or ingredient bowls.'
frozen=hashlib.sha256(json.dumps(steps,ensure_ascii=False,sort_keys=True).encode()).hexdigest()
item={'category_slug':'postres','cover':visuals[-1],'step_visuals':visuals,'ai_owner_confirmation':{'status':'delegated_editorial_authority','fields_are_estimated':['ingredients.amount','servings','prep_time_minutes','cook_time_minutes','total_time_minutes','nutrition'],'human_kitchen_confirmation':'not_performed'},'time_notes':'40 minutos activos + 30 de refrigeración + 30 para dos tandas de horno + 30 de enfriado = 130; una refrigeración adicional al cortar se suma si hace falta.','steps_frozen':True,'steps_sha256':frozen,'publication_blockers':['FINAL_IMAGES_PENDING','FULL_LOCALIZATION_PENDING','BATCH_15_COMPLETION_PENDING','PREVIEW_QA_PENDING'],'image_alts_by_language':alts,'scope':'preview.manualdecocina.com','state':'ES_PREPARED_IMAGES_AND_LOCALIZATIONS_PENDING','provenance':'Propuesta original de alfajor de maicena con yemas. Identidad REBUILD CANDIDATE validada contra P2, cola autorizada, rutas GSC y ausencia de otra entidad. No se leyeron cuerpos ni imágenes WordPress. Cantidades, pasos y textos propios; fuentes primarias solo para identidad culinaria general, técnica y seguridad. Sin prueba de cocina.','sources':[{'url':'https://www.goodnes.com/la-lechera/recipes/cornstarch-alfajores/','purpose':'Identidad de alfajores de almidón rellenos de dulce de leche y principio de enfriar antes de rellenar; no se copian receta ni cantidades.','accessed':'2026-10-08'},{'url':'https://www.fda.gov/food/buy-store-serve-safe-food/handling-flour-safely-what-you-need-know','purpose':'Harina y huevo crudos: no probar masa, cocinar y limpiar.','accessed':'2026-10-08'},{'url':'https://fdc.nal.usda.gov/fdc-datasets/FoodData_Central_sr_legacy_food_csv_2018-04.zip','purpose':'Diez fichas USDA verificadas para cálculo nutricional reproducible.','accessed':'2026-10-08'}],'records':[record]}
manifest={'slug':slug,'recipe_group_id':record['recipe_group_id'],'date':'2026-10-08','steps_frozen':True,'steps_sha256':frozen,'directory':f'public/recetas/{slug}/','image_source':'built-in image generation; one call per distinct original; cover crops from same original','prompts':[{'asset':'portada.webp','step':8,'prompt':cover}]+[{'asset':f'paso-{i:02d}.webp','step':i,'prompt':base+s} for i,s in enumerate(scenes,1)],'images':[],'state':'GENERATION_PENDING','last_step_reuses_cover':True}
gsc=Path(sys.argv[2]); rows=[r for r in csv.DictReader(gsc.open()) if 'alfajor' in r['Path normalizado']]
routes={'date':'2026-10-08','classification':'REBUILD_CANDIDATE_VALIDATED','classification_sources':['docs/P2-CATALOG-20260924.md','editorial/automation-queue.json'],'historical_rows':rows,'source_matrix_sha256':hashlib.sha256(gsc.read_bytes()).hexdigest(),'new_proposed_paths':{'ja':'/ja/cornstarch-alfajores','pt':'/pt/alfajores-de-amido-de-milho'},'collision_check':{'checked_at':'2026-10-08','recipes':'ES identity only; no second alfajores group','content_pages':'no rows on seven routes','content_redirects':'ES 302 to /es/recetas only; published recipe resolver precedes fallback; direct HTTP200 still required after publication'},'decision':'Eligible original culinary recipe with one preserved ES entity, no archived/health/merge disposition found. Preserve historical five routes and add collision-free JA/PT-BR. No redirects changed.'}
for name,obj in [(f'{slug}-20261008.json',item),(f'{slug}-imagenes.json',manifest),(f'{slug}-rutas-20261008.json',routes)]: (root/'editorial'/name).write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'slug':slug,'steps':len(steps),'nutrition':{k:v for k,v in n.items() if isinstance(v,(int,float))}}))
