"""Original four-portion chicken, avocado and mango salad with temperature gate."""
import csv,hashlib,html,json,sys
from pathlib import Path
from editorial_nutrition import calculate
root=Path(__file__).resolve().parents[1];slug='ensalada-de-pollo-con-aguacate-y-mango'
assert not (root/f'editorial/{slug}-20261008.json').exists()
foods=[('pechuga de pollo cruda sin piel ni hueso',600,171077),('aguacate, pulpa',200,171705),('mango, pulpa',250,169910),('pepino con piel',150,168409),('lechuga romana',100,169247),('cebolla roja',40,170000),('zumo de lima',40,168156),('aceite de oliva',30,171413),('miel',10,169640),('sal',3,173468),('pimienta negra',1,170931)]
n=calculate(sys.argv[1],foods,4)
n.update(serving_size='1 de 4 porciones',method='Once fichas USDA verificadas por 100 g, ponderadas por los pesos comestibles indicados y divididas entre 4. Pollo calculado por 600 g crudos sin piel ni hueso; cebolla roja aproximada con la ficha de cebolla cruda genérica. Se cuentan los 30 g de aceite y todo el aliño, aunque puedan quedar restos en sartén o cuenco.',note='Estimación informativa, no análisis de la ensalada preparada. Pérdidas de jugos al cocinar, variedad de fruta, aceite retenido y reparto alteran el resultado. No se cuenta pan ni ningún acompañamiento adicional.')
ing=[{'name':name,'amount':str(g),'unit':'g','group':'Ensalada' if i<6 else 'Cocción y aliño'} for i,(name,g,fdc) in enumerate(foods)]
step_data=[
 ('Lava y seca los vegetales','Lávate las manos y prepara una tabla limpia para fruta y verdura, separada de la del pollo. Lava pepino, mango, aguacate y lima bajo agua corriente antes de cortar o pelar, sin jabón. Lava y seca bien los 100 g de lechuga, salvo que el envase indique que está lista para comer. Corta los 150 g de pepino en medias lunas finas y los 40 g de cebolla roja en pluma; reserva con la lechuga en la nevera mientras cocinas.'),
 ('Prepara cuatro filetes de pollo','No laves el pollo crudo. Sobre su tabla separada, divide los 600 g de pechuga sin piel ni hueso en cuatro filetes de unos 150 g y grosor uniforme de aproximadamente 1,5 cm. Si hace falta, aplana suavemente entre papeles aptos para alimentos. Sazona con 1 g de la sal y 0,5 g de pimienta. Desecha el papel usado y lava manos y utensilios; no pongas la ensalada ni el pollo cocinado sobre la tabla o plato del pollo crudo.'),
 ('Cocina y comprueba la temperatura','Calienta una sartén amplia a fuego medio con 5 g de aceite. Cocina dos filetes durante unos 4–5 minutos por lado, sin moverlos hasta que se despeguen; ajusta el fuego si se queman. Comprueba con termómetro que el centro más grueso de cada filete alcanza al menos 74 °C, sin tocar la sartén con la sonda. Si falta temperatura, sigue cocinando y vuelve a medir; el color y el reloj no bastan. Retira a un plato limpio y repite con los otros dos filetes y los 5 g restantes de aceite para cocción. Los 20 minutos previstos son orientativos.'),
 ('Deja reposar y corta en tiras','Deja reposar el pollo cocinado 5 minutos en el plato limpio. Con cuchillo y tabla limpios, corta cada filete en tiras de alrededor de 1 cm de ancho. Debe dejar de desprender vapor intenso antes de ir a la ensalada; espera un poco más si es necesario y suma esa espera al tiempo total. Reserva solo mientras terminas el montaje, sin dejarlo horas a temperatura ambiente.'),
 ('Corta el mango y el aguacate','Pela el mango lavado, separa la pulpa del hueso y pesa 250 g. Corta en dados de unos 2 cm. Abre el aguacate lavado, retira el hueso con una cuchara en lugar de golpearlo con el cuchillo, saca la pulpa y pesa 200 g. Corta también en dados de unos 2 cm. Usa la tabla de fruta limpia, sin contacto con pollo crudo, y prepara ambos justo antes de mezclar para reducir el oscurecimiento del aguacate.'),
 ('Bate el aliño de lima','En un cuenco pequeño mezcla los 40 g de zumo de lima, 10 g de miel, los 2 g de sal y 0,5 g de pimienta restantes. Añade los 20 g de aceite reservados para el aliño y bate con un tenedor hasta que se integre de forma temporal. Remueve de nuevo justo antes de usar si se separa. El aliño no sustituye cocinar el pollo ni evita la contaminación cruzada.'),
 ('Monta la ensalada sin aplastar','Pon la lechuga, pepino y cebolla en un cuenco grande y mezcla con la mitad del aliño. Añade los dados de mango y aguacate y las tiras de pollo templado. Incorpora el resto del aliño con dos cucharas, levantando suavemente desde el fondo para no deshacer el aguacate. Reparte entre cuatro platos, distribuyendo el pollo y la fruta de manera similar.'),
 ('Sirve y conserva refrigerada','Sirve recién montada, sola o con un acompañamiento que no se incluye en la nutrición. Si sobra, tapa y refrigera a 4 °C o menos dentro de 2 horas, o 1 hora si el ambiente supera 32 °C. Consume la ensalada montada dentro de 24 horas como propuesta conservadora; lechuga y aguacate perderán textura. Para adelantar, guarda pollo cocinado, vegetales y aliño separados en frío y monta al servir; no congeles la ensalada completa porque cambiará mucho su textura.')
]
steps=[{'title':t,'content':c,'image_url':'','image_alt':'Ensalada de pollo, aguacate y mango: '+t.lower()} for t,c in step_data]
summary='Esta ensalada combina pollo hecho en sartén, dados de aguacate y mango, lechuga, pepino y cebolla roja. Un aliño de lima, aceite de oliva y un poco de miel une los ingredientes sin convertirlos en una salsa espesa.\n\nLa propuesta rinde 4 porciones. Los 55 minutos estimados incluyen 30 de preparación, 20 para cocinar en dos tandas y 5 de reposo. El pollo se comprueba con termómetro a 74 °C como mínimo; cantidades, tiempos y rendimiento están pendientes de confirmar mediante prueba de cocina.'
excerpt='Ensalada de pollo con aguacate y mango para 4: pollo en sartén, aliño de lima y pasos para lavar, cocinar, cortar y montar sin aplastar la fruta.'
notes='Elige mango maduro pero firme y aguacate que ceda ligeramente sin estar deshecho. Puedes cambiar la lima por el mismo peso de zumo de limón; cambiará el sabor y la nutrición. Si omites la miel, el aliño será más ácido y las cifras nutricionales ya no serán las mismas. La lechuga debe estar seca para no diluirlo. Prepara solo la fruta que vas a usar; el ácido retrasa algo el oscurecimiento, pero no mantiene el aguacate intacto indefinidamente. Usa utensilios separados para pollo crudo y alimentos listos para comer. La cocción se determina por temperatura, no por ausencia de color rosado.'
r={'id':'035e3edf-8b72-4604-8cd9-ae6883eff1c5','recipe_group_id':'43e5b443-a225-49c7-b432-217b5df787be','slug':slug,'public_path':'/'+slug,'source_url':'https://manualdecocina.com/'+slug+'/','language':'es','title':'Ensalada de pollo con aguacate y mango','excerpt':excerpt,'summary':summary,'category':'Ensaladas','category_slug':'ensaladas','difficulty':'Fácil','course':'Ensalada principal','cuisine':'Internacional','prep_time_minutes':30,'cook_time_minutes':20,'total_time_minutes':55,'servings':4,'ingredients':ing,'steps':steps,'notes':notes,'nutrition':n,'keywords':['ensalada de pollo con aguacate y mango','ensalada de pollo a la sartén','aliño de lima para ensalada'],'image_url':None,'gallery':[],'seo':{'title':'Ensalada de pollo con aguacate y mango','description':excerpt,'image_alt':'Ensalada con tiras de pollo dorado, dados de mango y aguacate, lechuga, pepino y cebolla roja','image_variants':[],'faq':[{'q':'¿Puedo preparar la ensalada con antelación?','a':'Guarda pollo ya cocinado, vegetales y aliño separados en frío y monta al servir. Corta el aguacate cerca del montaje. La ensalada ya aliñada pierde textura; se propone consumirla en 24 horas refrigerada.'},{'q':'¿Cómo sé si el pollo está bien cocinado?','a':'Mide el centro más grueso de cada filete con un termómetro de alimentos: debe alcanzar al menos 74 °C. Ni un tiempo fijo ni el color de la carne garantizan por sí solos ese punto.'},{'q':'¿Por qué queda agua en el fondo?','a':'La lechuga mojada, el mango demasiado blando y el aliño añadido mucho antes pueden soltar líquido. Seca bien las hojas, usa fruta firme y mezcla justo antes de servir.'}]},'published':False,'editorial_status':'draft','content_html':''.join('<p>'+html.escape(p)+'</p>' for p in summary.split('\n\n'))}
titles={'es':r['title'],'de':'Hähnchensalat mit Avocado und Mango','en':'Chicken salad with avocado and mango','fr':'Salade de poulet à l’avocat et à la mangue','it':'Insalata di pollo con avocado e mango','ja':'鶏肉とアボカド、マンゴーのサラダ','pt':'Salada de frango com abacate e manga'}
st={'es':[t for t,c in step_data],'de':['Gemüse waschen und trocknen','Vier Hähnchenfilets vorbereiten','Braten und Kerntemperatur prüfen','Ruhen lassen und in Streifen schneiden','Mango und Avocado würfeln','Limettendressing verrühren','Salat vorsichtig mischen','Servieren und gekühlt aufbewahren'],'en':['Wash and dry the produce','Prepare four chicken fillets','Cook and check the temperature','Rest and slice into strips','Dice the mango and avocado','Whisk the lime dressing','Assemble gently','Serve and refrigerate'],'fr':['Laver et sécher les végétaux','Préparer quatre filets de poulet','Cuire et vérifier la température','Laisser reposer et couper en lanières','Couper mangue et avocat','Mélanger la vinaigrette au citron vert','Assembler délicatement','Servir et réfrigérer'],'it':['Lava e asciuga le verdure','Prepara quattro filetti di pollo','Cuoci e controlla la temperatura','Lascia riposare e taglia a strisce','Taglia mango e avocado','Mescola il condimento al lime','Assembla delicatamente','Servi e conserva in frigorifero'],'ja':['野菜を洗って乾かす','鶏肉を4枚に整える','焼いて中心温度を確認する','休ませて細切りにする','マンゴーとアボカドを切る','ライムのドレッシングを混ぜる','つぶさずに盛り合わせる','盛り付けて冷蔵保存する'],'pt':['Lave e seque os vegetais','Prepare quatro filés de frango','Cozinhe e confira a temperatura','Deixe descansar e corte em tiras','Corte manga e abacate','Misture o molho de limão','Monte com cuidado','Sirva e guarde na geladeira']}
covers={'es':r['seo']['image_alt'],'de':'Salat mit goldbraunen Hähnchenstreifen, Mango, Avocado, Romanasalat, Gurke und roter Zwiebel','en':'Salad with browned chicken strips, mango and avocado cubes, lettuce, cucumber and red onion','fr':'Salade aux lanières de poulet dorées, mangue, avocat, laitue, concombre et oignon rouge','it':'Insalata con pollo dorato a strisce, mango, avocado, lattuga, cetriolo e cipolla rossa','ja':'焼いた鶏肉、マンゴーとアボカド、レタス、きゅうり、紫玉ねぎのサラダ','pt':'Salada com tiras de frango dourado, manga, abacate, alface, pepino e cebola roxa'}
alts={lang:{'title':t,'cover':covers[lang],'steps':[t+': '+s for s in st[lang]]} for lang,t in titles.items()}
visuals=['Vegetales lavados y secos, lechuga, pepino cortado y cebolla separados; sin pollo crudo cerca.','Cuatro filetes de pollo crudo de grosor uniforme sobre tabla separada, sin vegetales ni plato final.','Filetes dorados en sartén y termómetro midiendo el centro, sin ingredientes de ensalada en la zona de crudo.','Pollo cocinado reposado y cortado en tiras sobre tabla limpia, con interior totalmente opaco.','Dados de mango y aguacate de unos 2 cm preparados sobre tabla de fruta limpia.','Aliño claro de lima, miel y aceite batido con tenedor en cuenco pequeño, sin salsa cremosa.','Montaje suave de lechuga, pepino, cebolla, mango, aguacate y pollo cocinado con dos cucharas.','Ensalada terminada de pollo dorado a tiras, mango y aguacate en dados, lechuga, pepino y cebolla.']
scenes=[
 'Produce preparation phase: clean separate bowls of washed thoroughly dried romaine lettuce pieces, thin cucumber half-moons and thin red onion slivers on a clean light kitchen counter. Washed whole mango, avocado and lime nearby, separate plain produce cutting board and knife. No raw chicken, cooked chicken or assembled salad anywhere.',
 'Raw poultry preparation phase: exactly four raw boneless skinless chicken breast fillets of even about 1.5 cm thickness on a dedicated nonporous white cutting board, lightly seasoned with tiny black pepper flecks. No produce, fruit, salad bowl, cooked chicken or ready-to-eat food anywhere near the raw chicken. Plain knife resting safely beside the board. Clean separated food preparation area.',
 'Cooking phase: two chicken breast fillets with a light golden pan-seared surface in a plain wide frying pan, no charred grill stripes. A food thermometer probe inserted horizontally into the thick centre of one fillet without touching the pan; unbranded display not readable, no fake numbers. No salad produce or raw chicken on the counter. Show thermometer technique and gently golden chicken only.',
 'Cooked chicken slicing phase: rested cooked chicken breast on a clean wooden board, sliced into about 1 cm strips, completely opaque white cut interiors with light golden pan-seared outside. Plain clean knife beside it, no raw meat, blood, pink centre, salad produce or assembled dish.',
 'Fruit cutting phase: ripe firm golden mango flesh and pale green avocado flesh cut into approximately 2 cm cubes on a separate clean produce board, pieces kept in two separate small bowls. Mango pit and avocado stone safely aside, plain spoon beside avocado shell, no knife lodged in stone. No raw chicken or assembled salad.',
 'Dressing phase: small plain bowl of translucent pale golden lime, olive oil and honey dressing with tiny black pepper flecks, a fork whisking or resting inside. Squeezed lime half beside it. No creamy mayonnaise, white dairy dressing, herbs, yogurt, salad assembly or chicken in the bowl.',
 'Assembly phase: large plain salad bowl containing dry romaine lettuce, thin cucumber half-moons, red onion slivers, golden mango 2 cm cubes, pale green avocado 2 cm cubes and cooked lightly golden chicken breast strips with opaque white interiors. Two plain serving spoons gently lift ingredients without crushing avocado. Light translucent dressing, no extra tomato, nuts, cheese, herbs, mayonnaise or raw chicken.'
]
base='Use case: photorealistic-natural. Asset type: original Manual de Cocina chicken avocado mango salad recipe photograph. One realistic photo, 4:3 landscape, soft natural light, clean light neutral kitchen, plain unbranded utensils, correct food safety phases and natural edible textures. No text, label, logo, watermark, collage, extra ingredients, tomato, cheese, nuts, herbs, mayonnaise or thick creamy sauce. '
cover=base+'Finished four-portion recipe shown as one plated portion: a simple shallow off-white bowl of dry chopped romaine lettuce, thin cucumber half-moons and fine red onion slivers, topped with golden mango cubes around 2 cm, pale green avocado cubes around 2 cm, and lightly golden pan-seared chicken breast strips around 1 cm wide with visibly opaque cooked white interiors. Light translucent lime-olive dressing coating gently, no liquid pool. Balanced even distribution, natural appetising salad, no charcoal grill marks. Generous centred margins for square, 4:3 and 16:9 cover crops.'
h=hashlib.sha256(json.dumps(steps,ensure_ascii=False,sort_keys=True).encode()).hexdigest()
item={'category_slug':'ensaladas','cover':visuals[-1],'step_visuals':visuals,'ai_owner_confirmation':{'status':'delegated_editorial_authority','fields_are_estimated':['ingredients.amount','servings','prep_time_minutes','cook_time_minutes','total_time_minutes','nutrition'],'human_kitchen_confirmation':'not_performed'},'time_notes':'30 minutos activos + 20 orientativos de cocción en dos tandas + 5 de reposo = 55. Cocción real hasta 74 °C; sumar espera si el pollo sigue desprendiendo mucho vapor.','steps_frozen':True,'steps_sha256':h,'publication_blockers':['FINAL_IMAGES_PENDING','FULL_LOCALIZATION_PENDING','BATCH_15_COMPLETION_PENDING','PREVIEW_QA_PENDING'],'image_alts_by_language':alts,'scope':'preview.manualdecocina.com','state':'ES_PREPARED_IMAGES_AND_LOCALIZATIONS_PENDING','provenance':'Receta original desde identidad culinaria de la cola autorizada; no se usan cuerpos, traducciones ni medios WordPress. Una sola entidad ES inédita; sin borrador nuevo anterior en el repositorio. Rutas históricas conservadas incluidas terminaciones -2. Seguridad primaria FDA/CDC/FoodSafety.gov; cálculos USDA reproducibles. Sin prueba de cocina ni promesas de salud.','sources':[{'url':'https://www.foodsafety.gov/food-safety-charts/safe-minimum-internal-temperatures','purpose':'Pollo a al menos 74 °C, comprobado con termómetro.','accessed':'2026-10-08'},{'url':'https://www.cdc.gov/food-safety/foods/chicken.html','purpose':'Separación crudo/listo para comer, no necesidad de lavar pollo, limpieza y refrigeración de sobras en 2 horas o 1 con calor >32 °C.','accessed':'2026-10-08'},{'url':'https://www.fda.gov/food/buy-store-serve-safe-food/selecting-and-serving-produce-safely','purpose':'Lavado de fruta y vegetales antes de pelar, secado y separación de pollo crudo.','accessed':'2026-10-08'},{'url':'https://fdc.nal.usda.gov/fdc-datasets/FoodData_Central_sr_legacy_food_csv_2018-04.zip','purpose':'Once fichas USDA verificadas y pesos comestibles.','accessed':'2026-10-08'}],'records':[r]}
manifest={'slug':slug,'recipe_group_id':r['recipe_group_id'],'date':'2026-10-08','steps_frozen':True,'steps_sha256':h,'directory':f'public/recetas/{slug}/','image_source':'built-in image generation; one call per distinct original; cover crops from same original','prompts':[{'asset':'portada.webp','step':8,'prompt':cover}]+[{'asset':f'paso-{i:02d}.webp','step':i,'prompt':base+s} for i,s in enumerate(scenes,1)],'images':[],'state':'GENERATION_PENDING','last_step_reuses_cover':True}
gsc=Path(sys.argv[2]);paths={'/ensalada-de-pollo-con-aguacate-y-mango','/de/huhnersalat-mit-avocado-und-mango','/en/chicken-salad-with-avocado-and-mango-2','/fr/salade-de-poulet-avec-avocat-et-mangue-2','/it/insalata-di-pollo-con-avocado-e-mango-2'}
rows=[r for r in csv.DictReader(gsc.open()) if r['Path normalizado'] in paths]
routes={'date':'2026-10-08','classification':'CULINARY_QUEUE_CANDIDATE_VALIDATED','classification_sources':['editorial/automation-queue.json','docs/CATALOG-FINAL-V1-20260924.md','docs/P4-CLOSEOUT-20260924.md'],'historical_rows':rows,'source_matrix_sha256':hashlib.sha256(gsc.read_bytes()).hexdigest(),'new_proposed_paths':{'ja':'/ja/chicken-avocado-mango-salad','pt':'/pt/salada-de-frango-abacate-e-manga'},'collision_check':{'recipes':'Only preserved ES identity; no other mango chicken salad group','content_pages':'No seven-route or slug collisions','content_redirects':'ES temporary catalogue fallback only; direct HTTP200 required after publication'},'decision':'Relevant original culinary candidate from active queue, no archived/REVIEW/OUT or duplicate match found; classification preserved. Historical -2 language routes remain exact; new JA and PT-BR collision-free. No redirects changed.'}
for name,obj in [(f'{slug}-20261008.json',item),(f'{slug}-imagenes.json',manifest),(f'{slug}-rutas-20261008.json',routes)]: (root/'editorial'/name).write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'slug':slug,'steps':len(steps),'nutrition':{k:v for k,v in n.items() if isinstance(v,(int,float))}}))
