"""Prepare an original four-layer rainbow fruit drink; Spanish is frozen before images."""
import csv
import hashlib
import html
import json
import sys
from pathlib import Path
from editorial_nutrition import calculate

ROOT = Path(__file__).resolve().parents[1]
SLUG = 'receta-jugo-arcoiris'
GROUP = '8d66b805-5283-43f9-833b-b1ba0875d57f'
TITLE = 'Jugo arcoíris de frutas en cuatro capas'
foods = [('arándanos', 200, 171711), ('fresas sin hojas', 200, 167762), ('kiwi pelado', 200, 168153), ('mango pelado sin hueso', 200, 169910), ('banana pelada', 200, 173944), ('agua potable', 80, 173647)]
nutrition = calculate(sys.argv[1], foods, 4)
nutrition.update(serving_size='1 de 4 vasos, aproximadamente 270 g', method='Suma de las fichas USDA verificadas por 100 g, ponderada por el peso comestible de cada fruta antes de congelar y por 80 g de agua, dividida entre 4. Los 80 ml de agua se aproximan a 80 g. Sin azúcar, leche ni adornos añadidos.', note='Estimación informativa, no análisis del producto preparado. Varía con la madurez de la fruta, el agua utilizada y la mezcla que quede en la batidora. No se cuela: se incluye toda la pulpa de las cantidades indicadas.')
summary = 'Este jugo arcoíris es una bebida espesa de fruta entera, con textura de batido y cuatro capas de colores naturales: violeta de arándano, rosada de fresa, verde de kiwi y dorada de mango. Una pequeña cantidad de banana en cada mezcla ayuda a dar cuerpo. No se cuela ni se añaden colorantes, leche o azúcar.\n\nRinde 4 vasos de unos 270 g. Los 90 minutos totales incluyen 60 minutos de congelado previo. Las capas se sirven recién montadas; sus bordes pueden mezclarse un poco y no se mantienen separados indefinidamente.'
excerpt = 'Jugo arcoíris de frutas en cuatro capas: arándano, fresa, kiwi y mango. Cantidades para 4 vasos, congelado previo y montaje paso a paso, sin colorantes.'
names = ['arándanos frescos', 'fresas, peso sin hojas', 'kiwi, peso pelado', 'mango, peso pelado y sin hueso', 'banana, peso pelado', 'agua potable fría']
ingredients = [{'name': name, 'amount': '200' if i < 5 else '80', 'unit': 'g' if i < 5 else 'ml', 'group': 'Frutas' if i < 5 else 'Para triturar'} for i, name in enumerate(names)]
step_data = [
    ('Lava, corta y reparte la fruta', 'Lávate las manos y lava toda la fruta bajo agua corriente antes de pelar, sin jabón. Retira partes dañadas, hojas de las fresas, piel de kiwi y banana, y piel y hueso del mango. Pesa 200 g comestibles de cada una de las cinco frutas. Corta mango, kiwi, fresa y banana en trozos de unos 2 cm. Divide la banana en cuatro porciones de 50 g y junta cada una con una fruta distinta en cuatro recipientes separados.'),
    ('Congela las cuatro mezclas', 'Extiende por separado los arándanos con 50 g de banana, las fresas con 50 g, el kiwi con 50 g y el mango con los últimos 50 g en recipientes bajos aptos para congelador. Tapa y congela unos 60 minutos, hasta que la fruta esté firme pero los trozos se puedan separar. Si siguen blandos, necesitan más tiempo; no congeles en un bloque grueso. Enfría cuatro vasos de al menos 350 ml en la nevera.'),
    ('Tritura la capa violeta', 'Pon los 200 g de arándanos y sus 50 g de banana fría en una batidora apta para fruta congelada, con 20 ml de agua. Tritura de 40 a 60 segundos hasta obtener una mezcla espesa y uniforme. Si no mueve bien, apaga y desconecta antes de bajar la fruta con una espátula; deja ablandar 2 minutos en vez de añadir agua de más. Pasa a un cuenco, tapa y reserva en la nevera.'),
    ('Tritura la capa de fresa', 'Lava y seca el vaso de la batidora para no teñir la siguiente mezcla. Tritura los 200 g de fresa con sus 50 g de banana y 20 ml de agua de 40 a 60 segundos. Debe quedar rosada y espesa, no líquida. Pasa a otro cuenco, tapa y refrigera mientras terminas las demás capas.'),
    ('Tritura la capa verde', 'Vuelve a lavar y secar el vaso. Tritura los 200 g de kiwi con sus 50 g de banana y 20 ml de agua de 40 a 60 segundos. Mantén las semillas pequeñas del kiwi; no cueles la pulpa. Guarda la mezcla verde tapada en la nevera.'),
    ('Tritura la capa dorada', 'Lava y seca el vaso una vez más. Tritura los 200 g de mango con los últimos 50 g de banana y 20 ml de agua de 40 a 60 segundos, hasta que quede una crema dorada homogénea. La consistencia debe ser parecida a la de las otras capas; si alguna se ha templado demasiado, refrigérala antes de montar.'),
    ('Monta las capas despacio', 'Reparte la mezcla violeta entre los cuatro vasos fríos. Añade una cuarta parte de la mezcla de fresa a cada uno, dejándola caer despacio sobre el dorso de una cuchara situada justo encima de la capa anterior. Repite con el kiwi y termina con el mango. No remuevas ni viertas desde altura; cada vaso recibe un cuarto de las cuatro mezclas.'),
    ('Sirve recién montado', 'Sirve inmediatamente con una cuchara larga, mientras las cuatro capas conservan su forma. Para guardarlo, tapa y refrigera a 4 °C o menos y consume dentro de 24 horas; el color y la separación cambiarán. Si se mezcla, remueve y sírvelo como un batido de frutas. No lo dejes más de 2 horas a temperatura ambiente.'),
]
steps = [{'title': t, 'content': c, 'image_url': '', 'image_alt': 'Jugo arcoíris: ' + t.lower()} for t, c in step_data]
notes = 'Usa fruta madura para equilibrar la acidez del kiwi. La congelación y el poco líquido ayudan al montaje, pero no garantizan líneas perfectas: las capas son de fruta y pueden difuminarse. Para usar fruta ya congelada, respeta los mismos pesos comestibles y comprueba si su envase pide cocinarla; no uses cruda una fruta que requiera cocción. Adapta el tiempo total si omites el congelado previo. Si tu batidora no admite fruta congelada, deja ablandar los trozos hasta que pueda procesarlos con seguridad; las capas quedarán menos definidas. No se atribuyen efectos adelgazantes ni terapéuticos a esta bebida.'
record = {'id': '8ae419ae-f12a-4faa-8379-bb4b2c00a77b', 'recipe_group_id': GROUP, 'slug': SLUG, 'public_path': '/' + SLUG, 'source_url': 'https://manualdecocina.com/' + SLUG + '/', 'language': 'es', 'title': TITLE, 'excerpt': excerpt, 'summary': summary, 'category': 'Bebidas', 'category_slug': 'bebidas', 'difficulty': 'Fácil', 'course': 'Bebida', 'cuisine': 'Internacional', 'prep_time_minutes': 30, 'cook_time_minutes': 0, 'total_time_minutes': 90, 'servings': 4, 'ingredients': ingredients, 'steps': steps, 'notes': notes, 'nutrition': nutrition, 'keywords': ['jugo arcoíris', 'batido de frutas en capas', 'bebida de mango kiwi fresa arándano'], 'image_url': None, 'gallery': [], 'seo': {'title': 'Jugo arcoíris de frutas en capas | Manual de Cocina', 'description': excerpt, 'image_alt': 'Cuatro vasos de jugo arcoíris con capas violeta, rosada, verde y dorada de fruta', 'image_variants': [], 'faq': [{'q': '¿Por qué se mezclan los colores?', 'a': 'Las mezclas deben estar frías y espesas. Añade cada capa lentamente sobre una cuchara, sin altura, y sirve enseguida. Son purés de fruta y los bordes pueden difuminarse.'}, {'q': '¿Es un jugo filtrado?', 'a': 'No. Se conserva toda la pulpa, por lo que tiene textura de batido. Colarlo o añadir mucho líquido haría difícil mantener las capas.'}, {'q': '¿Puedo prepararlo de un día para otro?', 'a': 'Puedes guardar las cuatro mezclas tapadas por separado a 4 °C o menos hasta 24 horas y montarlas al servir. Cambiarán el color y la textura, especialmente la banana.'}]}, 'published': False, 'editorial_status': 'draft', 'content_html': ''.join('<p>' + html.escape(p) + '</p>' for p in summary.split('\n\n'))}
titles = {'es': TITLE, 'de': 'Regenbogensaft aus Früchten in vier Schichten', 'en': 'Four-layer rainbow fruit juice', 'fr': 'Jus arc-en-ciel aux fruits en quatre couches', 'it': 'Succo arcobaleno alla frutta in quattro strati', 'ja': '4色のフルーツ・レインボージュース', 'pt': 'Suco arco-íris de frutas em quatro camadas'}
step_titles = {
    'es': [s['title'] for s in steps],
    'de': ['Früchte waschen, schneiden und aufteilen', 'Vier Fruchtmischungen einfrieren', 'Violette Schicht pürieren', 'Erdbeerschicht pürieren', 'Grüne Schicht pürieren', 'Goldene Schicht pürieren', 'Schichten langsam einfüllen', 'Frisch geschichtet servieren'],
    'en': ['Wash, cut and portion the fruit', 'Freeze the four mixtures', 'Blend the purple layer', 'Blend the strawberry layer', 'Blend the green layer', 'Blend the golden layer', 'Build the layers slowly', 'Serve freshly layered'],
    'fr': ['Laver, couper et répartir les fruits', 'Congeler les quatre mélanges', 'Mixer la couche violette', 'Mixer la couche de fraise', 'Mixer la couche verte', 'Mixer la couche dorée', 'Monter les couches doucement', 'Servir juste après le montage'],
    'it': ['Lava, taglia e dividi la frutta', 'Congela le quattro miscele', 'Frulla lo strato viola', 'Frulla lo strato alla fragola', 'Frulla lo strato verde', 'Frulla lo strato dorato', 'Forma gli strati lentamente', 'Servi appena composto'],
    'ja': ['果物を洗って切り分ける', '4種類の果物を冷凍する', '紫色の層を攪拌する', 'いちごの層を攪拌する', '緑色の層を攪拌する', '黄金色の層を攪拌する', 'ゆっくり重ねる', '重ねたらすぐに出す'],
    'pt': ['Lave, corte e divida as frutas', 'Congele as quatro misturas', 'Bata a camada roxa', 'Bata a camada de morango', 'Bata a camada verde', 'Bata a camada dourada', 'Monte as camadas devagar', 'Sirva logo depois de montar'],
}
covers = {'es': record['seo']['image_alt'], 'de': 'Vier Gläser Regenbogensaft mit violetten, rosafarbenen, grünen und goldenen Fruchtschichten', 'en': 'Four glasses of rainbow fruit juice with purple, pink, green and golden layers', 'fr': 'Quatre verres de jus arc-en-ciel aux couches de fruits violette, rose, verte et dorée', 'it': 'Quattro bicchieri di succo arcobaleno con strati di frutta viola, rosa, verde e dorati', 'ja': '紫、ピンク、緑、黄金色の果物を重ねたレインボージュース4杯', 'pt': 'Quatro copos de suco arco-íris com camadas de frutas roxa, rosa, verde e dourada'}
alts = {lang: {'title': title, 'cover': covers[lang], 'steps': [title + ': ' + t for t in step_titles[lang]]} for lang, title in titles.items()}
visuals = [
    'Cinco frutas lavadas, cortadas y pesadas en cuencos separados; banana repartida en cuatro grupos y cada uno junto a una fruta.',
    'Cuatro recipientes bajos tapados aptos para congelador con fruta troceada y banana: arándanos, fresa, kiwi y mango, separados y con escarcha ligera.',
    'Puré violeta espeso recién triturado de arándanos y banana, en vaso de batidora apagada; únicamente ingredientes de esta capa.',
    'Puré rosado espeso recién triturado de fresa y banana, en vaso de batidora limpia y apagada; únicamente ingredientes de esta capa.',
    'Puré verde espeso de kiwi y banana, con pequeñas semillas de kiwi, en vaso de batidora limpia y apagada.',
    'Puré dorado espeso de mango y banana, en vaso de batidora limpia y apagada.',
    'Montaje en vasos transparentes: violeta abajo, rosado encima, verde añadido con el dorso de cuchara; mezcla dorada todavía en cuenco separado.',
    'Cuatro vasos terminados con cuatro capas naturales, de abajo arriba violeta, rosado, verde y dorado; sin adornos ni ingredientes extra.',
]
frozen_hash = hashlib.sha256(json.dumps(steps, ensure_ascii=False, sort_keys=True).encode()).hexdigest()
recipe = {'category_slug': 'bebidas', 'cover': visuals[-1], 'step_visuals': visuals, 'ai_owner_confirmation': {'status': 'delegated_editorial_authority', 'fields_are_estimated': ['ingredients.amount', 'prep_time_minutes', 'total_time_minutes', 'servings', 'nutrition'], 'human_kitchen_confirmation': 'not_performed', 'authority': 'Producción y publicación autónomas autorizadas por el usuario el 2026-10-08.'}, 'time_notes': '30 minutos de preparación activa + 60 minutos de congelado; sin cocción. El congelador y tamaño de los trozos pueden alargar la espera.', 'steps_frozen': True, 'steps_sha256': frozen_hash, 'publication_blockers': ['FINAL_IMAGES_PENDING', 'FULL_LOCALIZATION_PENDING', 'BATCH_15_COMPLETION_PENDING', 'PREVIEW_QA_PENDING'], 'image_alts_by_language': alts, 'scope': 'preview.manualdecocina.com', 'state': 'ES_PREPARED_IMAGES_AND_LOCALIZATIONS_PENDING', 'provenance': 'Receta original a partir de identidad y URL aprobadas KEEP/REBUILD; no se leyeron cuerpos, ingredientes, traducciones ni imágenes WordPress. Técnica de batido propia informada por guía primaria de fabricante; seguridad de fruta consultada en FDA y cálculo reproducible de USDA. No se realizó prueba de cocina ni se atribuyen beneficios médicos.', 'sources': [{'url': 'https://www.fda.gov/food/buy-store-serve-safe-food/selecting-and-serving-produce-safely', 'purpose': 'Lavado de fruta bajo agua corriente, limpieza y refrigeración.', 'accessed': '2026-10-08'}, {'url': 'https://www.vitamix.com/us/en_us/articles/part-2-all-about-smoothie-blending', 'purpose': 'Principio de espesar batidos con fruta congelada; no se reutilizan cantidades ni receta.', 'accessed': '2026-10-08'}, {'url': 'https://fdc.nal.usda.gov/fdc-datasets/FoodData_Central_sr_legacy_food_csv_2018-04.zip', 'purpose': 'Fichas originales para nutrientes por peso comestible.', 'accessed': '2026-10-08'}], 'records': [record]}
base_prompt = 'Use case: photorealistic-natural. Asset type: original Manual de Cocina recipe photograph. A single realistic food photo, 4:3 landscape framing, soft natural window light, clean light neutral kitchen counter, simple unbranded transparent glasses and blender, accurate natural fruit textures. No text, label, watermark, collage, extra ingredients, milk, yogurt, sugar, artificial colouring, blue-coloured liquid or garnish. The drink is thick fruit puree, not clear filtered juice. '
english_scenes = [
    'Washed prepared fruit on a clean worktop: five separate small bowls holding blueberries, hulled strawberry pieces, peeled green kiwi chunks, golden mango chunks and peeled banana pieces. A plain digital scale with unreadable display. Four small banana portions each placed beside one coloured fruit, before blending. Do not show a completed drink.',
    'Four shallow clear freezer-safe plastic containers with translucent lids in an open clean freezer drawer, each containing separate fruit chunks mixed with some banana: dark blueberries, red strawberries, green peeled kiwi and golden mango. Light realistic frost on fruit, not a solid block; show this freezing phase only. No glasses in the freezer.',
    'A clean unbranded compact blender cup containing thick smooth deep purple blueberry and banana puree. Blender switched off, closed safe lid. Small bowl of blueberries and some banana pieces beside it. No other colours or fruits, no layered drink.',
    'A clean unbranded compact blender cup containing thick smooth strawberry-pink puree of strawberries and banana. Blender switched off, closed safe lid. A few hulled strawberry pieces and banana pieces beside it. No other colours or fruits, no layered drink.',
    'A clean unbranded compact blender cup containing thick green kiwi and banana puree with tiny black kiwi seed flecks. Blender switched off, closed safe lid. Some peeled kiwi pieces and banana pieces beside it. No other fruits or colours, no layered drink.',
    'A clean unbranded compact blender cup containing thick golden yellow-orange mango and banana puree. Blender switched off, closed safe lid. Golden mango chunks and banana pieces beside it. No other fruits or colours, no layered drink.',
    'Close-up layering stage: four identical transparent 350 ml tumblers with deep purple blueberry puree at the bottom and strawberry pink puree above. One anatomically correct hand gently adds thick green kiwi puree to the first glass over the back of a spoon immediately above the pink surface. A separate small bowl of golden mango puree waits nearby; absolutely no golden top layer in these glasses yet. Thick puree, naturally soft boundaries, not perfect plastic stripes.',
]
cover_prompt = base_prompt + 'Finished rainbow fruit drink in four identical plain transparent 350 ml tumblers, standing close together, each filled with four fairly equal thick fruit puree layers. Exact order BOTTOM TO TOP: deep purple blueberry, strawberry pink, green kiwi with tiny seed flecks, golden yellow-orange mango. Natural slightly soft wavy boundaries, not artificially perfect geometric stripes. No blue layer, no extra white layer, no fruit garnish. One simple long spoon lies beside the glasses. Show all four colours clearly in all glasses, realistic volume around 270 g per glass. Central generous composition with crop margin for square, 4:3 and 16:9 cover variants.'
prompts = [{'asset': 'portada.webp', 'step': 8, 'prompt': cover_prompt}] + [{'asset': f'paso-{i:02d}.webp', 'step': i, 'prompt': base_prompt + scene} for i, scene in enumerate(english_scenes, 1)]
manifest = {'slug': SLUG, 'recipe_group_id': GROUP, 'date': '2026-10-08', 'steps_frozen': True, 'steps_sha256': frozen_hash, 'directory': f'public/recetas/{SLUG}/', 'image_source': 'built-in image generation; one call per distinct original; cover crops from same original', 'prompts': prompts, 'images': [], 'state': 'GENERATION_PENDING', 'last_step_reuses_cover': True}
def write(name, obj):
    (ROOT / 'editorial' / name).write_text(json.dumps(obj, ensure_ascii=False, indent=2) + '\n')
write(f'{SLUG}-20261008.json', recipe)
write(f'{SLUG}-imagenes.json', manifest)
gsc_path = Path(sys.argv[2])
rows = [r for r in csv.DictReader(gsc_path.open()) if r['Path normalizado'] in {'/receta-jugo-arcoiris', '/it/ricetta-succo-arcobaleno', '/en/rainbow-juice-recipe', '/fr/recette-de-jus-arc-en-ciel', '/de/regenbogensaft-rezept'}]
write(f'{SLUG}-rutas-20261008.json', {'date': '2026-10-08', 'classification': 'KEEP/REBUILD', 'classification_sources': ['docs/CATALOG-FINAL-V1-20260924.md', 'docs/URL-MASTER-CONSOLIDATED-20260924.md', 'docs/URL-MASTER-URL-ROWS-20260924.md'], 'historical_rows': rows, 'source_matrix_sha256': hashlib.sha256(gsc_path.read_bytes()).hexdigest(), 'new_proposed_paths': {'ja': '/ja/rainbow-fruit-juice', 'pt': '/pt/suco-arco-iris'}, 'collision_check': 'PENDING'})
print(json.dumps({'slug': SLUG, 'steps': len(steps), 'alt_languages': len(alts), 'nutrition': {k: v for k, v in nutrition.items() if isinstance(v, (int, float))}}, ensure_ascii=False))
