"""Original seafood pasta for four; proposed shell-on mussel yield is explicit."""
import csv,hashlib,html,json,sys
from pathlib import Path
from editorial_nutrition import calculate
root=Path(__file__).resolve().parents[1];slug='pasta-frutos-del-mar'
assert not (root/f'editorial/{slug}-20261008.json').exists()
foods=[('espaguetis secos',320,169736),('langostinos crudos pelados',250,174210),('calamar crudo limpio',250,174223),('mejillón, carne cruda estimada de 600 g con concha',150,174216),('tomate triturado en conserva',400,170501),('cebolla',100,170000),('ajo',12,169230),('aceite de oliva',30,171413),('perejil fresco',8,170416),('sal',3,173468)]
n=calculate(sys.argv[1],foods,4)
n.update(serving_size='1 de 4 platos, sin conchas',method='Diez fichas USDA verificadas, pesos secos de pasta y crudos comestibles de marisco, total dividido entre 4. Se propone un rendimiento de mejillón de 150 g de carne a partir de 600 g con concha, equivalente al 25 %, pendiente de pesar en cocina. Langostinos y calamar se aproximan con fichas de especies mixtas; mejillón con mejillón azul crudo. Aceite, tomate y sal de salsa contados completos. Pasta cocida en agua sin sal; agua escurrida y conchas no incluidas.',note='Estimación informativa, no análisis del plato terminado. El rendimiento real de mejillones, descartes, especie, posibles aditivos del langostino y marcas alteran las cifras. No incluye queso, pan ni vino; el líquido de mejillones puede aportar sales no reflejadas completamente por el rendimiento propuesto.')
ing=[{'name':name if i!=3 else 'mejillones vivos con concha','amount':str(g) if i!=3 else '600','unit':'g','group':'Pasta y marisco' if i<4 else 'Salsa'} for i,(name,g,fdc) in enumerate(foods)]
ing.extend([{'name':'agua para la pasta, sin sal','amount':'3000','unit':'ml','group':'Cocción'},{'name':'agua para abrir los mejillones','amount':'100','unit':'ml','group':'Cocción'}])
data=[
('Limpia y revisa el marisco','Usa 250 g de langostinos crudos ya pelados y sin intestino, y 250 g de calamar limpio: cuerpo sin piel ni vísceras, tentáculos sin pico. Corta el cuerpo en anillas de unos 0,5 cm y divide tentáculos grandes. Revisa los 600 g de mejillones vivos con concha de proveedor autorizado: descarta conchas rotas y los abiertos que no se cierren al dar un golpe suave. Cepilla bajo agua fría y retira las barbas justo antes de cocinar; no los dejes sumergidos en agua dulce. Mantén el marisco separado y refrigerado a 4 °C o menos mientras preparas la salsa. Si usas langostino o calamar congelado, descongela antes en la nevera; esa espera no entra en los 50 minutos.'),
('Pica los aromáticos y calienta el agua','Pica los 100 g de cebolla y los 12 g de ajo en una tabla limpia distinta de la del marisco crudo. Lava y pica los 8 g de perejil. Pon los 3 litros de agua para pasta en una olla amplia y calienta hasta hervir, sin añadir sal: la sazón se incorpora a la salsa. Prepara otra olla con tapa para mejillones y una sartén grande para la salsa. Lava manos y utensilios tras tocar marisco crudo; usa un cuenco limpio para el ya cocinado.'),
('Haz una salsa de tomate corta','Calienta los 30 g de aceite en la sartén a fuego medio. Sofríe la cebolla 5 minutos hasta que se ablande, sin quemarla. Añade el ajo y remueve 1 minuto. Incorpora los 400 g de tomate triturado y cocina 8 minutos a hervor suave, removiendo, hasta que pierda parte del agua y deje de saber tan crudo. Mantén la salsa caliente a fuego bajo. Los 14 minutos son orientativos; evita que se seque o se pegue.'),
('Abre los mejillones al vapor','Mientras se hace la salsa, vierte los 100 ml de agua en la olla de mejillones y lleva a hervor. Añade los mejillones limpios, tapa y cocina unos 4–5 minutos, agitando la olla con cuidado una vez. Retira a un cuenco limpio los que se abran; descarta los que sigan cerrados al final, sin forzarlos. Conserva hasta 100 ml del líquido y pásalo por colador fino con gasa limpia para quitar arena. Incorpóralo a la salsa. Deja algunos mejillones en su concha para servir y extrae la carne del resto con utensilios limpios. Mantén todo junto solo mientras terminas el plato.'),
('Cocina langostinos y calamar','Sube la salsa a hervor suave y añade los 250 g de langostinos y los 250 g de calamar. Cocina unos 3–4 minutos, moviendo, hasta que los langostinos estén firmes y opacos y el calamar pierda translucidez. Comprueba con una sonda fina que las partes más gruesas del marisco alcancen al menos 63 °C; si no, sigue y vuelve a medir. El tiempo depende del tamaño y la temperatura inicial. Retira el marisco cocinado a otro cuenco limpio para que no siga cocinándose mientras acabas la pasta. No uses el cuenco del marisco crudo.'),
('Cuece la pasta y reserva agua','Calcula el inicio para terminar esta fase cerca del marisco, ya que se puede cocer en paralelo. Echa los 320 g de espaguetis en el agua hirviendo sin sal, remueve al principio para separarlos y cuece 2 minutos menos que el tiempo al dente indicado en su envase: se terminarán en la salsa. Antes de escurrir guarda 150 ml del agua de cocción en una taza. Escurre sin enjuagar. Si la pasta o el marisco requieren más tiempo del previsto, amplía el total; no apresures una cocción insuficiente.'),
('Termina la pasta en la salsa','Añade los espaguetis escurridos a la salsa y mezcla a fuego medio unos 2 minutos, hasta que queden al dente. Añade agua reservada de 30 en 30 ml solo si hace falta para que la salsa cubra la pasta sin charco. Durante los últimos 30 segundos incorpora langostinos, calamar, mejillones y perejil, mezclando suavemente para calentarlos sin deshacerlos. Prueba con utensilio limpio y añade los 3 g de sal previstos, o menos si el líquido de mejillón ya sala bastante; menos sal cambia el sodio estimado. No añadas conchas cerradas ni fragments de concha.'),
('Sirve enseguida y enfría las sobras','Reparte en 4 platos distribuyendo por igual la pasta y las tres clases de marisco. Sirve inmediatamente; prolongar el calor endurece langostinos y calamar. Retira las conchas antes de guardar sobras, divide en recipientes pequeños y refrigera a 4 °C o menos dentro de 2 horas, o 1 hora si el ambiente supera 32 °C. Se propone consumir las sobras en 24 horas por calidad; recalienta solo la cantidad que vayas a comer, removiendo hasta al menos 74 °C en varios puntos. No se propone congelar el plato montado: pasta y marisco perderán textura.')]
steps=[{'title':t,'content':c.replace('fragments','fragmentos'),'image_url':'','image_alt':'Pasta de frutos del mar: '+t.lower()} for t,c in data]
summary='Esta pasta de frutos del mar reúne espaguetis, langostinos, calamar y mejillones en una salsa corta de tomate, ajo, cebolla y perejil. Los mejillones se abren aparte para filtrar su líquido; el resto del marisco se cocina en la salsa y se reserva mientras la pasta termina de cocerse.\n\nLa propuesta rinde 4 platos y estima 25 minutos de preparación y 25 de cocción, 50 en total, con agua, pasta y mejillones en paralelo cuando sea posible. Cantidades, tiempos y rendimiento están pendientes de una prueba de cocina. Para la nutrición se proponen 150 g de carne comestible de los 600 g de mejillones con concha; el rendimiento real debe pesarse.'
excerpt='Pasta de frutos del mar para 4 con langostinos, calamar y mejillones: salsa de tomate, cocción por fases y pasos para terminar los espaguetis.'
notes='La identidad del plato incluye las tres clases de marisco; sustituirlas por una mezcla comercial cambia cantidades, proceso y nutrición. Compra mejillones vivos de origen autorizado y sigue las indicaciones de conservación del proveedor. Elige langostinos crudos pelados y calamar ya limpio para que los pesos sean comestibles. No añadas vino o queso manteniendo el mismo cálculo. Para ajustar la salsa usa pequeñas cantidades de agua de pasta, no toda la taza por obligación. No reutilices tablas o cuencos del marisco crudo sin lavar. Contiene crustáceos, moluscos y trigo; revisa también las etiquetas si hay otros ingredientes o trazas. La temperatura y las señales de cocción mandan sobre el tiempo propuesto.'
r={'id':'ab45af90-bbfd-45b3-b417-b4c07bc3e7f1','recipe_group_id':'00a8928a-742e-4878-ba98-0539334c3530','slug':slug,'public_path':'/'+slug,'source_url':'https://manualdecocina.com/'+slug+'/','language':'es','title':'Pasta de frutos del mar con tomate','excerpt':excerpt,'summary':summary,'category':'Pastas','category_slug':'pastas','difficulty':'Media','course':'Plato principal','cuisine':'Mediterránea, propuesta casera','prep_time_minutes':25,'cook_time_minutes':25,'total_time_minutes':50,'servings':4,'ingredients':ing,'steps':steps,'notes':notes,'nutrition':n,'keywords':['pasta de frutos del mar','espaguetis con marisco','pasta con langostinos calamar y mejillones'],'image_url':None,'gallery':[],'seo':{'title':'Pasta de frutos del mar con tomate','description':excerpt,'image_alt':'Espaguetis con salsa de tomate, langostinos pelados, anillas de calamar, mejillones abiertos y perejil','image_variants':[],'faq':[{'q':'¿Qué hago con los mejillones que no se abren?','a':'Descarta los que sigan cerrados después de cocinar; no los fuerces para incorporarlos. Antes de cocinar también se descartan conchas rotas y los abiertos que no se cierren al tocarlos suavemente.'},{'q':'¿Puedo usar marisco congelado?','a':'Para langostinos y calamar, descongela en la nevera antes de empezar y pesa ya pelados o limpios. La descongelación no se cuenta en los 50 minutos. Esta propuesta usa mejillones vivos con concha, no un cambio directo por mejillón congelado.'},{'q':'¿Cómo evito que la pasta quede seca?','a':'Guarda 150 ml del agua de pasta y añade de 30 en 30 ml solo lo necesario al terminar los espaguetis en la salsa. Reincorpora el marisco al final para evitar un recalentado prolongado.'}]},'published':False,'editorial_status':'draft','content_html':''.join('<p>'+html.escape(p)+'</p>' for p in summary.split('\n\n'))}
titles={'es':r['title'],'de':'Pasta mit Meeresfrüchten und Tomatensauce','en':'Seafood pasta with tomato sauce','fr':'Pâtes aux fruits de mer et à la tomate','it':'Pasta ai frutti di mare con pomodoro','ja':'魚介とトマトソースのスパゲッティ','pt':'Massa com frutos do mar e tomate'}
st={'es':[t for t,c in data],'de':['Meeresfrüchte putzen und prüfen','Aromaten hacken und Wasser erhitzen','Kurze Tomatensauce zubereiten','Miesmuscheln dämpfen','Garnelen und Tintenfisch garen','Pasta kochen und Wasser aufheben','Pasta in der Sauce fertig garen','Sofort servieren und Reste kühlen'],'en':['Clean and check the seafood','Chop aromatics and heat water','Make a quick tomato sauce','Steam the mussels open','Cook shrimp and squid','Cook pasta and save water','Finish the pasta in the sauce','Serve immediately and chill leftovers'],'fr':['Nettoyer et vérifier les fruits de mer','Hacher les aromates et chauffer l’eau','Préparer une sauce tomate courte','Ouvrir les moules à la vapeur','Cuire crevettes et calamar','Cuire les pâtes et garder de l’eau','Terminer les pâtes dans la sauce','Servir aussitôt et refroidir les restes'],'it':['Pulisci e controlla i frutti di mare','Trita gli aromi e scalda l’acqua','Prepara una salsa di pomodoro breve','Apri le cozze al vapore','Cuoci gamberi e calamari','Cuoci la pasta e conserva acqua','Finisci la pasta nella salsa','Servi subito e raffredda gli avanzi'],'ja':['魚介を下処理して確認する','香味野菜を刻み湯を沸かす','短時間のトマトソースを作る','ムール貝を蒸して開く','えびといかを加熱する','パスタをゆでて湯を取り分ける','ソースでパスタを仕上げる','すぐに盛り付け残りを冷蔵する'],'pt':['Limpe e confira os frutos do mar','Pique os aromáticos e aqueça a água','Faça um molho rápido de tomate','Abra os mexilhões no vapor','Cozinhe camarão e lula','Cozinhe a massa e reserve água','Termine a massa no molho','Sirva na hora e refrigere as sobras']}
covers={'es':r['seo']['image_alt'],'de':'Spaghetti mit Tomatensauce, geschälten Garnelen, Tintenfischringen, geöffneten Miesmuscheln und Petersilie','en':'Spaghetti with tomato sauce, peeled shrimp, squid rings, open mussels and parsley','fr':'Spaghetti à la sauce tomate, crevettes décortiquées, anneaux de calamar, moules ouvertes et persil','it':'Spaghetti al pomodoro con gamberi sgusciati, anelli di calamaro, cozze aperte e prezzemolo','ja':'トマトソースのスパゲッティにむきえび、いかの輪切り、開いたムール貝、パセリ','pt':'Espaguete com molho de tomate, camarões sem casca, anéis de lula, mexilhões abertos e salsinha'}
alts={lang:{'title':t,'cover':covers[lang],'steps':[t+': '+s for s in st[lang]]} for lang,t in titles.items()}
visuals=['Marisco crudo separado: langostinos pelados, calamar limpio en anillas y mejillones con concha cerrada.','Cebolla, ajo y perejil picados sobre zona limpia, agua para pasta calentando.','Salsa de tomate con cebolla y ajo reduciendo, aún sin marisco ni pasta.','Mejillones abiertos al vapor en olla aparte y líquido pasando por colador fino con gasa limpia.','Langostinos opacos y calamar en salsa de tomate, aún sin pasta ni mejillones.','Espaguetis hirviendo y una taza de agua de cocción reservada.','Espaguetis mezclados con salsa y tres clases de marisco, perejil añadido al final.','Plato de espaguetis con langostinos, calamar, mejillones abiertos, tomate y perejil.']
scenes=[
'Raw seafood preparation: separate bowls of raw peeled deveined grey translucent shrimp with no heads or shells, raw cleaned squid body cut into thin white rings about 0.5 cm and a few clean small tentacles, and intact live black-blue mussels with CLOSED shells. Keep bowls separate on a dedicated raw-seafood preparation area, no parsley or cooked food nearby, no finished pasta.',
'Aromatics preparation: three separate small plain bowls of finely chopped white onion, minced garlic and washed chopped parsley on a clean produce board, a pot of plain water heating on stove softly in the background. No raw seafood on produce board, no tomato sauce or pasta yet.',
'Sauce phase: plain wide skillet with gently bubbling thick crushed red tomato sauce and visible tiny softened onion and garlic pieces. No seafood, mussels, pasta, parsley garnish or cheese has been added yet. Natural reduction, no tomato chunks, no carrots or peppers.',
'Mussel steaming phase: plain pot containing open black-blue mussel shells with opaque cooked orange-beige flesh, little clear broth and natural steam, lid aside. Beside pot, plain fine mesh strainer lined with clean white food-safe muslin over small bowl, collecting a little clear mussel cooking liquid. No spaghetti, tomato sauce, shrimp or squid in mussel pot.',
'Seafood cooking phase: wide skillet of short red tomato sauce with peeled opaque cooked pink shrimp and white cooked squid rings, a few squid tentacle pieces, still NO spaghetti and NO mussels. Correctly cooked natural seafood texture, no raw grey shrimp, no parsley yet, no cheese or cream.',
'Pasta cooking phase: plain pot of unsalted boiling water containing separate long spaghetti strands, clean utensil gently separating them. A plain small cup containing some lightly cloudy reserved pasta cooking water beside pot. No red sauce, seafood, cheese or finished plated pasta in the water.',
'Final mixing phase: wide skillet containing long spaghetti coated lightly with red tomato sauce, peeled opaque pink shrimp, white squid rings, a few tentacles and OPEN black-blue mussels with cooked orange flesh. Small chopped parsley flecks added at end. Clean tongs gently folding, no cheese, cream, lemon wedges, whole shrimp shells or closed mussels.'
]
base='Use case: photorealistic-natural. Asset type: original Manual de Cocina seafood spaghetti recipe photograph. One realistic 4:3 landscape photograph, soft natural light, clean light neutral kitchen, plain unbranded cookware, anatomically plausible seafood and correct distinct preparation phase. No text, label, logo, watermark, collage, cheese, cream, lemon, wine, carrots or peppers. '
cover=base+'Finished one of four portions on a plain shallow white plate: long spaghetti lightly coated in thick red tomato sauce, peeled cooked opaque pink shrimp with no heads or shells, white cooked squid rings about 0.5 cm and a few small tentacle pieces, OPEN black-blue mussel shells showing cooked orange-beige flesh, small chopped fresh parsley flecks. Even distribution, natural Mediterranean home-style plating, no watery pool, no closed shell mussels, no unlisted garnish. Generous central margins for square, 4:3 and 16:9 responsive cover crops.'
h=hashlib.sha256(json.dumps(steps,ensure_ascii=False,sort_keys=True).encode()).hexdigest()
item={'category_slug':'pastas','cover':visuals[-1],'step_visuals':visuals,'ai_owner_confirmation':{'status':'delegated_editorial_authority','fields_are_estimated':['ingredients.amount','servings','prep_time_minutes','cook_time_minutes','total_time_minutes','nutrition','mussel_edible_yield'],'human_kitchen_confirmation':'not_performed'},'time_notes':'25 minutos de preparación + 25 de cocción = 50; fases de agua, mejillones y pasta solapadas cuando sea posible. Salsa 14, marisco 3–4, acabado pasta 2; tiempos orientativos y cocción real comprobada. Descongelación previa no incluida.','steps_frozen':True,'steps_sha256':h,'publication_blockers':['FINAL_IMAGES_PENDING','FULL_LOCALIZATION_PENDING','BATCH_15_COMPLETION_PENDING','PREVIEW_QA_PENDING'],'image_alts_by_language':alts,'scope':'preview.manualdecocina.com','state':'ES_PREPARED_IMAGES_AND_LOCALIZATIONS_PENDING','provenance':'Original culinary reconstruction of P2 REBUILD CANDIDATE; no legacy WordPress bodies, translations or images. One unpublished ES entity, no duplicate group or new prior draft found. ES and IT historical routes preserved; five proposed new routes checked without collisions. Nutrition includes explicitly proposed shell-on yield, no claim of measured kitchen yield.','sources':[{'url':'https://www.fda.gov/food/buy-store-serve-safe-food/selecting-and-serving-fresh-and-frozen-seafood-safely','purpose':'Revisión de conchas, separación de crudo, descongelación refrigerada y señales de cocción.','accessed':'2026-10-08'},{'url':'https://www.foodsafety.gov/food-safety-charts/safe-minimum-internal-temperatures','purpose':'Marisco a 63 °C como objetivo con sonda fina y recalentado de sobras a 74 °C.','accessed':'2026-10-08'},{'url':'https://fdc.nal.usda.gov/fdc-datasets/FoodData_Central_sr_legacy_food_csv_2018-04.zip','purpose':'Diez fichas verificadas, 150 g de carne de mejillón propuestos a partir de 600 g con concha; rendimiento pendiente de medición.','accessed':'2026-10-08'}],'records':[r]}
manifest={'slug':slug,'recipe_group_id':r['recipe_group_id'],'date':'2026-10-08','steps_frozen':True,'steps_sha256':h,'directory':f'public/recetas/{slug}/','image_source':'built-in image generation; one call per distinct original; cover crops from same original','prompts':[{'asset':'portada.webp','step':8,'prompt':cover}]+[{'asset':f'paso-{i:02d}.webp','step':i,'prompt':base+s} for i,s in enumerate(scenes,1)],'images':[],'state':'GENERATION_PENDING','last_step_reuses_cover':True}
gsc=Path(sys.argv[2]);paths={'/pasta-frutos-del-mar','/it/pasta-frutti-di-mare'}
routes={'date':'2026-10-08','classification':'REBUILD_CANDIDATE_VALIDATED','classification_source':'docs/P2-CATALOG-20260924.md','historical_rows':[r for r in csv.DictReader(gsc.open()) if r['Path normalizado'] in paths],'source_matrix_sha256':hashlib.sha256(gsc.read_bytes()).hexdigest(),'new_proposed_paths':{'de':'/de/pasta-mit-meeresfruchten','en':'/en/seafood-pasta','fr':'/fr/pates-aux-fruits-de-mer','ja':'/ja/seafood-pasta','pt':'/pt/massa-com-frutos-do-mar'},'collision_check':{'recipes':'Only expected preserved ES identity; no other matching pasta group','content_pages':'No path or slug collisions across seven routes','content_redirects':'ES catalogue fallback only, direct HTTP200 required after publication'},'decision':'Preserve historical ES and IT paths; other paths new and collision-free, no invented historical attribution. All ES identifiers and historical source URL unchanged; no redirects edited.'}
for name,obj in [(f'{slug}-20261008.json',item),(f'{slug}-imagenes.json',manifest),(f'{slug}-rutas-20261008.json',routes)]: (root/'editorial'/name).write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'slug':slug,'steps':len(steps),'nutrition':{k:v for k,v in n.items() if isinstance(v,(int,float))}}))
