-- Corrección de control URL Master — 2026-10-04
-- La migración anterior añadió aliases históricos como redirects antes de contrastarlos
-- con la decisión URL-by-URL ya cerrada en 2026-09-25.
-- URL-MASTER-URL-ROWS-20260924.md establece: KEEP / REBUILD => servir la URL histórica
-- directamente; NO crear redirect si el destino final no cambia.
-- Se revierten únicamente las 71 filas introducidas por 20261004202500.
delete from public.content_redirects
where source_path in (
  '/fr/casuela-aux-haricots-colombiens',
  '/de/kolumbianische-bohnen-casuela',
  '/it/casuela-colombiana-di-fagioli',
  '/en/colombian-bean-casuela',
  '/ja/コロンビア豆カスエラ',
  '/ja/メキシカンブリトーのレシピ',
  '/it/ricetta-burrito-messicano',
  '/en/mexican-burrito-recipe',
  '/fr/recette-de-burrito-mexicain',
  '/de/mexikanisches-burrito-rezept',
  '/it/teriyaki-ricetta-pollo',
  '/fr/recette-de-poulet-teriyaki',
  '/de/teriyaki-hahnchen-rezept',
  '/en/teriyaki-chicken-recipe',
  '/ja/テリヤキチキンのレシピ',
  '/fr/milkshake-grimace-mcdonalds',
  '/de/milchshake-grimaze-mcdonalds',
  '/ja/ミルクセーキ-しかめっ面-マクドナルド',
  '/en/milkshake-grimace-mcdonalds-2',
  '/de/ajiaco-rezept',
  '/fr/ajiaco-recette',
  '/ja/アヒアコレシピ',
  '/en/ajiaco-recipe',
  '/it/ricetta-della-torta-al-frutto-della-passione',
  '/ja/パッションフルーツパイのレシピ',
  '/fr/recette-de-tarte-aux-fruits-de-la-passion',
  '/en/passion-fruit-pie-recipe',
  '/de/passionsfruchtkuchen-rezept',
  '/ja/レシピアレパとすべて',
  '/it/ricetta-arepa-con-tutto',
  '/de/rezept-arepa-mit-allem',
  '/fr/recette-arepa-avec-tout',
  '/en/recipe-arepa-with-everything',
  '/it/ricetta-buddha-bowl',
  '/en/buddha-bowl-recipe',
  '/de/buddha-bowl-rezept',
  '/ja/タヒニとロースト野菜を添えたヘルシーなキヌア',
  '/it/ricetta-sana-in-ciotola-di-quinoa-e-ceci-con-tahini-e-verdure-arrostite-2',
  '/fr/recette-de-bol-sain-de-quinoa-et-pois-chiches-avec-tahini-et-legumes-rotis',
  '/de/gesundes-quinoa-kichererbsen-bowl-rezept-mit-tahini-und-gerostetem-gemuse-2',
  '/en/healthy-quinoa-and-chickpea-bowl-recipe-with-tahini-and-roasted-vegetables-2',
  '/receta-saludable-bowl-de-quinoa-y-garbanzos-con-tahini-y-verduras-asadas',
  '/de/gesundes-obst-und-gemuse-smoothie-rezept-2',
  '/ja/健康的な果物と野菜のスムージー-レシピ',
  '/fr/recette-de-smoothie-sain-aux-fruits-et-legumes-2',
  '/it/ricetta-frullato-di-frutta-con-panna',
  '/ja/クリーム入りフルーツスムージーのレシピ',
  '/en/garlic-sauce-recipe',
  '/ja/ガーリックソースのレシピ',
  '/de/knoblauchsauce-rezept',
  '/de/creep-stroganoff',
  '/en/creep-stroganoff',
  '/fr/fluage-stroganoff',
  '/it/creep-stroganoff',
  '/ja/焼きナスの舟',
  '/de/gebackene-auberginenschiffchen',
  '/fr/bateaux-aubergines-au-four',
  '/en/pork-bondiola-recipe',
  '/it/ricetta-maiale-bondiola',
  '/fr/recette-de-porc-bondiola',
  '/ja/ポークボンディオーラのレシピ',
  '/de/schweinefleisch-bondiola-rezept',
  '/en/ground-beef-cannelloni-with-pineapple',
  '/en/shrimp-scampi',
  '/de/shrimps-scampi',
  '/ja/shurinpu-arugaarikku',
  '/de/pilawreis',
  '/ja/ピラフライス',
  '/en/pilaf-rice',
  '/it/riso-pilaf',
  '/fr/riz-pilaf'
);
